/* Phase 6 Company Portal projection. Supabase is the only runtime authority. */
(function(){
  const {useEffect,useState}=React;const ESTADOS=[{id:'pendiente',label:'Pendiente',tone:'amber',icon:'clock'},{id:'revision',label:'En revisión',tone:'blue',icon:'eye'},{id:'aprobada',label:'Aprobada',tone:'green',icon:'checkCircle'},{id:'rechazada',label:'Rechazada',tone:'red',icon:'close'},{id:'entregada',label:'Entregada',tone:'guinda',icon:'check'},{id:'cancelada',label:'Cancelada',tone:'red',icon:'ban'}];const ESTADO=(id)=>ESTADOS.find((x)=>x.id===id)||ESTADOS[0];
  const PENDING_PLAN=Object.freeze({id:'pending',name:'Configuración pendiente',desc:'Sin plan comercial autorizado',precioMensual:0,precioAnual:0,maxProductos:0,popups:false,statsHistory:false,activo:false,order:1,beneficios:[]});
  const listeners=new Set();let companies=[],plans=[],subscriptions=[],requests=[],quotes=[],popupProposals=[],authId=null,phase='idle',error=null,promise=null;const emit=()=>listeners.forEach((fn)=>fn());
  function planRow(p){return Object.freeze({id:p.id,name:p.name,desc:p.description||'',precioMensual:Number(p.monthly_price),precioAnual:Number(p.annual_price),maxProductos:p.max_products,popups:p.allows_popups,statsHistory:p.allows_stats_history,activo:p.enabled,order:p.sort_order,beneficios:p.benefits||[]});}
  function plan(id){return plans.find((p)=>p.id===id)||PENDING_PLAN;}
  window.COMPANY={get PLANS(){return plans.slice();},ESTADOS,ESTADO,PLAN:plan};
  function project(c){const sub=subscriptions.find((s)=>s.company_id===c.id);const ownRequests=requests.filter((x)=>x.company_id===c.id),ownQuotes=quotes.filter((x)=>x.company_id===c.id);return Object.assign({},c,{name:c.display_name||c.name,razon:c.legal_name||'',giro:c.category_raw||'',desc:c.description||'',historia:'',slotLogo:null,gallery:c.gallery_urls||[],video:'',web:c.website_url||'',tel:c.phone_raw||'',email:c.email_raw||'',redes:c.social_links||{},horario:'',sucursales:c.address_raw?[{nombre:'Ubicación',dir:c.address_raw}]:[],mapUrl:'',plan:sub&&sub.plan_id||'pending',billing:sub&&sub.billing_cycle==='monthly'?'mensual':sub&&sub.billing_cycle==='annual'?'anual':'',subStart:sub&&sub.starts_on||null,subEnd:sub&&sub.ends_on||null,subscriptionStatus:sub&&sub.status||'pending',convenioStatus:c.enabled?'vigente':'inactivo',products:[],promos:c.promos||[],stats:{visitas:0,vistasPromos:0,clicksContacto:0,conversion:0,solicitudes:ownRequests.length,cotizaciones:ownQuotes.length}});}
  async function load(force){if(promise){if(!force)return promise;await promise;}phase='loading';emit();promise=(async()=>{try{const repo=window.MarketplaceRepository,admin=window.AdminRepository&&window.AdminRepository.has('company_portal.read');const values=await Promise.all([admin?repo.listPortalCompanies():repo.companyContext(),repo.listPortalPlans(),repo.listPortalSubscriptions(),repo.listRequests(),repo.listQuotes(),window.PopupProposalRepository.list()]);plans=values[1].map(planRow);subscriptions=values[2].slice();requests=values[3].slice();quotes=values[4].slice();popupProposals=values[5].slice();const base=values[0].map(project);for(const co of base)co.promos=(await repo.listPromotions(co.id)).slice();companies=base.map(Object.freeze);if(authId&&!companies.some((x)=>x.id===authId))authId=null;phase='loaded';error=null;}catch(e){companies=[];plans=[];subscriptions=[];requests=[];quotes=[];popupProposals=[];authId=null;phase='error';error=e;}finally{promise=null;}emit();return store;})();return promise;}
  function subStatus(co){if(!co||co.subscriptionStatus==='pending'||!co.subEnd)return 'vencido';if(co.subscriptionStatus!=='active')return 'vencido';const days=Math.ceil((new Date(co.subEnd+'T23:59')-new Date())/86400000);return days<=0?'vencido':days<=30?'porVencer':'activo';}
  const store={ESTADOS,state:()=>({phase,error}),bootstrap:()=>load(false),retry:()=>load(true),plans:()=>plans.slice(),plan,planUsage:(id)=>subscriptions.filter((s)=>s.plan_id===id).length,blankPlan:()=>({id:null,name:'',desc:'',precioMensual:0,precioAnual:0,maxProductos:1,popups:false,statsHistory:false,activo:true,order:plans.length+1,beneficios:[]}),savePlan:async(p)=>{await window.MarketplaceRepository.savePortalPlan(p);await load(true);},removePlan:async(id)=>{await window.MarketplaceRepository.removePortalPlan(id);await load(true);return true;},duplicatePlan:async(id)=>{const p=plan(id);if(p===PENDING_PLAN)return;await store.savePlan(Object.assign({},p,{id:null,name:p.name+' (copia)',order:plans.length+1}));},togglePlan:async(id)=>{const p=plan(id);await store.savePlan(Object.assign({},p,{activo:!p.activo}));},resetPlans:()=>Promise.reject(new Error('NO_PRODUCTIVE_PLAN_RESET')),setCompanyPlan:async(companyId,planId,cycle)=>{await window.MarketplaceRepository.setPortalSubscription(companyId,planId,cycle);await load(true);},
    companies:()=>companies.slice(),get:(id)=>companies.find((x)=>x.id===id)||null,current:()=>companies.find((x)=>x.id===authId)||null,subStatus,planAllows:(co,key)=>Boolean(plan(co&&co.plan)[key]),isAuth:()=>Boolean(authId&&companies.some((x)=>x.id===authId)),authId:()=>authId,
    login:async(id)=>{await load(false);if(!companies.some((x)=>x.id===id))return false;authId=id;emit();return true;},logout:()=>{authId=null;emit();},save:async(co)=>{await window.MarketplaceRepository.updateCompany(co);await load(true);},
    saveProduct:(coId,prod)=>window.catalogStore.save(Object.assign({},prod,{company_id:coId,empresaId:coId})),removeProduct:(_co,id)=>window.catalogStore.remove(id),blankProduct:(kind)=>Object.assign(window.catalogStore.blank('convenio','',authId),{kind:kind||'producto'}),
    savePromo:async(coId,promo)=>{await window.MarketplaceRepository.savePromotion(Object.assign({},promo,{company_id:coId}));await load(true);},removePromo:async(_co,id)=>{await window.MarketplaceRepository.removePromotion(id);await load(true);},blankPromo:()=>({id:null,name:'',start:'',end:'',desc:'',restric:'',disc:0,beneficio:'',active:true,sort_order:((store.current()||{}).promos||[]).length+1}),
    solicitudes:(coId)=>requests.filter((x)=>x.company_id===coId),setEstado:async(id,estado)=>{await window.MarketplaceRepository.updateRequest(id,estado);await load(true);},addComentario:async(id,texto)=>{await window.MarketplaceRepository.updateRequest(id,undefined,texto);await load(true);},stats:(coId)=>(store.get(coId)||{}).stats||{},notifs:(coId)=>{const q=quotes.filter((x)=>x.company_id===coId),r=requests.filter((x)=>x.company_id===coId&&x.estado==='pendiente');const out=[];if(r.length)out.push({icon:'receipt',tone:'amber',title:r.length+' solicitud(es) pendiente(s)',body:'Requieren tu atención'});const pending=q.filter((x)=>x.estado==='solicitada').length;if(pending)out.push({icon:'doc',tone:'blue',title:pending+' cotización(es) por cargar',body:'Afiliados esperan tu presupuesto'});return out;},myPopups:(coId)=>popupProposals.filter((p)=>!coId||p.company_id===coId),submitPopup:async(coId,row)=>{await window.PopupProposalRepository.submit(coId,row);await load(true);},resetAll:()=>Promise.reject(new Error('NO_PRODUCTIVE_COMPANY_RESET')),subscribe:(fn)=>{listeners.add(fn);return()=>listeners.delete(fn)}};
  window.companyStore=store;window.useCompanyStore=function(){const[,setV]=useState(0);useEffect(()=>store.subscribe(()=>setV((n)=>n+1)),[]);useEffect(()=>{store.bootstrap();},[]);return store;};
})();
