/* Claude finance structure + managed non-financial presentation metadata.
   Financial conditions are supplied only by the protected server resolver. */
(function(){
  const FINANCIAL_LEGACY_READ_ONLY='FINANCIAL_LEGACY_READ_ONLY';
  const repo=window.AdminCutoverRepository,listeners=new Set();let rows=[];
  const base=[
    {id:'liquidez',title:'Liquidez inmediata',sub:'Dinero cuando lo necesitas',tone:'guinda',items:[{id:'prestamo',label:'Suti Préstamo',icon:'cash',tagline:'Consulta tus opciones',meta:'Condiciones según tu perfil',hero:true},{id:'nomina',label:'Adelanto de nómina',icon:'calendar',tagline:'Tu quincena hoy',meta:'Consulta disponibilidad'},{id:'caja',label:'Caja chica',icon:'money',tagline:'Apoyo exprés',meta:'Consulta disponibilidad'}]},
    {id:'patrimonio',title:'Crece tu patrimonio',sub:'Ahorro e inversión sindical',tone:'green',items:[{id:'ahorro',label:'Ahorro Voluntario',icon:'piggy',tagline:'Consulta tu ahorro',meta:'Tu información al día'},{id:'inversion',label:'Portafolio de Inversión',icon:'chart',tagline:'Haz crecer tu dinero',meta:'Conoce las opciones'}]},
    {id:'bienes',title:'Bienes y financiamientos',sub:'Compra a plazos con tu sindicato',tone:'blue',items:[{id:'auto',label:'Suti Auto',icon:'car',tagline:'Autos disponibles',meta:'Explora opciones'},{id:'renta',label:'Renta Car',icon:'key',tagline:'Vehículos en renta',meta:'Explora opciones'},{id:'casa',label:'Suti Casa',icon:'house',tagline:'Propiedades',meta:'Explora opciones'},{id:'terrenos',label:'Suti Terrenos',icon:'land',tagline:'Lotes disponibles',meta:'Explora opciones'},{id:'solar',label:'Paneles Solares',icon:'solar',tagline:'Ahorra en luz',meta:'Explora opciones'},{id:'aires',label:'Aires Acondicionados',icon:'ac',tagline:'Equipos disponibles',meta:'Explora opciones'},{id:'puertas',label:'Puertas de Seguridad',icon:'door',tagline:'Protege tu hogar',meta:'Explora opciones'},{id:'computo',label:'Equipos de Cómputo',icon:'laptop',tagline:'Tecnología',meta:'Explora opciones'}]},
    {id:'bienestar',title:'Bienestar y experiencias',sub:'Salud, viajes y más',tone:'amber',items:[{id:'farma',label:'Suti Farma',icon:'pharmacy',tagline:'Medicamentos disponibles',meta:'Explora opciones'},{id:'cirugias',label:'Suti Cirugías',icon:'surgery',tagline:'Estéticas y mayores',meta:'Conoce el beneficio'},{id:'tours',label:'Suti Tours',icon:'plane',tagline:'Viajes y paquetes',meta:'Explora opciones'},{id:'market',label:'Suti Market',icon:'cart',tagline:'Productos del hogar',meta:'Conoce el beneficio'},{id:'rifas',label:'Suti Rifas',icon:'ticket',tagline:'Boletos activos',meta:'Consulta disponibilidad'},{id:'donativos',label:'Donativos',icon:'heart',tagline:'Apoya una causa',meta:'Conoce el beneficio'}]}
  ];
  const emit=()=>listeners.forEach(fn=>fn()),fail=e=>console.error('Finance presentation authority error',e),row=k=>rows.find(x=>x.item_key===k);
  async function load(){try{rows=await repo.listFinancePresentation();emit();}catch(e){fail(e);}}
  function groups(){return base.map((g,gi)=>{const gr=row('group:'+g.id)||{};return Object.assign({},g,{title:gr.label_override||g.title,sub:gr.description_override||g.sub,items:g.items.map((it,ii)=>{const r=row(it.id)||{};return Object.assign({},it,{label:r.label_override||it.label,tagline:r.description_override||it.tagline,visible:r.enabled!==false,order:r.sort_order||ii});}).sort((a,b)=>a.order-b.order),order:gr.sort_order||gi});}).sort((a,b)=>a.order-b.order);}
  const save=(key,gid,p)=>repo.saveFinancePresentation({item_key:key,group_key:gid,label_override:p.label_override||null,description_override:p.description_override||null,enabled:p.enabled!==false,sort_order:p.sort_order||0}).then(load).catch(fail);
  const store={groups,groupsLive:()=>groups(),allItems:()=>groups().flatMap(g=>g.items),findItem:id=>groups().flatMap(g=>g.items).find(x=>x.id===id)||null,recs:()=>[],recsLive:()=>[],getRec:()=>null,
    saveGroup:(id,p)=>{const g=groups().find(x=>x.id===id);save('group:'+id,id,{label_override:p.title==null?g.title:p.title,description_override:p.sub==null?g.sub:p.sub,enabled:true,sort_order:g.order});},
    saveItem:(gid,id,p)=>{const it=store.findItem(id);save(id,gid,{label_override:p.label==null?it.label:p.label,description_override:p.tagline==null?it.tagline:p.tagline,enabled:p.visible==null?it.visible:p.visible,sort_order:it.order});},
    toggleItem:(gid,id)=>{const it=store.findItem(id);store.saveItem(gid,id,{visible:it.visible===false});},moveItem:(gid,id,dir)=>{const g=groups().find(x=>x.id===gid),i=g.items.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=g.items.length)return;const a=g.items[i],b=g.items[j];Promise.all([save(a.id,gid,{label_override:a.label,description_override:a.tagline,enabled:a.visible,sort_order:j}),save(b.id,gid,{label_override:b.label,description_override:b.tagline,enabled:b.visible,sort_order:i})]);},
    resetAll:()=>Promise.all(rows.map(r=>window.SutiSupabase.getClient().from('finance_catalog_presentation').delete().eq('item_key',r.item_key))).then(load),
    blankRec:()=>null,saveRec:()=>{},removeRec:()=>{},toggleRec:()=>{},moveRec:()=>{},subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}};
  window.finCatStore=store;window.useFinCatStore=function(){const[,f]=React.useState(0);React.useEffect(()=>store.subscribe(()=>f(n=>n+1)),[]);return store;};setTimeout(load,0);
})();
