/* Supabase authority for versioned request workflow definitions and tracking. */
(function(){
  const repo=window.AdminCutoverRepository,listeners=new Set();let flows=[],tracks={},requests=[],phase='idle',error=null,initialLoad=null;
  const TIPOS=[{id:'solicitud',label:'Solicitud',icon:'receipt'},{id:'convenio',label:'Convenio',icon:'handshake'},{id:'servicio',label:'Servicio',icon:'grid'},{id:'tramite',label:'Trámite',icon:'doc'}],RESULTADOS=[{id:'proceso',label:'En proceso',tone:'blue',icon:'clock'},{id:'exito',label:'Cierre exitoso',tone:'green',icon:'checkCircle'},{id:'fallo',label:'No procede',tone:'red',icon:'close'}],RESPONSABLES=['Afiliado','Finanzas','Sindicato','Empresa / proveedor','Sistema'],REQUEST_STATUSES=[{id:'submitted',label:'Enviada'},{id:'in_review',label:'En revisión'},{id:'requires_financial_processing',label:'En revisión financiera'},{id:'approved',label:'Aprobada'},{id:'rejected',label:'No aprobada'},{id:'cancelled',label:'Cancelada'}];
  const mapType={request:'solicitud',agreement:'convenio',service:'servicio',procedure:'tramite'},dbType={solicitud:'request',convenio:'agreement',servicio:'service',tramite:'procedure'},mapResult={process:'proceso',success:'exito',failure:'fallo'},dbResult={proceso:'process',exito:'success',fallo:'failure'};
  const emit=()=>listeners.forEach(fn=>fn()),uid=()=>crypto.randomUUID(),sorted=a=>a.slice().sort((x,y)=>(x.orden||0)-(y.orden||0)||String(x.id).localeCompare(String(y.id)));
  const stage=s=>({id:s.id,nombre:s.name,descripcion:s.description,orden:s.sort_order,resultado:mapResult[s.outcome],responsable:s.responsible,slaDias:s.sla_days,registraFecha:s.captures_date,servicios:s.service_keys||[],estadoRefs:String(s.status_reference||'').split(',').map(x=>x.trim()).filter(Boolean),activo:s.enabled!==false});
  const flow=r=>({id:r.id,nombre:r.name,descripcion:r.description,tipo:mapType[r.workflow_type],servicios:r.service_keys||[],activo:r.enabled,orden:r.sort_order,version:r.version,etapas:(r.operational_workflow_stages||[]).map(stage).sort((a,b)=>a.orden-b.orden)});
  async function load(){phase='loading';error=null;emit();try{const out=await Promise.all([repo.listWorkflows(),repo.listTracking(),repo.listRequestWorkflowTracking()]);flows=out[0].map(flow);tracks={};out[1].forEach(x=>tracks[x.request_id]={flujoId:x.workflow_id,etapaId:x.current_stage_id,fechas:x.stage_dates||{}});requests=out[2]||[];phase='loaded';}catch(e){phase='error';error=e;console.error('Workflow authority error',e);}emit();return store;}
  function servicesCatalog(){const out=[{id:'request:loan',label:'Financiamiento / préstamo',grupo:'Tipos de solicitud',icon:'cash'},{id:'request:membership',label:'Membresía',grupo:'Tipos de solicitud',icon:'card'},{id:'request:quote',label:'Cotización',grupo:'Tipos de solicitud',icon:'doc'},{id:'request:benefit',label:'Beneficio',grupo:'Tipos de solicitud',icon:'gift'}];(window.finCatStore.groups()||[]).forEach(g=>g.items.forEach(i=>out.push({id:i.id,label:i.label,grupo:g.title,icon:i.icon})));return out;}
  const store={TIPOS,RESULTADOS,RESPONSABLES,REQUEST_STATUSES,TIPO:id=>TIPOS.find(x=>x.id===id)||TIPOS[0],RESULTADO:id=>RESULTADOS.find(x=>x.id===id)||RESULTADOS[0],state:()=>({phase,error}),servicesCatalog,serviceLabel:id=>(servicesCatalog().find(x=>x.id===id)||{label:id}).label,stamp:()=>new Date().toISOString(),subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);},all:()=>sorted(flows),active:()=>sorted(flows.filter(x=>x.activo)),get:id=>flows.find(x=>x.id===id)||null,etapas:id=>{const f=store.get(id);return f?sorted(f.etapas):[];},etapasActivas:id=>store.etapas(id).filter(e=>e.activo),count:()=>flows.length,etapasCount:()=>flows.reduce((n,f)=>n+f.etapas.length,0),requests:()=>requests.slice(),blank:()=>({id:null,nombre:'',descripcion:'',tipo:'solicitud',servicios:[],activo:false,etapas:[]}),blankEtapa:()=>({id:null,nombre:'',descripcion:'',resultado:'proceso',responsable:'Sindicato',slaDias:null,registraFecha:true,servicios:[],estadoRefs:[],activo:true}),
    async save(f){const id=f.id||uid();await repo.saveWorkflow({id,name:f.nombre,description:f.descripcion||'',workflow_type:dbType[f.tipo],service_keys:f.servicios||[],enabled:f.activo===true,sort_order:f.orden||flows.length});await load();return id;},async remove(id){await repo.retireWorkflow(id);await load();},duplicate:id=>{const f=store.get(id);if(!f)return null;return store.save(Object.assign({},f,{id:null,nombre:f.nombre+' (copia)',activo:false,etapas:[]}));},setActivo:async(id,v)=>{const f=store.get(id);if(f)return store.save(Object.assign({},f,{activo:v}));},
    moveFlow:async(id,dir)=>{const a=store.all(),i=a.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i].orden,a[j].orden]=[j,i];await Promise.all([repo.saveWorkflow({id:a[i].id,name:a[i].nombre,description:a[i].descripcion,workflow_type:dbType[a[i].tipo],service_keys:a[i].servicios,enabled:a[i].activo,sort_order:a[i].orden}),repo.saveWorkflow({id:a[j].id,name:a[j].nombre,description:a[j].descripcion,workflow_type:dbType[a[j].tipo],service_keys:a[j].servicios,enabled:a[j].activo,sort_order:a[j].orden})]);await load();},
    async saveEtapa(fid,e){await repo.saveStage({id:e.id||uid(),workflow_id:fid,name:e.nombre,description:e.descripcion||'',responsible:e.responsable||'Sindicato',outcome:dbResult[e.resultado]||'process',sla_days:e.slaDias==null?null:Number(e.slaDias),service_keys:e.servicios||[],status_reference:(e.estadoRefs||[]).join(',')||null,captures_date:e.registraFecha!==false,sort_order:e.orden==null?store.etapas(fid).length*10+10:e.orden,enabled:e.activo!==false});await load();},async removeEtapa(fid,id){await repo.retireStage(id);await load();},
    moveEtapa:async(fid,id,dir)=>{const a=store.etapas(fid),i=a.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];await repo.reorderStages(fid,a.map(x=>x.id));await load();},
    flowFor:(sid,tipo)=>store.active().find(f=>(!tipo||f.tipo===tipo)&&f.servicios.includes(sid))||null,etapasFor:(fid,sid)=>store.etapasActivas(fid).filter(e=>!sid||!e.servicios.length||e.servicios.includes(sid)),track:id=>tracks[id]||null,
    setEtapaActual:async(id,fid,eid)=>{await repo.saveTracking({request_id:id,workflow_id:fid,current_stage_id:eid,stage_dates:Object.assign({},(tracks[id]||{}).fechas,{[eid]:new Date().toISOString()})});await load();},setFecha:async(id,eid,date)=>{const t=tracks[id]||{},d=Object.assign({},t.fechas||{});if(date)d[eid]=date;else delete d[eid];await repo.saveTracking({request_id:id,workflow_id:t.flujoId,current_stage_id:t.etapaId,stage_dates:d});await load();},
    steps:(fid,o)=>store.etapasFor(fid,o&&o.servicioId).map(e=>({label:e.nombre,desc:e.descripcion,date:(o&&o.fechas||{})[e.id],done:false,active:e.id===(o&&o.etapaId),responsable:e.responsable,sla:e.slaDias})),restore:()=>load()};
  const ensureLoaded=()=>initialLoad||(initialLoad=load());
  window.flowStore=store;window.FLUJOS={TIPOS,RESULTADOS,RESPONSABLES,REQUEST_STATUSES};window.useFlowStore=function(){const[,f]=React.useState(0);React.useEffect(()=>store.subscribe(()=>f(n=>n+1)),[]);React.useEffect(()=>{ensureLoaded();},[]);return store;};
})();
