/* Supabase authority for non-financial workflow definitions and tracking. */
(function(){
  const repo=window.AdminCutoverRepository,listeners=new Set();let flows=[],tracks={};
  const TIPOS=[{id:'solicitud',label:'Solicitud',icon:'receipt'},{id:'convenio',label:'Convenio',icon:'handshake'},{id:'servicio',label:'Servicio',icon:'grid'},{id:'tramite',label:'Trámite',icon:'doc'}],RESULTADOS=[{id:'proceso',label:'En proceso',tone:'blue',icon:'clock'},{id:'exito',label:'Cierre exitoso',tone:'green',icon:'checkCircle'},{id:'fallo',label:'No procede',tone:'red',icon:'close'}],RESPONSABLES=['Afiliado','Finanzas','Sindicato','Empresa / proveedor','Sistema'];
  const mapType={request:'solicitud',agreement:'convenio',service:'servicio',procedure:'tramite'},dbType={solicitud:'request',convenio:'agreement',servicio:'service',tramite:'procedure'},mapResult={process:'proceso',success:'exito',failure:'fallo'},dbResult={proceso:'process',exito:'success',fallo:'failure'};
  const emit=()=>listeners.forEach(fn=>fn()),fail=e=>console.error('Workflow authority error',e),uid=()=>crypto.randomUUID();
  const stage=s=>({id:s.id,nombre:s.name,descripcion:s.description,orden:s.sort_order,resultado:mapResult[s.outcome],responsable:s.responsible,slaDias:s.sla_days,registraFecha:s.captures_date,servicios:s.service_keys||[],estadoRef:s.status_reference||''});
  const flow=r=>({id:r.id,nombre:r.name,descripcion:r.description,tipo:mapType[r.workflow_type],servicios:r.service_keys||[],activo:r.enabled,orden:r.sort_order,etapas:(r.operational_workflow_stages||[]).map(stage).sort((a,b)=>a.orden-b.orden)});
  async function load(){try{const out=await Promise.all([repo.listWorkflows(),repo.listTracking()]);flows=out[0].map(flow);tracks={};out[1].forEach(x=>tracks[x.request_id]={flujoId:x.workflow_id,etapaId:x.current_stage_id,fechas:x.stage_dates||{}});emit();}catch(e){fail(e);}}
  const sorted=a=>a.slice().sort((x,y)=>(x.orden||0)-(y.orden||0));
  function servicesCatalog(){const out=[];(window.finCatStore.groups()||[]).forEach(g=>g.items.forEach(i=>out.push({id:i.id,label:i.label,grupo:g.title,icon:i.icon})));return out;}
  const store={TIPOS,RESULTADOS,RESPONSABLES,TIPO:id=>TIPOS.find(x=>x.id===id)||TIPOS[0],RESULTADO:id=>RESULTADOS.find(x=>x.id===id)||RESULTADOS[0],servicesCatalog,serviceLabel:id=>(servicesCatalog().find(x=>x.id===id)||{label:id}).label,stamp:()=>new Date().toLocaleString('es-MX'),subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);},all:()=>sorted(flows),active:()=>sorted(flows.filter(x=>x.activo)),get:id=>flows.find(x=>x.id===id)||null,etapas:id=>{const f=store.get(id);return f?sorted(f.etapas):[];},count:()=>flows.length,etapasCount:()=>flows.reduce((n,f)=>n+f.etapas.length,0),blank:()=>({id:null,nombre:'',descripcion:'',tipo:'solicitud',servicios:[],activo:true,etapas:[]}),blankEtapa:()=>({id:null,nombre:'',descripcion:'',resultado:'proceso',responsable:'Sindicato',slaDias:null,registraFecha:true,servicios:[],estadoRef:''}),
    save(f){const id=f.id||uid();repo.saveWorkflow({id,name:f.nombre,description:f.descripcion||'',workflow_type:dbType[f.tipo],service_keys:f.servicios||[],enabled:f.activo!==false,sort_order:f.orden||flows.length}).then(load).catch(fail);return id;},remove:id=>repo.deleteWorkflow(id).then(load).catch(fail),duplicate:id=>{const f=store.get(id);if(!f)return null;return store.save(Object.assign({},f,{id:null,nombre:f.nombre+' (copia)',etapas:[]}));},setActivo:(id,v)=>{const f=store.get(id);if(f)store.save(Object.assign({},f,{activo:v}));},
    moveFlow:(id,dir)=>{const a=store.all(),i=a.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i].orden,a[j].orden]=[j,i];Promise.all([repo.saveWorkflow({id:a[i].id,name:a[i].nombre,description:a[i].descripcion,workflow_type:dbType[a[i].tipo],service_keys:a[i].servicios,enabled:a[i].activo,sort_order:a[i].orden}),repo.saveWorkflow({id:a[j].id,name:a[j].nombre,description:a[j].descripcion,workflow_type:dbType[a[j].tipo],service_keys:a[j].servicios,enabled:a[j].activo,sort_order:a[j].orden})]).then(load).catch(fail);},
    saveEtapa:(fid,e)=>repo.saveStage({id:e.id||uid(),workflow_id:fid,name:e.nombre,description:e.descripcion||'',responsible:e.responsable||'Sindicato',outcome:dbResult[e.resultado]||'process',sla_days:e.slaDias||null,service_keys:e.servicios||[],status_reference:e.estadoRef||null,captures_date:e.registraFecha!==false,sort_order:e.orden==null?store.etapas(fid).length:e.orden}).then(load).catch(fail),removeEtapa:(fid,id)=>repo.deleteStage(id).then(load).catch(fail),
    moveEtapa:(fid,id,dir)=>{const a=store.etapas(fid),i=a.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i].orden,a[j].orden]=[j,i];Promise.all([store.saveEtapa(fid,a[i]),store.saveEtapa(fid,a[j])]);},
    flowFor:(sid,tipo)=>store.active().find(f=>(!tipo||f.tipo===tipo)&&f.servicios.includes(sid))||store.active().find(f=>f.tipo===(tipo||'solicitud'))||null,etapasFor:(fid,sid)=>store.etapas(fid).filter(e=>!sid||!e.servicios.length||e.servicios.includes(sid)),track:id=>tracks[id]||null,
    setEtapaActual:(id,fid,eid)=>repo.saveTracking({request_id:id,workflow_id:fid,current_stage_id:eid,stage_dates:Object.assign({},(tracks[id]||{}).fechas,{[eid]:new Date().toISOString()})}).then(load).catch(fail),setFecha:(id,eid,date)=>{const t=tracks[id]||{},d=Object.assign({},t.fechas||{});if(date)d[eid]=date;else delete d[eid];repo.saveTracking({request_id:id,workflow_id:t.flujoId,current_stage_id:t.etapaId,stage_dates:d}).then(load).catch(fail);},clearTrack:()=>{},
    steps:(fid,o)=>store.etapasFor(fid,o&&o.servicioId).map(e=>({label:e.nombre,desc:e.descripcion,date:(o&&o.fechas||{})[e.id],done:false,active:e.id===(o&&o.etapaId),responsable:e.responsable,sla:e.slaDias})),forSolicitud:s=>{if(!s)return null;const sid=s.servicioId||(s._fin&&(s._fin.productoId||s._fin.itemId)),f=store.flowFor(sid,'solicitud');if(!f)return null;const id=s.id||s.folio,t=tracks[id]||{},es=store.etapasFor(f.id,sid),eid=t.etapaId||(es[0]||{}).id;return{flow:f,refId:id,servicioId:sid,etapaActual:es.find(e=>e.id===eid),steps:store.steps(f.id,{servicioId:sid,etapaId:eid,fechas:t.fechas||{}})};},restore:()=>load()};
  let initialLoad=null;const ensureLoaded=()=>initialLoad||(initialLoad=load());
  window.flowStore=store;window.FLUJOS={TIPOS,RESULTADOS,RESPONSABLES};window.useFlowStore=function(){const[,f]=React.useState(0);React.useEffect(()=>store.subscribe(()=>f(n=>n+1)),[]);React.useEffect(()=>{ensureLoaded();},[]);return store;};
})();
