/* Request history projection. Supabase workflow snapshots own every timeline. */
(function(){
  const{useState,useEffect}=React;const listeners=new Set();let rows=[],phase='idle',error=null,promise=null;const emit=()=>listeners.forEach(fn=>fn());
  function timeline(r){const state=r.workflow_state||{};return{available:state.available===true,message:state.message||'Seguimiento no disponible',activeNote:state.active_note||null,workflowName:state.workflow_name||'',workflowVersion:state.workflow_version||null,steps:(state.stages||[]).map((stage)=>({id:stage.id,label:stage.label,desc:stage.description||'',responsable:stage.responsible||'',sla:stage.sla_days,date:stage.date?new Date(stage.date).toLocaleString('es-MX'):null,done:stage.state==='done',active:stage.state==='current'}))};}
  function common(r,kind){const state=r.status||'submitted',approved=['approved','completed'].includes(state),rejected=['rejected','cancelled'].includes(state),flow=timeline(r),isLoan=kind==='loan',isQuote=kind==='quote',isProductPayment=!isLoan&&!isQuote&&r.financial_processing_status!=null&&r.requested_amount!=null;return Object.freeze({id:r.folio||r.id,sourceId:r.id,ts:new Date(r.created_at).getTime(),kind,icon:isLoan?'receipt':isQuote?'doc':isProductPayment?'cash':'cart',tipo:r.productoNombre||(isLoan?'Suti Préstamo':isQuote?'Cotización comercial':'Solicitud de beneficio'),monto:isLoan||isProductPayment?(r.requested_amount==null?r.importe:Number(r.requested_amount)):isQuote?(approved&&r.quoted_amount!=null?Number(r.quoted_amount):null):(r.importe==null?null:Number(r.importe)*Number(r.quantity||1)),estado:rejected?'rechazado':approved?'aprobado':'revision',fecha:new Date(r.created_at).toLocaleDateString('es-MX'),plazo:(isLoan||isProductPayment)&&r.requested_term&&r.requested_term_semantics?`${r.requested_term} ${r.requested_term_semantics}`:isQuote?(approved?'Cotización recibida':'Por cotizar'):(state==='requires_financial_processing'?'Revisión financiera':'Solicitud registrada'),subtipo:isLoan?'Préstamo':isProductPayment?'Producto vía nómina':r.empresaNombre||r.program_id||'',motivo:rejected?(r.company_notes||'La solicitud fue cerrada por el área responsable.'):'',steps:flow.steps,workflowAvailable:flow.available,workflowMessage:flow.message,activeNote:flow.activeNote,workflowName:flow.workflowName,workflowVersion:flow.workflowVersion});}
  const requestRow=(r)=>common(r,'benefit'),quoteRow=(r)=>common(r,'quote'),loanRow=(r)=>common(r,'loan');
  async function load(force){if(promise&&!force)return promise;phase='loading';emit();promise=(async()=>{try{const requests=await window.ProgramRequestRepository.listHistory();rows=requests.map((r)=>r.program_id==='prestamo'?loanRow(r):r.request_type==='quote'?quoteRow(r):requestRow(r)).sort((a,b)=>b.ts-a.ts);phase='loaded';error=null;}catch(e){rows=[];phase='error';error=e;}emit();return store;})();return promise;}
  const store={state:()=>({phase,error}),all:()=>rows.slice(),load,invalidate:()=>{promise=null;rows=[];phase='idle';error=null;emit();},retry:()=>{promise=null;return load(true);},subscribe:(fn)=>{listeners.add(fn);return()=>listeners.delete(fn)}};
  window.operationsStore=store;window.useOperationsStore=function(){const[,setV]=useState(0);useEffect(()=>store.subscribe(()=>setV(n=>n+1)),[]);useEffect(()=>{if(store.state().phase==='idle')store.load(false);},[]);return store;};
})();
