/* Phase 5 non-financial operations projection. Supabase is authoritative. */
(function(){
  const{useState,useEffect}=React;const listeners=new Set();let rows=[],phase='idle',error=null,promise=null;const emit=()=>listeners.forEach(fn=>fn());const step=(label,done,active,date)=>({label,done,active,date});
  function requestRow(r){const state=r.status||'submitted',approved=['approved','completed'].includes(state),rejected=['rejected','cancelled'].includes(state),review=['review','in_review','requires_financial_processing'].includes(state);return Object.freeze({id:r.folio||r.id,sourceId:r.id,ts:new Date(r.created_at).getTime(),kind:'benefit',icon:'cart',tipo:r.productoNombre||'Solicitud de beneficio',monto:r.importe==null?null:Number(r.importe)*Number(r.quantity||1),estado:rejected?'rechazado':approved?'aprobado':'revision',fecha:new Date(r.created_at).toLocaleDateString('es-MX'),plazo:state==='requires_financial_processing'?'Revisión financiera':'Solicitud registrada',subtipo:r.empresaNombre||r.program_id||'',motivo:rejected?(r.company_notes||'El área responsable marcó la solicitud como no aprobada.'):'',steps:[step('Solicitud enviada',true,false,new Date(r.created_at).toLocaleDateString('es-MX')),step(state==='requires_financial_processing'?'Revisión financiera':'Revisión del área responsable',approved||rejected,review||(!approved&&!rejected)),step(approved?'Solicitud aprobada':rejected?'Solicitud no aprobada':'Resolución',approved||rejected,false)]});}
  function quoteRow(r){const quoted=['quoted','approved'].includes(r.status),rejected=['expired','rejected','cancelled'].includes(r.status);return Object.freeze({id:r.folio||r.id,sourceId:r.id,ts:new Date(r.created_at).getTime(),kind:'quote',icon:'doc',tipo:r.productoNombre||'Cotización comercial',monto:quoted&&r.quoted_amount!=null?Number(r.quoted_amount):null,estado:rejected?'rechazado':quoted?'aprobado':'revision',fecha:new Date(r.created_at).toLocaleDateString('es-MX'),plazo:quoted?'Cotización recibida':'Por cotizar',subtipo:r.empresaNombre||r.program_id||'',motivo:rejected?'La cotización fue cerrada.':'',steps:[step('Cotización solicitada',true,false,new Date(r.created_at).toLocaleDateString('es-MX')),step('Preparación del área responsable',quoted||rejected,!quoted&&!rejected),step(quoted?'Cotización disponible':rejected?'Cotización cerrada':'Respuesta',quoted||rejected,false,quoted&&(r.responded_at||r.quoted_at)?new Date(r.responded_at||r.quoted_at).toLocaleDateString('es-MX'):null)]});}
  async function load(force){if(promise&&!force)return promise;phase='loading';emit();promise=(async()=>{try{const requests=await window.ProgramRequestRepository.listHistory();rows=requests.map((r)=>r.request_type==='quote'?quoteRow(r):requestRow(r)).sort((a,b)=>b.ts-a.ts);phase='loaded';error=null;}catch(e){rows=[];phase='error';error=e;}emit();return store;})();return promise;}
  const store={state:()=>({phase,error}),all:()=>rows.slice(),load,retry:()=>{promise=null;return load(true);},subscribe:(fn)=>{listeners.add(fn);return()=>listeners.delete(fn)}};
  window.operationsStore=store;window.useOperationsStore=function(){const[,setV]=useState(0);useEffect(()=>store.subscribe(()=>setV(n=>n+1)),[]);useEffect(()=>{if(store.state().phase==='idle')store.load(false);},[]);return store;};
})();
