/* Phase 3 commercial quote store: Supabase-backed, no browser persistence. */
(function(){
  const {useEffect,useState}=React;const ESTADOS=[{id:'solicitada',label:'Esperando cotización',tone:'amber',icon:'clock'},{id:'cotizada',label:'Cotización lista',tone:'green',icon:'checkCircle'},{id:'vencida',label:'Vencida',tone:'red',icon:'ban'}];const ESTADO=(id)=>ESTADOS.find((x)=>x.id===id)||ESTADOS[0];window.COTIZA={ESTADOS,ESTADO};
  const listeners=new Set();let rows=[],phase='idle',error=null,promise=null;const emit=()=>listeners.forEach((fn)=>fn());
  function enrich(row){const product=window.catalogStore&&window.catalogStore.get(row.productoId);return Object.freeze(Object.assign({},row,{productoNombre:row.productoNombre||(product&&product.nombre)||'Producto',empresaNombre:row.empresaNombre||(product&&product.empresaNombre)||'Proveedor',usuario:{id:row.affiliate_id,nombre:'Afiliado',sindicato:'—',categoria:'—'},mensaje:row.message||'',firma:row.signature_data||null}));}
  async function load(force){if(promise&&!force)return promise;phase='loading';emit();promise=(async()=>{try{rows=(await window.MarketplaceRepository.listQuotes()).map(enrich);phase='loaded';error=null;}catch(e){rows=[];phase='error';error=e;}emit();return store;})();return promise;}
  const store={ESTADOS,ESTADO,state:()=>({phase,error}),bootstrap:()=>load(false),retry:()=>{promise=null;return load(true);},
    providerFor:(id)=>{const p=window.catalogStore&&window.catalogStore.get(id);return p?{id:p.empresaId,name:p.empresaNombre}:null;},requiresQuote:(id)=>{const p=window.catalogStore&&window.catalogStore.get(id);return Boolean(p&&p.cotiza);},
    solicitar:async(opts)=>{const o=opts||{};const rec=enrich(await window.MarketplaceRepository.createQuote(o.productoId,o.mensaje,o.firma,o.terminos&&o.terminos.aceptado,o.idempotencyKey));await load(true);return rec;},
    cotizar:async(id,data)=>{const d=data||{};let valid=null;if(/^\d{4}-\d{2}-\d{2}$/.test(d.vigencia||''))valid=d.vigencia;else{const days=parseInt(d.vigencia,10)||15;const date=new Date();date.setDate(date.getDate()+days);valid=date.toISOString().slice(0,10);}await window.MarketplaceRepository.respondQuote(id,d.monto,d.nota,valid);await load(true);},
    markVisto:async(id)=>{await window.MarketplaceRepository.markQuoteSeen(id);await load(true);},all:()=>rows.slice(),get:(id)=>rows.find((x)=>x.id===id)||null,mine:()=>rows.slice(),latestFor:(id)=>rows.filter((x)=>x.productoId===id).sort((a,b)=>(b.ts||0)-(a.ts||0))[0]||null,forCompany:(id)=>rows.filter((x)=>x.empresaId===id),pendientes:()=>rows.filter((x)=>x.estado==='solicitada').length,readyUnseen:()=>rows.filter((x)=>x.estado==='cotizada'&&!x.visto),resetAll:()=>Promise.reject(new Error('NO_PRODUCTIVE_QUOTE_RESET')),subscribe:(fn)=>{listeners.add(fn);return()=>listeners.delete(fn)}};
  window.quoteStore=store;window.useQuoteStore=function(){const[,setV]=useState(0);useEffect(()=>store.subscribe(()=>setV((n)=>n+1)),[]);useEffect(()=>{store.bootstrap();},[]);return store;};
})();
