(function(){
 'use strict';
 const h=React.createElement,{useState,useEffect,useRef}=React;
 const css='.svp-rh{margin-top:20px}.svp-rh-card{background:white;border:1px solid var(--hairline);border-radius:14px;padding:24px}.svp-rh fieldset{border:0;padding:0;margin:0 0 32px;min-width:0}.svp-rh fieldset:last-child{margin-bottom:0}.svp-rh legend{width:100%;padding:0;margin-bottom:12px;font-weight:800;font-size:14px}.svp-rh legend small{float:right;color:var(--ink-3);font-size:12px;font-weight:400}.svp-rh-options{display:flex;flex-wrap:wrap;gap:8px}.svp-rh-choice{position:relative;cursor:pointer}.svp-rh-choice input{position:absolute;opacity:0;width:1px;height:1px}.svp-rh-choice span{display:block;border:1px solid var(--hairline-strong);border-radius:999px;padding:10px 16px;font-size:14px;min-height:42px}.svp-rh-choice input:checked+span{background:var(--guinda-50);color:var(--guinda);border-color:var(--guinda)}.svp-rh-choice input:focus-visible+span{outline:2px solid var(--guinda);outline-offset:3px}.svp-rh fieldset:disabled{opacity:.55}.svp-rh-submit{display:block!important;width:min(100%,360px);margin:16px auto 0;background:var(--guinda)!important;color:white!important}.svp-rh-help{font-size:13px;color:var(--ink-2);line-height:1.5;margin:12px 0}@container savings-panel (max-width:450px){.svp-rh-card{padding:18px}.svp-rh-choice span{padding:10px 13px}}';
 const messages={SAVINGS_RH_DATE_INVALID:'La fecha seleccionada no existe. Revisa el mes y el día.',SAVINGS_RH_SELECTION_INVALID:'Selecciona un tipo y año válidos.',SAVINGS_REPORT_DENIED:'No tienes permiso para generar reportes de Ahorro.',SAVINGS_RH_EMPTY:'No hay instrucciones de descuento para el periodo seleccionado.',SAVINGS_RH_HISTORY_UNAVAILABLE:'No hay planes fechados suficientes para generar el periodo completo. No se sustituyen por saldos ni rendimientos históricos.',SAVINGS_RH_IDENTITY_INVALID:'Hay un Folio sin identidad o nombre válido en Afiliados. Revisa las incidencias antes de exportar.',SAVINGS_RH_PLAN_CONFLICT:'Hay planes de descuento incompletos o superpuestos. Revisa las incidencias antes de exportar.',SAVINGS_RH_AMOUNT_INVALID:'Hay un importe no válido. No se generó el archivo.',SAVINGS_CONTEXT_CHANGED:'Cambió la sesión. Vuelve a abrir Reporte RH.',SAVINGS_RH_FILE_INVALID:'No se recibió un Excel válido. Intenta nuevamente.'};
 function SavingsRhReport({today}){
  const date=today||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Hermosillo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const currentYear=Number(date.slice(0,4)),[type,setType]=useState('mensual'),[year,setYear]=useState(currentYear),[month,setMonth]=useState(Number(date.slice(5,7))),[day,setDay]=useState(15);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false),controller=useRef(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  function change(setter,value){setter(value);setError('');setSuccess(false);}
  function choices(title,name,values,value,setter,disabled=false){return h('fieldset',{disabled:busy||disabled},h('legend',null,title,h('small',null,disabled?'No aplica al anual':'Requerido')),h('div',{className:'svp-rh-options'},values.map(([key,label])=>h('label',{key,className:'svp-rh-choice'},h('input',{type:'radio',name:'savings-rh-'+name,value:key,checked:value===key,required:!disabled,onChange:()=>change(setter,key)}),h('span',null,label)))));}
  async function submit(event){event.preventDefault();if(controller.current)return;const request=new AbortController();controller.current=request;setBusy(true);setError('');setSuccess(false);
   try{await window.SavingsRhRepository.download({type,year,month,day},request.signal);if(!request.signal.aborted)setSuccess(true);}
   catch(e){if(!request.signal.aborted)setError(messages[e.message]||'No se pudo generar el reporte. Intenta nuevamente; si persiste, revisa tus permisos y la conexión.');}
   finally{controller.current=null;if(!request.signal.aborted)setBusy(false);}
  }
  return h('form',{className:'svp-rh',onSubmit:submit,'aria-label':'Reporte RH','aria-busy':busy},h('style',null,css),
   h('div',{className:'svp-rh-card'},choices('Tipo reporte','type',[['mensual','mensual'],['anual','anual']],type,setType),choices('Año','year',Array.from({length:5},(_,i)=>[currentYear-2+i,String(currentYear-2+i)]),year,setYear),choices('Mes','month',window.SavingsRhRepository.months.map((name,i)=>[i+1,name]),month,setMonth,type==='anual'),choices('Día','day',[5,15,28,30].map(value=>[value,String(value)]),day,setDay,type==='anual')),
   h('p',{className:'svp-rh-help'},type==='mensual'?'Descuentos de la fecha seleccionada. Se excluyen montos en cero, saldos iniciales y rendimientos.':'Proceso 1 y jubilados: último monto positivo del año. Proceso 3: una fila por quincena. Se excluyen saldos iniciales y rendimientos.'),
   error&&h('p',{role:'alert',className:'svp-error'},error),success&&h('p',{role:'status',className:'svp-success'},'Archivo Excel generado. Revisa la carpeta de descargas.'),
   h('button',{type:'submit',className:'svp-btn svp-rh-submit',disabled:busy},busy?'Generando reporte…':'Generar reporte'));
 }
 window.SavingsRhReport=SavingsRhReport;
})();
