/* Private imported withdrawal records; no financial posting or alternate data source. */
(function(){
 'use strict';const h=React.createElement;
 function dateKey(value){const text=String(value||'').trim();let parts=text.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!parts){const local=text.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(local)parts=[text,local[3],local[2].padStart(2,'0'),local[1].padStart(2,'0')];}if(!parts)return '';const iso=parts.slice(1).join('-'),d=new Date(iso+'T12:00:00Z');return !Number.isNaN(+d)&&d.toISOString().slice(0,10)===iso?iso:'';}
 const date=value=>{const iso=dateKey(value);return iso?new Date(iso+'T12:00:00Z').toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}):value?String(value)+' · Fecha por revisar':'Sin fecha registrada';};
 const money=value=>value==null||value===''?'Sin importe registrado':typeof value==='number'?new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(value):String(value)+' · Importe por revisar';
 const show=value=>value==null||value===''?'Sin dato':String(value);
 const css='.svw{font:13px var(--font,Arial);line-height:1.5}.svw-heading{display:flex;gap:12px;justify-content:space-between;align-items:center}.svw h2{margin:0}.svw p{color:#626b7b}.svw-table{background:white;border:1px solid #dde0e7;border-radius:12px;overflow:auto}.svw table{width:100%;border-collapse:collapse;font-size:12px}.svw td,.svw th{padding:12px 9px;text-align:left;vertical-align:top;border-bottom:1px solid #e5e7ed}.svw th{background:#f1f3f7}.svw small{display:block;color:#626b7b;margin-top:4px}.svw-money{font-weight:bold;white-space:nowrap}.svw-warning{background:#fff2d4;padding:12px;border-radius:10px}.svw-pager{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:12px 0}@media(max-width:650px){.svw thead{display:none}.svw tr{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid #dde0e7;padding:8px}.svw td{border:0;padding:7px;min-width:0;overflow-wrap:anywhere}.svw td::before{content:attr(data-label);display:block;font-size:10px;color:#626b7b;margin-bottom:4px}.svw td:last-child{grid-column:1/-1}.svw td:last-child button{width:100%}.svw-heading{align-items:flex-start}.svw-pager{font-size:11px}}';
 function SavingsWithdrawalList({recordId,onOpen,disabled=false,data:providedData,onRefresh}){
  const [state,setState]=React.useState({}),[retry,setRetry]=React.useState(0),[page,setPage]=React.useState(0);
  const provided=providedData!==undefined;
  React.useEffect(()=>{let active=true;setState({});setPage(0);if(!provided)window.SavingsReviewRepository.withdrawals(recordId).then(data=>{if(active)setState({id:recordId,data});}).catch(()=>{if(active)setState({id:recordId,error:true});});return()=>{active=false;};},[recordId,retry,provided]);
  const refresh=provided?onRefresh:()=>setRetry(retry+1);
  if(!provided&&state.id!==recordId)return h('p',{role:'status'},'Cargando retiros de esta persona…');
  if(provided?(!providedData||providedData.parent_id!==recordId||!Array.isArray(providedData.records)):state.error)return h('div',{role:'alert'},'No fue posible cargar los retiros. ',h('button',{onClick:refresh,disabled:!refresh},'Reintentar retiros'));
  const data=provided?providedData:state.data,rows=(data.records||[]).slice().sort((a,b)=>dateKey(b.source_data.D).localeCompare(dateKey(a.source_data.D))||a.source_row-b.source_row||a.id.localeCompare(b.id)),pages=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pages-1);
  function cell(r,key,label,format=show){const original=r.source_data[key],proposal=r.proposed_data||{},changed=!r.identity_change_pending&&Object.prototype.hasOwnProperty.call(proposal,key)&&JSON.stringify(original)!==JSON.stringify(proposal[key]);return h('td',{'data-label':label},h('span',{className:key==='G'?'svw-money':undefined},format(original)),changed&&h('small',null,'En revisión: '+format(proposal[key])));}
  return h('section',{className:'svw','aria-label':'Retiros de esta persona'},h('style',null,css),h('div',{className:'svw-heading'},h('div',null,h('h2',null,'Historial de retiros'),h('p',null,rows.length+' registro(s) · Folio '+(data.source_folio||'sin registro'))),h('button',{onClick:refresh,disabled:disabled||!refresh},'Actualizar retiros')),
   h('p',null,'Cada fila corresponde a un registro de «Solicitud de retiro». La fecha corresponde a esa solicitud y el estado indica cómo quedó registrado.'),
   data.identity_change_pending&&h('p',{className:'svw-warning'},'Hay un cambio de Folio pendiente. Esta lista conserva los retiros del Folio original.'),
   !rows.length?h('p',null,'No hay solicitudes de retiro cargadas con el Folio exacto de esta persona.'):h('div',{className:'svw-table'},h('table',{'aria-label':'Lista de retiros'},h('thead',null,h('tr',null,['Fecha de retiro','Importe','Tipo de retiro','Continúa ahorrando','Estado','Detalle'].map(label=>h('th',{key:label},label)))),h('tbody',null,rows.slice(current*8,current*8+8).map(r=>h('tr',{key:r.id},cell(r,'D','Fecha de retiro',date),cell(r,'G','Importe',money),cell(r,'E','Tipo de retiro'),cell(r,'F','Continúa ahorrando'),cell(r,'H','Estado'),h('td',{'data-label':'Detalle'},h('button',{disabled,onClick:()=>onOpen(r.id),'aria-label':'Ver retiro de '+date(r.source_data.D)+' por '+money(r.source_data.G)+' fila '+r.source_row},'Ver y revisar'),r.identity_change_pending&&h('small',null,'Folio en revisión; se muestran importes originales.'),h('small',null,'Fila '+r.source_row+' · Copia '+date(String(r.batch.observed_at).slice(0,10))))))))),
   rows.length>0&&h('div',{className:'svw-pager'},h('button',{disabled:current===0,onClick:()=>setPage(current-1)},'Retiros anteriores'),h('span',null,'Página '+(current+1)+' de '+pages),h('button',{disabled:current+1>=pages,onClick:()=>setPage(current+1)},'Más retiros')));
 }
 window.SavingsWithdrawalList=SavingsWithdrawalList;
})();
