/* High-fidelity membership application; Supabase documents + request snapshot. */
(function(){
  const{useEffect,useMemo,useState}=React,I=window.Icon;
  const money=(n)=>window.money?window.money(Number(n)||0):'$'+Number(n||0).toLocaleString('es-MX');
  function MembershipApplicationScreen({app,params}){
    const offering=window.membershipStore.get(params&&params.id),[phase,setPhase]=useState('loading'),[requirements,setRequirements]=useState([]),[documents,setDocuments]=useState([]),[terms,setTerms]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(null);
    const[data,setData]=useState({phone:String(app.user.phone||'').replace(/\D/g,''),rfc:String(app.user.rfc||'').toUpperCase(),curp:String(app.user.curp||'').toUpperCase()});
    const idem=React.useRef(window.ProgramRequestRepository.newIdempotencyKey());
    const load=React.useCallback(async()=>{if(!offering){setPhase('error');setError('La membresía ya no está disponible.');return;}setPhase('loading');try{const r=await window.DocumentWorkflowRepository.requirements('membership',offering.id);const[dResult,tResult]=await Promise.allSettled([window.DocumentWorkflowRepository.list(),window.ProgramTermsRepository.current('membership',offering.id)]);setRequirements(r.slice());setDocuments(dResult.status==='fulfilled'?dResult.value.slice():[]);setTerms(tResult.status==='fulfilled'?tResult.value:null);setError(dResult.status==='rejected'?'Los requisitos están disponibles; vuelve a intentar si tus documentos existentes no aparecen.':'');setPhase('ready');}catch(_){setRequirements([]);setDocuments([]);setTerms(null);setPhase('error');setError('No fue posible consultar los requisitos autorizados.');}},[offering&&offering.id]);useEffect(()=>{load();},[load]);
    const selected=useMemo(()=>requirements.map((r)=>documents.find((d)=>d.document_type_id===r.document_type_id&&['PENDING_REVIEW','UNDER_REVIEW','VERIFIED'].includes(d.status))).filter(Boolean),[requirements,documents]);
    const validData=/^[0-9]{10}$/.test(data.phone)&&/^[A-ZÑ&]{3,4}[0-9]{6}[A-Z0-9]{3}$/.test(data.rfc)&&/^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[A-Z0-9][0-9]$/.test(data.curp),ready=phase==='ready'&&selected.length===requirements.filter((r)=>r.required).length&&validData&&!!terms;
    const submit=async()=>{if(!ready||busy)return;setBusy(true);setError('');try{const request=await window.ProgramRequestRepository.createMembership({membershipOfferingId:offering.id,documentIds:selected.map((d)=>d.id),phone:data.phone,rfc:data.rfc,curp:data.curp,termsVersionId:terms.id,idempotencyKey:idem.current});setSent(request);}catch(_){setError('No pudimos registrar la solicitud. Revisa los requisitos e inténtalo de nuevo.');}finally{setBusy(false);}};
    if(sent)return React.createElement('div',{style:{position:'absolute',inset:0,background:'var(--bg)',display:'flex',flexDirection:'column'}},React.createElement('div',{style:{padding:16,background:'#fff',fontWeight:800}},React.createElement('button',{onClick:app.back,style:{border:'none',background:'none'}},React.createElement(I,{name:'arrowL',size:22})),'  Listo'),React.createElement('div',{style:{flex:1,display:'grid',placeItems:'center',padding:32,textAlign:'center'}},React.createElement('div',null,React.createElement('div',{style:{width:86,height:86,borderRadius:'50%',background:'#E5F7EF',color:'#087A50',display:'grid',placeItems:'center',margin:'0 auto'}},React.createElement(I,{name:'checkCircle',size:48,stroke:2})),React.createElement('h2',null,'¡Solicitud enviada!'),React.createElement('p',{style:{color:'var(--ink-2)',lineHeight:1.5}},'Tu solicitud quedó registrada y pasará al proceso de revisión correspondiente.'),React.createElement('div',{style:{display:'inline-block',padding:'9px 14px',background:'var(--guinda-50)',color:'var(--guinda)',borderRadius:12,font:'800 13px var(--mono)'}},'Folio '+sent.folio),React.createElement(window.Btn,{full:true,onClick:()=>{app.back();app.setTab('historial');},style:{marginTop:28}},'Seguir mi solicitud'))));
    const completed=selected.length+(validData?3:[data.phone,data.rfc,data.curp].filter(Boolean).length),total=requirements.length+3,missing=Math.max(0,total-completed),pay=offering?Number(offering.monto)/Math.max(1,Number(offering.pagos)):0;
    return React.createElement('div',{'data-membership-application':offering&&offering.id,style:{position:'absolute',inset:0,background:'var(--bg)',display:'flex',flexDirection:'column'}},
      React.createElement('div',{className:'su-app-scroll',style:{flex:1,overflowY:'auto'}},
        React.createElement('header',{style:{position:'relative',overflow:'hidden',color:'#fff',padding:'10px 20px 34px',background:'linear-gradient(158deg,var(--guinda),#6a001b 62%,#45000f)'}},React.createElement('div',{style:{display:'flex',alignItems:'center',gap:4}},React.createElement('button',{onClick:app.back,'aria-label':'Atrás',style:{width:44,height:44,border:'none',background:'transparent',color:'#fff'}},React.createElement(I,{name:'arrowL',size:22,stroke:2.2})),React.createElement('span',{style:{fontSize:11.5,fontWeight:900,letterSpacing:'.11em'}},'SOLICITUD DE MEMBRESÍA')),offering&&React.createElement(React.Fragment,null,React.createElement('div',{style:{display:'flex',alignItems:'center',gap:15,marginTop:16}},React.createElement('div',{style:{width:76,height:76,borderRadius:22,background:'#fff',display:'grid',placeItems:'center',overflow:'hidden'}},offering.logo?React.createElement('img',{src:offering.logo,alt:'',style:{width:'82%',height:'82%',objectFit:'contain'}}):React.createElement(I,{name:'card',size:30,style:{color:'var(--guinda)'}})),React.createElement('div',null,React.createElement('h1',{style:{margin:0,fontSize:24,fontWeight:900}},offering.empresa),React.createElement('div',{style:{fontSize:13.5,fontWeight:600,opacity:.88,marginTop:3}},offering.concepto))),React.createElement('div',{style:{display:'flex',gap:14,marginTop:20,padding:'13px 16px',borderRadius:16,background:'rgba(255,255,255,.13)'}},[['Costo total',money(offering.monto)],['Parcialidades',offering.pagos+' pagos'],['Cada quincena',money(pay)]].map((x,i)=>React.createElement('div',{key:x[0],style:{flex:1,minWidth:0,paddingLeft:i?14:0,borderLeft:i?'1px solid rgba(255,255,255,.24)':'none'}},React.createElement('div',{style:{fontSize:10,fontWeight:900,textTransform:'uppercase',opacity:.82}},x[0]),React.createElement('div',{style:{fontSize:16,fontWeight:900,marginTop:3}},x[1])))),React.createElement('p',{style:{fontSize:11.5,fontWeight:600,opacity:.82,lineHeight:1.5}},'Se descuenta vía nómina a partir del mes siguiente a la aprobación.'))),
        React.createElement('main',{style:{padding:'0 20px 24px',marginTop:-20}},React.createElement('section',{style:{background:'#fff',borderRadius:20,padding:16,boxShadow:'var(--shadow-lg)'}},React.createElement('div',{style:{display:'flex',justifyContent:'space-between',fontWeight:900}},React.createElement('span',null,missing?'Requisitos obligatorios':'Expediente completo'),React.createElement('span',{style:{color:missing?'var(--guinda)':'#087A50'}},completed+' de '+total)),React.createElement('div',{style:{display:'flex',gap:4,marginTop:11}},Array.from({length:total},(_,i)=>React.createElement('span',{key:i,style:{flex:1,height:7,borderRadius:999,background:i<completed?'var(--guinda)':'var(--surface-2)'}})))),
          React.createElement('section',{style:{marginTop:24}},React.createElement(window.SectionHead,{title:'Documentos',icon:'folder'}),phase==='ready'&&React.createElement(window.DocumentRequirementList,{requirements,documents,onChanged:load,compact:true})),
          React.createElement('section',{style:{marginTop:24}},React.createElement(window.SectionHead,{title:'Tus datos',icon:'idcard'}),React.createElement('div',{style:{background:'#fff',borderRadius:18,boxShadow:'var(--neo-sm)',overflow:'hidden'}},[['phone','Teléfono','10 dígitos'],['rfc','RFC','AAAA000000AAA'],['curp','CURP','18 caracteres']].map((x,i)=>React.createElement('label',{key:x[0],style:{display:'block',padding:'13px 15px',borderTop:i?'1px solid var(--hairline)':'none',fontSize:11.5,fontWeight:900,color:'var(--ink-2)'}},x[1],React.createElement('input',{value:data[x[0]],placeholder:x[2],maxLength:x[0]==='phone'?10:x[0]==='rfc'?13:18,onChange:(e)=>setData((d)=>Object.assign({},d,{[x[0]]:(x[0]==='phone'?e.target.value.replace(/\D/g,''):e.target.value.toUpperCase())})),style:{display:'block',width:'100%',border:'none',outline:'none',background:'transparent',padding:'5px 0 1px',font:'700 16px var(--mono)',color:'var(--ink)'}}))))),
          !terms&&phase==='ready'&&React.createElement('div',{role:'alert',style:{marginTop:18,padding:13,borderRadius:13,background:'#FFF4D9',color:'#805100',fontSize:12,fontWeight:700}},'Esta membresía aún no tiene términos publicados. Admin debe publicar una versión antes de recibir solicitudes.'),error&&React.createElement('div',{role:'alert',style:{marginTop:14,color:'#A32921',fontSize:12,fontWeight:700}},error))),
      React.createElement('footer',{style:{padding:'12px 20px calc(12px + env(safe-area-inset-bottom))',background:'#fff',borderTop:'1px solid var(--hairline)'}},React.createElement(window.Btn,{full:true,size:'lg',disabled:!ready||busy,onClick:submit},busy?'Enviando…':missing?'Solicitar · faltan '+missing:'Solicitar'),missing>0&&React.createElement('div',{style:{fontSize:12,fontWeight:700,color:'var(--ink-2)',textAlign:'center',marginTop:8}},'Completa los pendientes para continuar')));
  }
  window.MembershipApplicationScreen=MembershipApplicationScreen;
})();
