/* Universal program-product payment flow. Product, price, Caja Chica and math stay server-authoritative. */
(function(){
  'use strict';
  const h=React.createElement,{useState,useEffect,useRef}=React,I=window.Icon;
  const money2=(value)=>'$'+Number(value||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2});
  const money0=(value)=>window.money?window.money(Number(value||0)):money2(value);
  const dateLabel=(value)=>{try{return new Date(String(value)+'T12:00:00').toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'});}catch(_){return String(value||'—');}};
  function Field({label,value,accent}){return h('div',{style:{minWidth:0}},h('div',{style:{fontSize:11.5,fontWeight:700,color:'var(--ink-3)'}},label),h('div',{style:{fontSize:15.5,fontWeight:900,letterSpacing:'-.02em',marginTop:3,color:accent?'var(--guinda)':'var(--ink)',fontVariantNumeric:'tabular-nums'}},value));}
  function documentSelection(requirements,documents){
    const latest=new Map();(documents||[]).forEach((doc)=>{const current=latest.get(doc.document_type_id);if(!current||new Date(doc.created_at)>new Date(current.created_at))latest.set(doc.document_type_id,doc);});
    const required=(requirements||[]).filter((r)=>r.required!==false),selected=[],missing=[];
    required.forEach((requirement)=>{const doc=latest.get(requirement.document_type_id);if(doc&&doc.available===true&&doc.availability==='AVAILABLE'&&['PENDING_REVIEW','UNDER_REVIEW','VERIFIED'].includes(doc.status))selected.push(doc.id);else missing.push(requirement);});
    return{selected,missing};
  }
  function PaymentSchedule({schedule}){
    const [open,setOpen]=useState(false),rows=schedule&&Array.isArray(schedule.rows)?schedule.rows:[];
    if(!rows.length)return null;
    return h('div',{style:{marginTop:14,borderTop:'1px solid var(--hairline)',paddingTop:12}},
      h('button',{type:'button',onClick:()=>setOpen(!open),style:{width:'100%',border:'none',background:'transparent',padding:0,display:'flex',alignItems:'center',justifyContent:'space-between',fontFamily:'inherit',cursor:'pointer',color:'var(--ink)'}},
        h('span',{style:{fontSize:12.5,fontWeight:900}},'Calendario de descuentos'),
        h('span',{style:{fontSize:11.5,fontWeight:800,color:'var(--guinda)'}},open?'Ocultar':'Ver '+rows.length+' pagos')),
      open&&h('div',{'data-program-payment-schedule':'true',style:{marginTop:10,maxHeight:300,overflowY:'auto',border:'1px solid var(--hairline)',borderRadius:13}},
        h('div',{style:{display:'grid',gridTemplateColumns:'38px 1fr 1fr',gap:8,padding:'8px 10px',background:'var(--surface-2)',fontSize:10.5,fontWeight:800,color:'var(--ink-3)',position:'sticky',top:0}},h('span',null,'#'),h('span',null,'Fecha'),h('span',{style:{textAlign:'right'}},'Descuento')),
        rows.map((row)=>h('div',{key:row.number,style:{display:'grid',gridTemplateColumns:'38px 1fr 1fr',gap:8,padding:'9px 10px',borderTop:'1px solid var(--hairline)',fontSize:11.5,fontWeight:700}},h('span',{style:{fontFamily:'var(--mono)',color:'var(--ink-3)'}},String(row.number).padStart(2,'0')),h('span',null,dateLabel(row.date)),h('span',{style:{textAlign:'right',fontVariantNumeric:'tabular-nums'}},money2(row.payment))))));
  }
  function Application({item,session,quote,onClose,app}){
    const [step,setStep]=useState('documents'),[docState,setDocState]=useState({phase:'loading',requirements:[],documents:[],terms:null}),[signature,setSignature]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(null),idem=useRef(window.ProgramRequestRepository.newIdempotencyKey());
    const load=React.useCallback(async()=>{setDocState((s)=>Object.assign({},s,{phase:'loading'}));try{const[requirements,documents,terms]=await Promise.all([window.DocumentWorkflowRepository.requirements('prestamo'),window.DocumentWorkflowRepository.listSelfDocuments('SELF_SERVICE_LOAN'),window.ProgramTermsRepository.current('prestamo')]);setDocState({phase:'ready',requirements:requirements.slice(),documents:documents.slice(),terms});}catch(_){setDocState({phase:'error',requirements:[],documents:[],terms:null});}},[]);
    useEffect(()=>{load();},[load]);
    const gate=documentSelection(docState.requirements,docState.documents),canSummary=docState.phase==='ready'&&gate.missing.length===0&&docState.terms;
    const send=async()=>{if(busy||!canSummary||!signature||!accepted)return;setBusy(true);setError('');try{const result=await window.FinancialLegacyRepository.confirmProgramPayment({snapshotId:session.loanSession.id,programItemId:item.id,downPayment:quote.downPayment,term:quote.financialResult.paymentCount,notes:'Solicitud de producto con descuento vía nómina',signature,terms:true,termsVersionId:docState.terms.id,documentIds:gate.selected,idempotencyKey:idem.current});setSent(result);if(window.operationsStore)window.operationsStore.invalidate();}catch(e){const code=e.code||e.message;setError(code==='CONDITIONS_CHANGED'?'Las condiciones cambiaron. Cierra y vuelve a simular antes de enviar.':code==='REQUIRED_DOCUMENTS_MISSING'?'Falta validar uno o más documentos requeridos.':'No se pudo registrar la solicitud. Inténtalo nuevamente sin cambiar los datos.');}finally{setBusy(false);}};
    if(sent)return h(window.RequestSubmissionSuccess,{app,folio:sent.folio,kind:'benefit',subject:item.nombre,workflowState:sent.workflow_state,onBack:onClose,fullScreen:true,destination:'Tu solicitud de producto con descuento vía nómina fue enviada al Área de Finanzas para revisión.'});
    return h('div',{'data-program-payment-application':'true','data-program-payment-step':step,style:{position:'absolute',inset:0,zIndex:88,isolation:'isolate',overflow:'hidden',background:'var(--bg)',display:'flex',flexDirection:'column'}},
      h('div',{style:{display:'flex',alignItems:'center',gap:11,padding:'calc(10px + env(safe-area-inset-top)) 15px 11px',background:'var(--surface)',borderBottom:'1px solid var(--hairline)'}},
        h('button',{onClick:step==='summary'?()=>setStep('documents'):onClose,'aria-label':'Atrás',style:{width:40,height:40,border:'none',borderRadius:12,background:'var(--surface-2)',display:'grid',placeItems:'center',color:'var(--ink)'}},h(I,{name:'arrowL',size:20,stroke:2.2})),
        h('div',{style:{flex:1}},h('div',{style:{fontSize:15,fontWeight:900}},step==='documents'?'Documentos':'Revisa y firma'),h('div',{style:{fontSize:11.5,fontWeight:700,color:'var(--ink-3)'}},step==='documents'?'Paso 1 de 2 · Expediente vigente':'Paso 2 de 2 · Solicitud de producto'))),
      h('div',{'data-program-payment-scroll':'true',className:'su-app-scroll',style:{position:'relative',zIndex:0,flex:1,overflowY:'auto',overscrollBehavior:'contain',padding:'16px 17px calc(144px + env(safe-area-inset-bottom))'}},
        step==='documents'?h(React.Fragment,null,
          h('div',{style:{fontSize:13,color:'var(--ink-2)',fontWeight:600,lineHeight:1.5,marginBottom:13}},'Usamos los mismos requisitos documentales vigentes de Suti Préstamo. Puedes reutilizar documentos válidos o reemplazarlos aquí.'),
          h(window.UnifiedDocumentPhase,{requirements:docState.requirements,documents:docState.documents,onChanged:load,phase:docState.phase,error:'No fue posible consultar los requisitos autorizados.',onRetry:load,accessPurpose:'SELF_SERVICE_LOAN',title:'Verifica tus documentos'})):
        h(React.Fragment,null,
          h('div',{style:{background:'var(--surface)',borderRadius:18,padding:15,boxShadow:'var(--neo-sm)'}},
            h('div',{style:{fontSize:11.5,fontWeight:800,color:'var(--ink-3)'}},item.scopeId||item.program_key||'Programa'),h('div',{style:{fontSize:17,fontWeight:900,marginTop:3}},item.nombre),
            h('div',{style:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:13,marginTop:15}},h(Field,{label:'Precio autorizado',value:money2(quote.authorizedPrice)}),h(Field,{label:'Enganche',value:money2(quote.downPayment)}),h(Field,{label:'Monto financiado',value:money2(quote.financedAmount)}),h(Field,{label:'Fondo',value:quote.financialResult.fund}),h(Field,{label:'Pagos',value:quote.financialResult.paymentCount+' '+(quote.financialResult.paymentPeriod==='mensual'?'mensuales':'quincenales')}),h(Field,{label:'Descuento por pago',value:money2(quote.financialResult.paymentPerPeriod),accent:true}),h(Field,{label:'Intereses',value:money2(quote.financialResult.interest)}),h(Field,{label:'Gastos administrativos',value:money2(quote.financialResult.administrativeFeeTotal)}),h(Field,{label:'Total a pagar',value:money2(quote.financialResult.total),accent:true})),
            h(PaymentSchedule,{schedule:quote.paymentSchedule})),
          h(window.SignBlock,{programa:'financiamiento',subtitulo:'Producto con descuento vía nómina · '+item.nombre,firma:signature,setFirma:setSignature,accept:accepted,setAccept:setAccepted,termsVersion:docState.terms}),
          error&&h('div',{role:'alert',style:{marginTop:12,color:'#A32921',fontSize:12.5,fontWeight:800,lineHeight:1.45}},error))),
      h('div',{'data-program-payment-footer':'true',style:{position:'absolute',zIndex:10,left:0,right:0,bottom:0,padding:'24px 17px calc(14px + env(safe-area-inset-bottom))',background:'linear-gradient(transparent 0,var(--surface) 24px)'}},
        step==='documents'?h(window.Btn,{full:true,size:'lg',icon:'arrowR',disabled:!canSummary,onClick:()=>setStep('summary')},docState.phase==='loading'?'Consultando documentos…':docState.phase==='error'?'Reintenta la consulta':gate.missing.length?'Faltan '+gate.missing.length+' documentos':'Continuar al resumen'):
        h(window.Btn,{full:true,size:'lg',icon:'check',disabled:busy||!signature||!accepted,onClick:send},busy?'Enviando solicitud…':'Enviar solicitud')));
  }
  function ProgramProductPaymentFlow({item,app,onRequestQuote}){
    const acquisitionBlocked=item.sold===true||item.commercialMode==='DIRECT_CONTACT'||item.commercial_mode==='DIRECT_CONTACT';
    const [open,setOpen]=useState(false),[state,setState]=useState({phase:'loading',data:null,error:''}),[downTxt,setDownTxt]=useState('0'),[term,setTerm]=useState(1),[quoteState,setQuoteState]=useState({phase:'idle',data:null,error:''}),[application,setApplication]=useState(false),sequence=useRef(0);
    const load=React.useCallback(async()=>{if(acquisitionBlocked)return;setState({phase:'loading',data:null,error:''});try{const data=await window.FinancialLegacyRepository.openProgramPaymentSession(item.id);setState({phase:'ready',data,error:''});if(data.status==='READY'){const min=Math.ceil(Number(data.minimumDownPayment||0)*100)/100;setDownTxt(String(min));setTerm(Number(data.program.custom_term&&data.program.custom_term.min||1));}}catch(e){setState({phase:'error',data:null,error:e.code||e.message});}},[item.id,acquisitionBlocked]);
    useEffect(()=>{if(!acquisitionBlocked)load();},[load,acquisitionBlocked]);
    const session=state.data,price=Number(session&&session.authorizedPrice||0),down=Math.max(0,Number(downTxt)||0),maxTerm=Number(session&&session.program&&session.program.custom_term&&session.program.custom_term.max||1),minDown=Number(session&&session.minimumDownPayment||0);
    useEffect(()=>{if(acquisitionBlocked||!session||session.status!=='READY'||!session.loanSession)return;const current=++sequence.current;setQuoteState((s)=>({phase:'loading',data:s.data,error:''}));const timer=setTimeout(()=>window.FinancialLegacyRepository.quoteProgramPayment(session.loanSession.id,down,term).then((data)=>{if(current===sequence.current)setQuoteState({phase:'ready',data,error:''});},(e)=>{if(current===sequence.current)setQuoteState({phase:'error',data:null,error:e.code||e.message});}),260);return()=>clearTimeout(timer);},[acquisitionBlocked,session&&session.loanSession&&session.loanSession.id,down,term]);
    const quote=quoteState.data,period=quote&&quote.financialResult.paymentPeriod==='mensual'?'mensual':'quincenal';
    if(acquisitionBlocked)return null;
    if(state.phase==='loading')return h('div',{'data-program-payment-state':'loading',className:'su-skeleton',style:{height:72,borderRadius:18,marginTop:18}});
    if(state.phase==='error')return h('div',{'data-program-payment-state':'error',style:{marginTop:18,background:'var(--surface)',borderRadius:18,padding:14,boxShadow:'var(--neo-sm)'}},h('div',{style:{fontSize:12.5,fontWeight:800,color:'#A32921'}},'No fue posible consultar el plan de pago.'),h('button',{onClick:load,style:{border:'none',background:'none',color:'var(--guinda)',fontWeight:900,marginTop:8,padding:0}},'Reintentar'));
    if(session.status==='QUOTE_REQUIRED')return h('div',{'data-program-payment-state':'quote-required',style:{marginTop:18,background:'var(--surface)',borderRadius:18,padding:15,boxShadow:'var(--neo-sm)'}},h('div',{style:{display:'flex',gap:11,alignItems:'center'}},h('div',{style:{width:42,height:42,borderRadius:13,background:'var(--guinda-50)',color:'var(--guinda)',display:'grid',placeItems:'center'}},h(I,{name:'doc',size:20,stroke:2})),h('div',{style:{flex:1}},h('div',{style:{fontSize:14,fontWeight:900}},'Primero necesitas una cotización'),h('div',{style:{fontSize:11.5,fontWeight:700,color:'var(--ink-3)',marginTop:2}},'Cuando el precio autorizado esté vigente, aquí aparecerá el mismo simulador.'))),h(window.Btn,{full:true,variant:'outline',icon:'doc',style:{marginTop:12},onClick:onRequestQuote},'Solicitar cotización'));
    if(session.status==='NOT_ELIGIBLE')return h('div',{'data-program-payment-state':'not-eligible',style:{marginTop:18,background:'var(--surface)',borderRadius:18,padding:15,boxShadow:'var(--neo-sm)',fontSize:12.5,fontWeight:700,color:'var(--ink-2)'}},'Caja Chica no tiene una regla vigente para tu perfil. El producto sigue visible, pero no puede simularse por nómina.');
    return h(React.Fragment,null,
      h('div',{'data-program-payment-state':'ready',style:{marginTop:18,background:'var(--surface)',borderRadius:20,boxShadow:'var(--neo-sm)',padding:open?'16px 16px 18px':14}},
        !open?h('button',{'data-program-payment-open':'true','aria-label':'Abrir simulador de plan de pago',onClick:()=>setOpen(true),className:'su-press',style:{display:'flex',alignItems:'center',gap:12,width:'100%',textAlign:'left',border:'none',background:'transparent',padding:0,fontFamily:'inherit',cursor:'pointer'}},h('div',{style:{width:44,height:44,borderRadius:13,background:'var(--guinda-50)',color:'var(--guinda)',display:'grid',placeItems:'center'}},h(I,{name:'cash',size:22,stroke:2})),h('div',{style:{flex:1}},h('div',{style:{fontSize:14.5,fontWeight:900}},'Simula tu plan de pago'),h('div',{style:{fontSize:12.5,fontWeight:700,color:'var(--ink-3)',marginTop:2}},quote?'Desde '+money2(quote.financialResult.paymentPerPeriod)+' '+period:'Consulta tu descuento autorizado')),h(I,{name:'chevR',size:20,stroke:2.2,style:{color:'var(--ink-3)'}})):
        h('div',{style:{animation:'su-fadein .22s ease'}},
          h('div',{style:{display:'flex',alignItems:'center',gap:10,marginBottom:14}},h('div',{style:{width:38,height:38,borderRadius:12,background:'var(--guinda-50)',color:'var(--guinda)',display:'grid',placeItems:'center'}},h(I,{name:'cash',size:20,stroke:2})),h('div',{style:{flex:1}},h('div',{style:{fontSize:14.5,fontWeight:900}},'Simula tu plan de pago'),h('div',{style:{fontSize:11.5,fontWeight:700,color:'var(--ink-3)'}},'Elige tu enganche y número de descuentos')),h('button',{onClick:()=>setOpen(false),'aria-label':'Cerrar simulador',style:{width:32,height:32,border:'none',background:'transparent',color:'var(--ink-3)'}},h(I,{name:'close',size:17,stroke:2.3}))),
          h('div',{style:{background:'linear-gradient(135deg,var(--guinda),var(--guinda-700))',color:'#fff',borderRadius:18,padding:'15px 16px',textAlign:'center'}},h('div',{style:{fontSize:11.5,opacity:.82,fontWeight:700,textTransform:'uppercase'}},'Descuento '+period),h('div',{style:{fontSize:34,fontWeight:800,letterSpacing:'-.03em',lineHeight:1.14,marginTop:2}},quote?money2(quote.financialResult.paymentPerPeriod):'—'),h('div',{style:{display:'flex',justifyContent:'center',gap:14,marginTop:11,fontSize:11.5}},h('span',null,term+' pagos'),h('span',null,'·'),h('span',null,quote?dateLabel(quote.paymentSchedule.first_payment_date):'Calculando…'),h('span',null,'·'),h('span',null,quote?money0(quote.financialResult.total):'—'))),
          h('div',{style:{marginTop:16}},h('div',{style:{display:'flex',justifyContent:'space-between',fontSize:13,fontWeight:800,color:'var(--ink-2)'}},h('span',null,'Tu enganche'),h('span',{style:{fontSize:11,color:'var(--ink-3)'}},minDown>0?'Mínimo '+money0(minDown):'Desde $0')),h('div',{style:{display:'flex',alignItems:'center',gap:8,background:'var(--surface-2)',boxShadow:'var(--neo-inset)',borderRadius:14,padding:'2px 13px',marginTop:7}},h('span',{style:{fontSize:18,fontWeight:800,color:'var(--guinda)'}},'$'),h('input',{type:'number',inputMode:'decimal',min:minDown,max:Math.max(minDown,price-.01),step:'0.01',value:downTxt,onChange:(e)=>setDownTxt(e.target.value),style:{flex:1,border:'none',background:'transparent',padding:'11px 0',fontSize:18,fontWeight:800,color:'var(--guinda)',minWidth:0}})),down<minDown&&h('div',{style:{fontSize:11.5,fontWeight:700,color:'#B3261E',marginTop:7}},'El enganche mínimo para Caja Chica es '+money0(minDown)+'.')),
          h('div',{style:{marginTop:16}},h('div',{style:{display:'flex',justifyContent:'space-between',fontSize:13,fontWeight:800,color:'var(--ink-2)'}},h('span',null,'Número de descuentos '+(session.program.payment_period==='mensual'?'mensuales':'permitidos')),h('span',{style:{fontSize:11,color:'var(--ink-3)'}},'Máximo '+maxTerm)),h('input',{type:'range',min:1,max:maxTerm,step:1,value:term,onChange:(e)=>setTerm(Number(e.target.value)),className:'su-range',style:{width:'100%',marginTop:8,accentColor:'var(--guinda)'}}),h('div',{style:{textAlign:'center',fontSize:16,fontWeight:900,color:'var(--guinda)'}},term+' '+(session.program.payment_period==='mensual'?'meses':'pagos'))),
          quote&&h(React.Fragment,null,h('div',{style:{marginTop:16,paddingTop:15,borderTop:'1px solid var(--hairline)',display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}},h(Field,{label:'Precio autorizado',value:money2(quote.authorizedPrice)}),h(Field,{label:'Monto a financiar',value:money2(quote.financedAmount)}),h(Field,{label:'Tasa de interés',value:quote.financialResult.rate+'% '+period}),h(Field,{label:'Total de intereses',value:money2(quote.financialResult.interest)}),h(Field,{label:'Gasto por pago',value:money2(quote.financialResult.administrativeFeePerPayment)}),h(Field,{label:'Total gastos administrativos',value:money2(quote.financialResult.administrativeFeeTotal)}),h(Field,{label:'Total a pagar',value:money2(quote.financialResult.total),accent:true})),h(PaymentSchedule,{schedule:quote.paymentSchedule}),h(window.Btn,{full:true,icon:'arrowR',disabled:quoteState.phase!=='ready'||down<minDown,style:{marginTop:14},onClick:()=>setApplication(true)},'Continuar con esta simulación')),
          quoteState.phase==='error'&&h('div',{role:'alert',style:{fontSize:11.5,fontWeight:800,color:'#A32921',marginTop:10}},quoteState.error==='DOWN_PAYMENT_OUT_OF_RANGE'?'Ajusta el enganche al monto permitido por Caja Chica.':'No fue posible actualizar la simulación.'),
          h('div',{style:{display:'flex',gap:8,marginTop:12,fontSize:11,fontWeight:600,lineHeight:1.45,color:'var(--ink-3)'}},h(I,{name:'info',size:14,stroke:2,style:{flexShrink:0,marginTop:1}}),h('span',null,'Precio y reglas validados en Supabase. El primer descuento será al menos 30 días después de formalizar la solicitud.')))),
      application&&quote&&h(Application,{item,session,quote,onClose:()=>setApplication(false),app}));
  }
  window.ProgramProductPaymentFlow=ProgramProductPaymentFlow;
})();
