/* Convenios Claude Design contract + Supabase authority (H-007.3/H-009). */
(function () {
  'use strict';
  const { useEffect, useRef, useState } = React;
  const I = window.Icon;

  function AdSlide({ ad, active, empty, onClick, onZoom }) {
    const image = ad && ad.image_url;
    return React.createElement('div', {
      onClick, className: 'su-press', 'data-convenios-ad': empty ? 'empty' : ad.id,
      style: { flex:'0 0 100%', height:196, borderRadius:24, overflow:'hidden', position:'relative', cursor:empty?'default':'pointer', background:'linear-gradient(140deg,var(--guinda),#4c1025)', boxShadow:active?'0 18px 40px -16px rgba(20,33,61,.4)':'var(--neo-sm)', transform:active?'scale(calc(1 * var(--press-s, 1)))':'scale(calc(.94 * var(--press-s, 1)))', opacity:active?1:.65, transition:'transform .55s cubic-bezier(.22,1,.36,1), opacity .55s, box-shadow .55s' } },
      image && React.createElement('img',{src:image,alt:ad.title||'',style:{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover'}}),
      React.createElement('div',{style:{position:'absolute',inset:0,background:'linear-gradient(180deg,rgba(0,0,0,.28) 0%,transparent 32%,transparent 48%,rgba(0,0,0,.72) 100%)',pointerEvents:'none'}}),
      React.createElement('div',{style:{position:'absolute',top:14,left:14,display:'inline-flex',alignItems:'center',gap:6,background:'rgba(255,255,255,.92)',color:'var(--ink)',fontSize:10,fontWeight:800,letterSpacing:'.08em',padding:'6px 11px',borderRadius:999,boxShadow:'0 4px 12px -4px rgba(0,0,0,.35)'}},React.createElement('span',{style:{width:6,height:6,borderRadius:'50%',background:'var(--gold-2)'}}),'PATROCINADO'),
      image&&React.createElement('button',{onClick:(event)=>{event.stopPropagation();onZoom();},'aria-label':'Ampliar anuncio',style:{position:'absolute',top:12,right:12,width:38,height:38,border:'none',borderRadius:12,background:'rgba(0,0,0,.42)',color:'#fff',display:'grid',placeItems:'center',cursor:'zoom-in'}},React.createElement(I,{name:'search',size:18,stroke:2.3})),
      React.createElement('div',{style:{position:'absolute',left:18,right:18,bottom:16,color:'#fff',display:'flex',alignItems:'flex-end',justifyContent:'space-between',gap:12}},
        React.createElement('div',{style:{minWidth:0}},React.createElement('div',{style:{fontSize:21,fontWeight:800,letterSpacing:'-.01em',textShadow:'0 2px 12px rgba(0,0,0,.4)'}},empty?'Sin campañas publicadas':ad.title),React.createElement('div',{style:{fontSize:13.5,fontWeight:600,opacity:.94,marginTop:2,textShadow:'0 1px 8px rgba(0,0,0,.4)'}},empty?'Espacio disponible':ad.description||'')),
        !empty&&React.createElement('div',{style:{flexShrink:0,width:42,height:42,borderRadius:14,background:'rgba(255,255,255,.95)',display:'grid',placeItems:'center',color:'var(--guinda)',boxShadow:'0 6px 16px -6px rgba(0,0,0,.5)'}},React.createElement(I,{name:'arrowR',size:21,stroke:2.4}))));
  }

  function AdCarousel({ ads }) {
    const items=ads||[];const n=items.length;const[idx,setIdx]=useState(0);const[paused,setPaused]=useState(false);const[offset,setOffset]=useState(0);const[viewer,setViewer]=useState(null);const drag=useRef(null);
    useEffect(()=>{if(idx>=n&&n)setIdx(0);},[n,idx]);
    useEffect(()=>{if(paused||n<2)return;const t=setTimeout(()=>setIdx((i)=>(i+1)%n),4600);return()=>clearTimeout(t);},[idx,paused,n]);
    const open=(ad)=>{if(!ad)return;if(ad.action_url)window.openSafeContentUrl(ad.action_url);else if(ad.image_url)setViewer(ad);};
    const down=(e)=>{if(n<2)return;drag.current={id:e.pointerId,x:e.clientX,t:Date.now(),dx:0};setPaused(true);try{e.currentTarget.setPointerCapture(e.pointerId);}catch(_){}};
    const move=(e)=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;d.dx=e.clientX-d.x;setOffset(d.dx);};
    const up=()=>{const d=drag.current;drag.current=null;if(d&&n>1){const width=Math.max(1,document.documentElement.clientWidth-32);const speed=Math.abs(d.dx)/Math.max(1,Date.now()-d.t);if(Math.abs(d.dx)>width*.22||speed>.5)setIdx((i)=>d.dx<0?Math.min(n-1,i+1):Math.max(0,i-1));}setOffset(0);setPaused(false);};
    const rendered=n?items:[null];const current=n?idx:0;
    return React.createElement('section',{'data-convenios-section':'ads',style:{paddingTop:6}},
      React.createElement('div',{style:{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 20px 10px'}},React.createElement('div',{style:{display:'flex',alignItems:'center',gap:7}},React.createElement('span',{style:{width:7,height:7,borderRadius:'50%',background:'var(--gold-2)',boxShadow:'0 0 0 3px rgba(200,146,47,.2)'}}),React.createElement('span',{style:{fontSize:11,fontWeight:800,letterSpacing:'.1em',color:'var(--ink-3)'}},'ESPACIO PUBLICITARIO')),React.createElement('span',{'data-convenios-ad-position':'',style:{fontSize:11.5,fontWeight:700,color:'var(--ink-3)'}},n?(current+1)+' / '+n:'0 / 0')),
      React.createElement('div',{onMouseEnter:()=>setPaused(true),onMouseLeave:()=>setPaused(false),onPointerDown:down,onPointerMove:move,onPointerUp:up,onPointerCancel:up,style:{overflow:'hidden',padding:'0 16px',touchAction:'pan-y'}},React.createElement('div',{style:{display:'flex',gap:14,transition:drag.current?'none':'transform .55s cubic-bezier(.22,1,.36,1)',transform:`translateX(calc(${-current} * (100% + 14px) + ${offset}px))`,willChange:'transform'}},rendered.map((ad,i)=>React.createElement(AdSlide,{key:ad?ad.id:'empty',ad,empty:!ad,active:i===current,onClick:()=>open(ad),onZoom:()=>setViewer(ad)})))),
      n>1&&React.createElement('div',{'data-convenios-ad-dots':'',style:{display:'flex',gap:7,justifyContent:'center',marginTop:14}},items.map((_,i)=>React.createElement('button',{key:i,onClick:()=>setIdx(i),'aria-label':'Anuncio '+(i+1),style:{width:i===current?24:8,height:8,borderRadius:999,border:'none',cursor:'pointer',padding:0,background:i===current?'var(--grad-guinda-soft)':'var(--hairline-strong)',transition:'width .3s ease'}}))),
      viewer&&React.createElement(window.ImageViewer,{sources:[viewer.image_url],alt:viewer.title||'Anuncio',onClose:()=>setViewer(null)}));
  }

  function CompanyImage({ company, height=150 }) {
    return React.createElement('div',{style:{height,position:'relative',overflow:'hidden',background:'var(--surface-2)'}},company.cover_url?React.createElement('img',{src:company.cover_url,alt:company.display_name,loading:'lazy',style:{width:'100%',height:'100%',objectFit:'cover',display:'block'}}):React.createElement('div',{style:{width:'100%',height:'100%',display:'grid',placeItems:'center',color:'var(--ink-3)'}},React.createElement(I,{name:'tag',size:42,stroke:1.5})));
  }

  function PendingDiscount(){return React.createElement(window.Badge,{tone:'amber',solid:true},'DESCUENTO PENDIENTE');}

  function ConvenioCard({ company, fav, onFav, onClick }) {
    return React.createElement('article',{onClick,className:'su-press','data-company-id':company.id,style:{background:'var(--surface)',borderRadius:20,overflow:'hidden',boxShadow:'var(--neo-sm)',cursor:'pointer'}},
      React.createElement('div',{style:{position:'relative'}},React.createElement(CompanyImage,{company}),React.createElement('div',{style:{position:'absolute',top:12,left:12}},React.createElement(PendingDiscount)),React.createElement(window.FavHeart,{on:fav,onClick:(e)=>{e.stopPropagation();onFav();},style:{top:10,right:10}})),
      React.createElement('div',{style:{padding:'13px 15px 15px'}},React.createElement('div',{style:{fontSize:16.5,fontWeight:800,letterSpacing:'-.01em'}},company.display_name),React.createElement('div',{style:{display:'flex',alignItems:'center',gap:5,fontSize:12.5,color:'var(--ink-3)',fontWeight:600,marginTop:3}},React.createElement(window.Res,{resKey:'convenios.card.pin',size:13,stroke:2}),React.createElement('span',{style:{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}},company.address_raw||company.location_raw||'Ubicación pendiente')),company.category_raw&&React.createElement('div',{style:{display:'flex',gap:7,flexWrap:'wrap',marginTop:10}},React.createElement('span',{style:{fontSize:11.5,fontWeight:700,color:'var(--guinda)',background:'var(--guinda-50)',padding:'4px 10px',borderRadius:999}},company.category_raw))));
  }

  function LoadingLayout({ app }) {
    return React.createElement('div',{className:'su-route','data-convenios-state':'loading',style:{paddingBottom:18}},React.createElement(window.TopBar,{app,variant:'convenios'}),React.createElement('div',{style:{padding:'6px 16px 0'}},React.createElement(window.Skeleton,{h:196,r:24})),React.createElement('div',{style:{padding:'20px 16px 0'}},React.createElement(window.Skeleton,{h:52,r:16})),React.createElement('div',{style:{padding:'14px 16px 2px'}},React.createElement(window.Skeleton,{h:38,r:19})),React.createElement('div',{style:{padding:'20px 16px'}},React.createElement(window.Skeleton,{h:130,r:18,style:{marginBottom:20}}),React.createElement(window.Skeleton,{h:220,r:20})));
  }

  function ConveniosScreen({ app }) {
    const visual=app.visual;const catalog=window.useCatalogStore();const[cat,setCat]=useState('Todos');const[q,setQ]=useState('');const[filters,setFilters]=useState(false);
    if(visual.phase==='loading')return React.createElement(LoadingLayout,{app});
    if(visual.phase==='error')return React.createElement('div',{className:'su-route','data-convenios-state':'error','data-h0073-state':'error',style:{paddingBottom:18}},React.createElement(window.TopBar,{app,variant:'convenios'}),React.createElement(AdCarousel,{ads:[]}),React.createElement(window.EmptyState,{icon:'alert',title:'No pudimos cargar las empresas',sub:'Comprueba tu conexión e inténtalo de nuevo.',action:React.createElement(window.Btn,{onClick:visual.retry},'Reintentar')}));
    const base=visual.companies||[];const cats=['Todos',...Array.from(new Set(base.map((c)=>String(c.category_raw||'').trim()).filter(Boolean)))];const needle=q.trim().toLocaleLowerCase('es-MX');
    const list=base.filter((c)=>(cat==='Todos'||c.category_raw===cat)&&(!needle||[c.display_name,c.description,c.category_raw].concat(catalog.byCompany(c.id).map((p)=>p.nombre)).some((x)=>String(x||'').toLocaleLowerCase('es-MX').includes(needle))));
    const toggleFav=(id)=>catalog.toggleCompanyFavorite(id).catch(()=>app.toast&&app.toast('No se pudo actualizar el favorito'));const selectCat=(value)=>{setCat(value);setFilters(false);};
    return React.createElement('div',{className:'su-route','data-convenios-state':'loaded','data-h0073-state':'loaded',style:{paddingBottom:18}},
      React.createElement(window.TopBar,{app,variant:'convenios'}),React.createElement(AdCarousel,{ads:visual.marketplaceBanners||[]}),
      React.createElement('div',{style:{padding:'20px 16px 0'}},React.createElement(window.SearchBar,{placeholder:'Busca una empresa o beneficio…',value:q,onChange:setQ,onFilter:()=>setFilters(true)})),
      React.createElement(window.ChipBar,{items:cats,value:cat,onChange:setCat,style:{padding:'14px 16px 2px'}}),
      cat==='Todos'&&!q&&React.createElement('section',{'data-convenios-section':'featured',style:{marginTop:18}},React.createElement('div',{style:{padding:'0 20px'}},React.createElement(window.SectionHead,{title:'Destacados',icon:'star'})),React.createElement('div',{'data-convenios-featured-state':'pending',style:{margin:'0 16px',height:130,borderRadius:18,background:'var(--surface)',boxShadow:'var(--neo-sm)',display:'grid',placeItems:'center',padding:16,textAlign:'center',color:'var(--ink-3)',fontSize:12.5,fontWeight:700}},'Pendiente de clasificación destacada')),
      React.createElement('section',{'data-convenios-section':'all',style:{padding:'20px 16px 0'}},React.createElement(window.SectionHead,{title:cat==='Todos'?'Todos los convenios':cat,icon:'tag'}),React.createElement('div',{'data-h0073-company-count':list.length,style:{display:'flex',flexDirection:'column',gap:14}},list.map((company)=>React.createElement(ConvenioCard,{key:company.id,company,fav:catalog.isCompanyFavorite(company.id),onFav:()=>toggleFav(company.id),onClick:()=>app.push('convenio',{company})})),list.length===0&&React.createElement(window.EmptyState,{icon:'search',title:'Sin resultados',sub:'Prueba con otra búsqueda o categoría.'}))),
      React.createElement(window.Sheet,{open:filters,onClose:()=>setFilters(false),title:'Filtrar convenios'},React.createElement(window.ChipBar,{items:cats,value:cat,onChange:selectCat,style:{padding:'4px 0 10px'}})));
  }

  function ConvenioDetail({ app, params }) {
    const company=params.company;const catalog=window.useCatalogStore();const[viewer,setViewer]=useState(null);
    if(!company)return null;
    const fav=catalog.isCompanyFavorite(company.id);const products=catalog.byCompany(company.id).filter((p)=>p.activo!==false);const images=[company.cover_url].concat(company.gallery_urls||[]).filter(Boolean);const phone=String(company.phone_raw||'').trim();const wa=String(company.whatsapp_raw||'').replace(/\D/g,'');
    return React.createElement('div',{'data-convenio-detail':'',style:{position:'absolute',inset:0,background:'var(--bg)',display:'flex',flexDirection:'column'}},React.createElement('div',{className:'su-app-scroll su-route',style:{flex:1,overflowY:'auto',paddingBottom:110}},
      React.createElement('div',{'data-convenio-cover-zoom':company.cover_url?'enabled':'disabled',style:{position:'relative'},onClick:()=>company.cover_url&&setViewer(0)},React.createElement(CompanyImage,{company,height:240}),React.createElement('button',{onClick:(event)=>{event.stopPropagation();app.back();},'aria-label':'Volver',style:{position:'absolute',top:12,left:10,width:40,height:40,borderRadius:'50%',border:'none',background:'rgba(0,0,0,.35)',display:'grid',placeItems:'center',cursor:'pointer',color:'#fff'}},React.createElement(I,{name:'arrowL',size:22,stroke:2})),React.createElement(window.FavHeart,{on:fav,onClick:(event)=>{event&&event.stopPropagation&&event.stopPropagation();catalog.toggleCompanyFavorite(company.id).catch(()=>app.toast&&app.toast('No se pudo actualizar el favorito'));},size:40,iconSize:21,style:{top:12,right:10}}),React.createElement('div',{style:{position:'absolute',top:12,left:60}},React.createElement(PendingDiscount)),company.cover_url&&React.createElement('div',{style:{position:'absolute',right:13,bottom:13,padding:'6px 10px',borderRadius:999,background:'rgba(0,0,0,.42)',color:'#fff',fontSize:10.5,fontWeight:800,pointerEvents:'none'}},'AMPLIAR')),
      React.createElement('div',{style:{padding:20}},React.createElement('h1',{style:{fontSize:25,fontWeight:800,letterSpacing:'-.02em',margin:0}},company.display_name),React.createElement('div',{style:{display:'flex',alignItems:'center',gap:6,fontSize:13.5,color:'var(--ink-3)',fontWeight:600,marginTop:6}},React.createElement(window.Res,{resKey:'convenios.card.pin',size:15,stroke:2}),company.address_raw||company.location_raw||'Ubicación pendiente'),company.category_raw&&React.createElement('div',{style:{display:'flex',gap:8,flexWrap:'wrap',marginTop:16}},React.createElement(window.Pill,{tone:'guinda'},company.category_raw)),
        React.createElement('div',{style:{marginTop:18}},React.createElement(window.SectionHead,{title:'Sobre el beneficio'}),React.createElement('p',{style:{fontSize:15,color:'var(--ink-2)',fontWeight:500,lineHeight:1.6,margin:0}},company.description||'Información pendiente de publicación.')),
        React.createElement('div',{'data-convenio-benefits-state':'pending',style:{marginTop:18}},React.createElement(window.SectionHead,{title:'Beneficios disponibles',icon:'gift'}),React.createElement('div',{style:{background:'var(--surface)',borderRadius:14,padding:'13px 14px',boxShadow:'var(--neo-sm)',fontSize:12.5,color:'var(--ink-3)',fontWeight:700}},'Pendiente de información estructurada')),
        React.createElement('div',{'data-marketplace-company-products':products.length,style:{marginTop:20}},React.createElement(window.SectionHead,{title:'Productos y servicios',icon:'cart'}),products.length?React.createElement(window.CatalogGrid,{items:products,hue:345,icon:'cart',onOpen:(p)=>app.push('catitem',{item:p,ctx:{id:company.id,label:company.display_name,icon:'cart',hue:345}})}):React.createElement(window.EmptyState,{icon:'cart',title:'Sin productos publicados',sub:'La empresa aún no ha publicado productos o servicios.'})),
        images.length>1&&React.createElement('div',{style:{marginTop:20}},React.createElement(window.SectionHead,{title:'Imágenes'}),React.createElement('div',{style:{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10}},images.slice(1).map((src,i)=>React.createElement('button',{key:src,onClick:()=>setViewer(i+1),'aria-label':'Ampliar imagen '+(i+2),style:{border:'none',padding:0,background:'none',cursor:'zoom-in'}},React.createElement('img',{src,alt:company.display_name+' '+(i+2),loading:'lazy',style:{width:'100%',aspectRatio:'1.4',objectFit:'cover',borderRadius:14,display:'block'}}))))),
        React.createElement('div',{onClick:()=>app.setTab('credencial'),className:'su-press',style:{marginTop:18,background:'var(--guinda-50)',borderRadius:16,padding:16,display:'flex',gap:12,alignItems:'center',cursor:'pointer'}},React.createElement('div',{style:{width:44,height:44,borderRadius:12,background:'var(--surface)',display:'grid',placeItems:'center',color:'var(--guinda)'}},React.createElement(window.Res,{resKey:'convenios.detail.credencial',size:24,stroke:1.9})),React.createElement('div',{style:{flex:1}},React.createElement('div',{style:{fontSize:14,fontWeight:800,color:'var(--guinda)'}},'Muestra tu credencial digital'),React.createElement('div',{style:{fontSize:12.5,color:'var(--ink-2)',fontWeight:600}},'Toca para abrir tu QR')),React.createElement(I,{name:'chevR',size:20,stroke:2,style:{color:'var(--guinda)'}})))),
      React.createElement('div',{style:{position:'absolute',left:0,right:0,bottom:0,padding:'12px 20px calc(14px + env(safe-area-inset-bottom))',background:'linear-gradient(transparent,var(--surface) 22%)',display:'flex',gap:10}},React.createElement(window.Btn,{full:true,icon:'phone',disabled:!phone,onClick:()=>{if(phone)window.location.href='tel:'+phone;}},'Llamar'),React.createElement(window.Btn,{full:true,variant:'outline',icon:'message',disabled:!wa,onClick:()=>{if(wa)window.open('https://wa.me/'+wa,'_blank','noopener');}},'Mensaje')),
      viewer!==null&&React.createElement(window.ImageViewer,{sources:images,startIndex:viewer,alt:company.display_name,onClose:()=>setViewer(null)}));
  }

  Object.assign(window,{ConveniosScreen,ConvenioDetail});
})();
