/* Complete Savings administration workbench. All sections read/write through
   permission-gated RPCs; no Google, DATA, mocks or direct table writes. */
(function () {
  'use strict';
  const h = React.createElement;
  const I = window.Icon;
  const TABS = [
    ['summary', 'Resumen'], ['participants', 'Participantes'], ['contributions', 'Aportaciones'], ['calendar', 'Calendario'],
    ['amount_changes', 'Cambios de monto'], ['withdrawals', 'Retiros'], ['terminations', 'Bajas'], ['beneficiaries', 'Beneficiarios'],
    ['yields', 'Rendimientos'], ['omissions', 'Omisiones'], ['holds', 'Retenciones'], ['process', 'Cambios de PROCESS'],
    ['identity', 'Identidad pendiente'], ['documents', 'Documentos'], ['reports', 'Reportes'], ['audit', 'Auditoría'], ['config', 'Configuración'],
  ];
  const CSS = `
    .sava-root{min-height:100%;color:var(--ink)}.sava-page{padding:14px 16px 34px!important}.sava-banner{display:flex;align-items:flex-start;gap:10px;padding:11px 13px;border:1px solid #efd39a;border-radius:13px;background:#fff6df;color:#6f4c0e;font-size:11px;font-weight:750;line-height:1.45;margin-bottom:12px}.sava-banner svg{flex-shrink:0}
    .sava-kpis{display:grid;grid-template-columns:repeat(6,minmax(120px,1fr));gap:9px;margin-bottom:12px}.sava-kpi{padding:12px;border:1px solid var(--hairline);border-radius:15px;background:#fff;box-shadow:var(--neo-sm)}.sava-kpi span{display:block;color:var(--ink-3);font-size:9px;font-weight:850;text-transform:uppercase}.sava-kpi b{display:block;margin-top:4px;font-size:20px;font-weight:950}.sava-kpi:first-child{background:var(--grad-guinda-soft);color:#fff}.sava-kpi:first-child span{color:rgba(255,255,255,.82)}
    .sava-toolbar{display:flex;align-items:center;gap:9px;padding:11px;border:1px solid var(--hairline);border-radius:15px;background:#fff;box-shadow:var(--neo-sm)}.sava-search{flex:1;display:flex;align-items:center;gap:7px;min-width:180px;padding:0 10px;height:39px;border-radius:11px;background:var(--surface-2)}.sava-search input{width:100%;border:0;outline:0;background:transparent;font:700 12px var(--font);color:var(--ink)}.sava-toolbar select,.sava-input,.sava-select,.sava-textarea{border:1px solid var(--hairline);border-radius:10px;background:var(--surface-2);color:var(--ink);padding:9px 10px;font:700 11.5px var(--font);outline:none}.sava-toolbar select{max-width:270px}.sava-button{border:0;border-radius:10px;padding:9px 12px;background:var(--surface-2);color:var(--ink);font:850 11px var(--font);cursor:pointer}.sava-button.is-primary{background:var(--grad-guinda-soft);color:#fff}.sava-button.is-danger{background:#fce9ee;color:#a00027}.sava-button:disabled{opacity:.45;cursor:not-allowed}
    .sava-tabs{display:flex;gap:5px;overflow:auto;padding:10px 1px 8px;scrollbar-width:thin}.sava-tabs button{border:0;border-radius:999px;padding:8px 11px;background:#e9edf3;color:var(--ink-3);font:850 9.5px var(--font);white-space:nowrap;cursor:pointer}.sava-tabs button[aria-current=page]{background:var(--guinda);color:#fff}.sava-workbench{display:grid;grid-template-columns:minmax(245px,.72fr) minmax(0,1.8fr);gap:11px;min-height:570px}.sava-panel{min-width:0;overflow:hidden;border:1px solid var(--hairline);border-radius:16px;background:#fff;box-shadow:var(--neo-sm)}.sava-panel-head{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:12px 13px;border-bottom:1px solid var(--hairline)}.sava-panel-head h2{margin:0;font-size:14px}.sava-panel-head span{font-size:9px;font-weight:850;color:var(--ink-3)}.sava-list{max-height:610px;overflow:auto}.sava-person{width:100%;display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px 12px;border:0;border-bottom:1px solid var(--hairline);background:#fff;text-align:left;font-family:var(--font);cursor:pointer}.sava-person[aria-selected=true]{background:#fff3f6;box-shadow:inset 3px 0 var(--guinda)}.sava-person b,.sava-person span{display:block}.sava-person b{font-size:11.5px}.sava-person span{margin-top:2px;color:var(--ink-3);font-size:9.5px}.sava-person strong{font-size:10px;color:var(--guinda)}
    .sava-content{padding:13px;max-height:650px;overflow:auto}.sava-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.sava-card{min-width:0;padding:12px;border:1px solid var(--hairline);border-radius:13px;background:#fff}.sava-card h3{display:flex;align-items:center;gap:7px;margin:0 0 9px;font-size:12.5px}.sava-card p{margin:4px 0;color:var(--ink-3);font-size:10.5px;font-weight:650;line-height:1.45}.sava-value{font-size:19px;font-weight:950;color:var(--guinda)}.sava-facts{display:grid;grid-template-columns:1fr 1fr;gap:7px}.sava-fact{padding:8px;border-radius:9px;background:var(--surface-2)}.sava-fact span,.sava-field label{display:block;color:var(--ink-3);font-size:8.5px;font-weight:850;text-transform:uppercase}.sava-fact b{display:block;margin-top:3px;font-size:10.5px;overflow-wrap:anywhere}.sava-badge{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef1f5;color:#69748a;font-size:8.5px;font-weight:900}.sava-badge[data-tone=ok]{background:#e5f7ef;color:#087a50}.sava-badge[data-tone=warn]{background:#fff3d8;color:#8a5a00}.sava-badge[data-tone=danger]{background:#fce9ee;color:#a00027}
    .sava-table{width:100%;border-collapse:collapse;font-size:10px}.sava-table th{position:sticky;top:0;z-index:1;padding:8px;background:#f3f5f8;color:var(--ink-3);text-align:left;font-size:8px;text-transform:uppercase}.sava-table td{padding:9px 8px;border-top:1px solid var(--hairline);font-weight:700;vertical-align:top}.sava-table td:last-child{text-align:right}.sava-empty{display:grid;place-items:center;min-height:190px;padding:24px;text-align:center;color:var(--ink-3);font-size:11px;font-weight:700}.sava-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;padding:11px;margin-bottom:11px;border-radius:12px;background:var(--surface-2)}.sava-field{display:flex;flex-direction:column;gap:4px}.sava-field.is-wide{grid-column:span 2}.sava-input,.sava-select,.sava-textarea{width:100%;box-sizing:border-box;background:#fff}.sava-textarea{min-height:58px;resize:vertical}.sava-form-actions{display:flex;align-items:end}.sava-note{padding:10px;border-radius:10px;background:#fff6df;color:#765316;font-size:10px;font-weight:750;line-height:1.45;margin-bottom:10px}.sava-error{padding:10px;border-radius:10px;background:#fce9ee;color:#a00027;font-size:10px;font-weight:800;margin-bottom:10px}.sava-success{padding:10px;border-radius:10px;background:#e5f7ef;color:#087a50;font-size:10px;font-weight:800;margin-bottom:10px}.sava-actions{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.sava-section-title{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0 0 10px}.sava-section-title h2{margin:0;font-size:15px}.sava-section-title span{font-size:9px;color:var(--ink-3);font-weight:800}.sava-settings{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.sava-setting{display:grid;grid-template-columns:1fr auto;gap:9px;align-items:center;padding:11px;border:1px solid var(--hairline);border-radius:12px}.sava-setting b,.sava-setting span{display:block}.sava-setting b{font-size:11px}.sava-setting span{font-size:9px;color:var(--ink-3)}
    @media(max-width:1279px){.sava-kpis{grid-template-columns:repeat(3,1fr)}.sava-grid{grid-template-columns:repeat(2,1fr)}.sava-form{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:1023px){.sava-page{padding:12px 12px 90px!important}.sava-kpis{display:flex;overflow:auto}.sava-kpi{min-width:128px}.sava-toolbar{align-items:stretch;flex-direction:column}.sava-toolbar select{max-width:none}.sava-workbench{grid-template-columns:1fr}.sava-list{max-height:260px}.sava-content{max-height:none}.sava-grid,.sava-settings{grid-template-columns:1fr}.sava-form{grid-template-columns:1fr}.sava-field.is-wide{grid-column:auto}}
  `;
  const money = (value) => new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', minimumFractionDigits: 2 }).format(Number(value || 0));
  const date = (value) => value ? new Date(value + (String(value).length === 10 ? 'T12:00:00' : '')).toLocaleDateString('es-MX', { dateStyle: 'medium' }) : '—';
  const badgeTone = (value) => /MATCH|ACTIVE|APPROVED|CERTIFIED|SETTLED|APPLIED/.test(value || '') ? 'ok' : /MISMATCH|REJECT|MISSING/.test(value || '') ? 'danger' : 'warn';
  const Badge = ({ children }) => h('span', { className: 'sava-badge', 'data-tone': badgeTone(String(children)) }, children || '—');
  const Empty = ({ text }) => h('div', { className: 'sava-empty' }, text || 'Sin datos para esta sección.');
  function errorText(error) { const raw = String(error && (error.message || error.code) || ''); if (/42501|DENIED/.test(raw)) return 'Tu rol no tiene el permiso técnico requerido.'; if (/FIRST_EXPECTED/.test(raw)) return 'Debes indicar PROCESS y primera aportación esperada.'; if (/YIELD_PRODUCTIVE_DISABLED/.test(raw)) return 'La acreditación productiva de rendimiento está deshabilitada por diseño.'; return 'No se completó la operación. Revisa los datos y vuelve a intentar.'; }

  function Table({ columns, rows, renderActions }) {
    if (!rows || !rows.length) return h(Empty, {});
    return h('table', { className: 'sava-table' }, h('thead', null, h('tr', null, columns.map((column) => h('th', { key: column[0] }, column[1])), renderActions && h('th', null, 'Acciones'))), h('tbody', null, rows.map((row, index) => h('tr', { key: row.id || row.folio || index }, columns.map((column) => h('td', { key: column[0] }, column[2] ? column[2](row) : row[column[0]] == null ? '—' : String(row[column[0]]))), renderActions && h('td', null, renderActions(row))))));
  }

  function RequestSection({ rows, reload, app }) {
    const [busy, setBusy] = React.useState(''), [error, setError] = React.useState('');
    async function review(row, decision) {
      const reason = window.prompt(decision === 'APPROVE' ? 'Motivo de aprobación (mínimo 3 caracteres)' : 'Motivo del rechazo (mínimo 3 caracteres)');
      if (!reason) return;
      let first = null, process = null, effective = row.effective_from || null;
      if (decision === 'APPROVE' && row.request_type === 'JOIN') { process = window.prompt('PROCESS: JUB, PROCESS_1 o PROCESS_3'); first = window.prompt('Primera aportación esperada (AAAA-MM-DD)'); }
      if (decision === 'APPROVE' && row.request_type === 'CHANGE_AMOUNT') effective = window.prompt('Fecha futura de aplicación (AAAA-MM-DD)', effective || '');
      setBusy(row.id); setError(''); try { await window.SavingsRepository.reviewRequest({ requestId: row.id, decision, reason, process, firstExpectedContributionDate: first, effectiveFrom: effective }); app.toast && app.toast('Solicitud actualizada'); await reload(); } catch (failure) { setError(errorText(failure)); } finally { setBusy(''); }
    }
    async function dual(row, role, decision) { const reason = window.prompt('Motivo de la decisión (mínimo 3 caracteres)'); if (!reason) return; setBusy(row.id); setError(''); try { await window.SavingsRepository.recordRequestApproval({ requestId: row.id, approvalRole: role, decision, reason }); await reload(); } catch (failure) { setError(errorText(failure)); } finally { setBusy(''); } }
    async function settle(row) { const capital = window.prompt('Capital a liquidar', row.requested_capital_amount || row.requested_amount || '0'); if (capital == null) return; const yieldAmount = window.prompt('Rendimiento a liquidar', row.requested_yield_amount || '0'); if (yieldAmount == null) return; const reason = window.prompt('Motivo de liquidación'); if (!reason) return; setBusy(row.id); setError(''); try { await window.SavingsRepository.settleRequest({ requestId: row.id, capitalAmount: capital, yieldAmount, reason }); await reload(); } catch (failure) { setError(errorText(failure)); } finally { setBusy(''); } }
    return h(React.Fragment, null, error && h('div', { className: 'sava-error' }, error), h(Table, { rows, columns: [['folio', 'Folio'], ['request_type', 'Tipo'], ['status', 'Estado', (row) => h(Badge, null, row.status)], ['requested_amount', 'Monto', (row) => row.requested_amount == null ? '—' : money(row.requested_amount)], ['new_contribution_amount', 'Nueva aportación', (row) => row.new_contribution_amount == null ? '—' : money(row.new_contribution_amount)], ['effective_from', 'Vigencia', (row) => date(row.effective_from)], ['submitted_at', 'Enviada', (row) => date(row.submitted_at)]], renderActions: (row) => h('div', { className: 'sava-actions' }, row.request_type === 'EXTRAORDINARY_WITHDRAWAL' && ['SUBMITTED', 'UNDER_REVIEW'].includes(row.status) ? h(React.Fragment, null, h('button', { className: 'sava-button', disabled: busy === row.id, onClick: () => dual(row, 'GENERAL_SECRETARY', 'APPROVE') }, 'Sec. General'), h('button', { className: 'sava-button', disabled: busy === row.id, onClick: () => dual(row, 'FINANCE_SECRETARY', 'APPROVE') }, 'Finanzas')) : ['SUBMITTED', 'UNDER_REVIEW'].includes(row.status) && h(React.Fragment, null, h('button', { className: 'sava-button is-primary', disabled: busy === row.id, onClick: () => review(row, 'APPROVE') }, 'Aprobar'), h('button', { className: 'sava-button is-danger', disabled: busy === row.id, onClick: () => review(row, 'REJECT') }, 'Rechazar')), row.status === 'APPROVED' && ['WITHDRAW', 'EXTRAORDINARY_WITHDRAWAL', 'TERMINATE'].includes(row.request_type) && h('button', { className: 'sava-button is-primary', disabled: busy === row.id, onClick: () => settle(row) }, 'Liquidar')) }));
  }

  function SavingsAdminModule({ app, onBack, header, initialAffiliateId }) {
    const [globalData, setGlobalData] = React.useState(null), [detailData, setDetailData] = React.useState(null), [phase, setPhase] = React.useState('loading'), [error, setError] = React.useState('');
    const [selectedId, setSelectedId] = React.useState(''), [tab, setTab] = React.useState('summary'), [query, setQuery] = React.useState('');
    const [feedback, setFeedback] = React.useState(''), [busy, setBusy] = React.useState(false);
    const loadGlobal = React.useCallback(async () => { setPhase('loading'); setError(''); try { const value = await window.SavingsRepository.getAdminDashboard(null); setGlobalData(value); const candidates = value.participants || []; const initial = candidates.find((row) => row.affiliate_id === initialAffiliateId) || candidates.find((row) => row.id === selectedId) || candidates[0]; if (initial) setSelectedId(initial.id); setPhase('ready'); return value; } catch (failure) { setError(errorText(failure)); setPhase('error'); return null; } }, [initialAffiliateId]);
    React.useEffect(() => { loadGlobal(); }, [loadGlobal]);
    React.useEffect(() => { if (!selectedId) { setDetailData(null); return; } let active = true; window.SavingsRepository.getAdminDashboard(selectedId).then((value) => { if (active) setDetailData(value); }).catch((failure) => { if (active) setFeedback(errorText(failure)); }); return () => { active = false; }; }, [selectedId]);
    const reload = async () => { const value = await loadGlobal(); if (selectedId) setDetailData(await window.SavingsRepository.getAdminDashboard(selectedId)); return value; };
    const data = detailData || globalData || {};
    const allParticipants = globalData && globalData.participants || [];
    const visible = allParticipants.filter((row) => [row.display_name, row.legacy_folio, row.identity_status].join(' ').toLocaleLowerCase('es').includes(query.trim().toLocaleLowerCase('es')));
    const selected = allParticipants.find((row) => row.id === selectedId) || null;
    const kpis = globalData && globalData.kpis || {};
    async function run(task, success) { setBusy(true); setFeedback(''); try { await task(); setFeedback(success); await reload(); } catch (failure) { setFeedback(errorText(failure)); } finally { setBusy(false); } }

    function summary() { if (!selected) return h(Empty, { text: 'Selecciona un participante.' }); return h('div', null,
      h('div', { className: 'sava-section-title' }, h('h2', null, selected.display_name || selected.legacy_folio), h(Badge, null, selected.data_classification)),
      h('div', { className: 'sava-grid' },
        h('article', { className: 'sava-card' }, h('h3', null, h(I, { name: 'cash', size: 16 }), 'Saldo por ledger'), h('div', { className: 'sava-value' }, money(selected.total)), h('p', null, 'Capital ', money(selected.capital), ' · Rendimiento ', money(selected.yield))),
        h('article', { className: 'sava-card' }, h('h3', null, h(I, { name: 'shield', size: 16 }), 'Disponible / retenido'), h('div', { className: 'sava-value' }, money(selected.available)), h('p', null, 'Retenido ', money(selected.held))),
        h('article', { className: 'sava-card' }, h('h3', null, h(I, { name: 'refresh', size: 16 }), 'Q legacy'), h('div', { className: 'sava-value' }, selected.legacy_reported_balance == null ? '—' : money(selected.legacy_reported_balance)), h(Badge, null, selected.legacy_balance_status)),
        h('article', { className: 'sava-card' }, h('h3', null, 'Identidad'), h('div', { className: 'sava-facts' }, [['Folio', selected.legacy_folio], ['Vínculo afiliado', selected.affiliate_id], ['Tipo', selected.participant_type], ['Estado', selected.identity_status], ['Certificación', selected.certification_status]].map((pair) => h('div', { className: 'sava-fact', key: pair[0] }, h('span', null, pair[0]), h('b', null, pair[1] || '—'))))),
        h('article', { className: 'sava-card' }, h('h3', null, 'Inscripción'), h('div', { className: 'sava-facts' }, [['Estado', selected.enrollment_status], ['Secuencia', selected.sequence_number], ['Inicio', date(selected.enrollment_started_at)], ['Primera esperada', date(selected.first_expected_contribution_date)], ['Primera real', date(selected.first_actual_contribution_date)], ['Frecuencia', selected.frequency === 'MONTHLY' ? 'Mensual' : selected.frequency === 'TWICE_MONTHLY' ? 'Quincenal' : '—']].map((pair) => h('div', { className: 'sava-fact', key: pair[0] }, h('span', null, pair[0]), h('b', null, pair[1] || '—'))))),
        h('article', { className: 'sava-card' }, h('h3', null, 'Plan actual'), h('div', { className: 'sava-value' }, selected.current_contribution_amount == null ? '—' : money(selected.current_contribution_amount)), h('p', null, (selected.process_snapshot || selected.current_process || 'Sin PROCESS') + ' · sólo vigencia actual'))),
      h('div', { className: 'sava-section-title', style: { marginTop: 14 } }, h('h2', null, 'Movimientos recientes'), h('span', null, 'Ledger · sólo realizados')),
      h(Table, { rows: (data.history || []).slice(0, 12), columns: [['effective_date', 'Fecha', (row) => date(row.effective_date)], ['transaction_type', 'Concepto'], ['component', 'Componente'], ['direction', 'Dirección'], ['amount', 'Monto', (row) => money(row.amount)], ['data_classification', 'Clasificación', (row) => h(Badge, null, row.data_classification)]] })); }

    function participants() { return h(Table, { rows: visible, columns: [['legacy_folio', 'Folio'], ['display_name', 'Nombre'], ['participant_type', 'Tipo'], ['identity_status', 'Identidad', (row) => h(Badge, null, row.identity_status)], ['certification_status', 'Certificación', (row) => h(Badge, null, row.certification_status)], ['current_process', 'PROCESS'], ['total', 'Saldo', (row) => money(row.total)], ['legacy_balance_status', 'Q vs ledger', (row) => h(Badge, null, row.legacy_balance_status)]], renderActions: (row) => h('button', { className: 'sava-button', onClick: () => { setSelectedId(row.id); setTab('summary'); } }, 'Abrir') }); }

    function contributions() { const rows = data.contributions || []; return h('div', null, app.admin.has('savings.write') && selected && selected.enrollment_id && h(ContributionForm, { selected, busy, run }), h(Table, { rows, columns: [['contribution_date', 'Fecha', (row) => date(row.contribution_date)], ['expected_amount', 'Esperado', (row) => money(row.expected_amount)], ['actual_amount', 'Real', (row) => money(row.actual_amount)], ['difference', 'Diferencia', (row) => money(Number(row.actual_amount) - Number(row.expected_amount))], ['status', 'Estado', (row) => h(Badge, null, Number(row.actual_amount) === 0 && Number(row.expected_amount) > 0 ? 'MISSING' : Number(row.actual_amount) < Number(row.expected_amount) ? 'PARTIAL' : 'MATCH')], ['origin', 'Origen', () => 'ADMIN_OVERRIDE'], ['version_number', 'Versión'], ['editor_auth_user_id', 'Editado por'], ['reason', 'Motivo'], ['created_at', 'Fecha edición', (row) => date(row.created_at)]] })); }
    function ContributionForm({ selected: participant, busy: isBusy, run: execute }) { const [day, setDay] = React.useState(''), [actual, setActual] = React.useState(''), [reason, setReason] = React.useState(''); return h('div', { className: 'sava-form' }, h('div', { className: 'sava-field' }, h('label', null, 'Fecha esperada'), h('input', { className: 'sava-input', type: 'date', value: day, onChange: (e) => setDay(e.target.value) })), h('div', { className: 'sava-field' }, h('label', null, 'Monto real (acepta 0)'), h('input', { className: 'sava-input', type: 'number', min: '0', step: '.01', value: actual, onChange: (e) => setActual(e.target.value) })), h('div', { className: 'sava-field' }, h('label', null, 'Motivo obligatorio'), h('input', { className: 'sava-input', value: reason, onChange: (e) => setReason(e.target.value) })), h('div', { className: 'sava-form-actions' }, h('button', { className: 'sava-button is-primary', disabled: isBusy || !day || actual === '' || reason.trim().length < 3, onClick: () => execute(() => window.SavingsRepository.overrideContribution({ enrollmentId: participant.enrollment_id, contributionDate: day, actualAmount: actual, reason }), 'Aportación real registrada con nueva versión.') }, 'Guardar real'))); }

    function calendar() { return h(React.Fragment, null, h('div', { className: 'sava-note' }, 'Calendario generado bajo demanda. No se persisten columnas por año y la primera fecha esperada nunca se infiere.'), h(Table, { rows: data.calendar || [], columns: [['contribution_date', 'Fecha', (row) => date(row.contribution_date)], ['expected_amount', 'Esperado', (row) => money(row.expected_amount)], ['process_snapshot', 'PROCESS'], ['plan_id', 'Plan']] })); }
    function beneficiaries() { const rows = (data.beneficiaries || []).flatMap((version) => (version.items || []).map((item) => Object.assign({}, item, { version_number: version.version.version_number, version_status: version.version.status }))); return h(Table, { rows, columns: [['version_number', 'Versión'], ['version_status', 'Estado', (row) => h(Badge, null, row.version_status)], ['full_name', 'Nombre'], ['relationship', 'Parentesco'], ['percentage', 'Porcentaje', (row) => Number(row.percentage).toFixed(2) + '%']] }); }
    function omissions() { return h(React.Fragment, null, h('div', { className: 'sava-note' }, 'MISSING: esperado > 0 y real = 0. PARTIAL: real entre 0 y esperado. No se crea deuda automática. La regla de cuatro omisiones JUB está DESHABILITADA.'), h(Table, { rows: data.omissions || [], columns: [['contribution_date', 'Fecha', (row) => date(row.contribution_date)], ['expected_amount', 'Esperado', (row) => money(row.expected_amount)], ['actual_amount', 'Real', (row) => money(row.actual_amount)], ['difference', 'Diferencia', (row) => money(row.difference)], ['status', 'Estado', (row) => h(Badge, null, row.status)], ['reason', 'Motivo']] })); }
    function holds() { const [component, setComponent] = React.useState('CAPITAL'), [amount, setAmount] = React.useState(''), [reason, setReason] = React.useState(''); return h('div', null, app.admin.has('savings.write') && selected && h('div', { className: 'sava-form' }, h('div', { className: 'sava-field' }, h('label', null, 'Componente'), h('select', { className: 'sava-select', value: component, onChange: (e) => setComponent(e.target.value) }, h('option', { value: 'CAPITAL' }, 'Capital'), h('option', { value: 'YIELD' }, 'Rendimiento'))), h('div', { className: 'sava-field' }, h('label', null, 'Monto'), h('input', { className: 'sava-input', type: 'number', min: '0', value: amount, onChange: (e) => setAmount(e.target.value) })), h('div', { className: 'sava-field' }, h('label', null, 'Motivo'), h('input', { className: 'sava-input', value: reason, onChange: (e) => setReason(e.target.value) })), h('div', { className: 'sava-form-actions' }, h('button', { className: 'sava-button is-primary', disabled: busy || !Number(amount) || reason.trim().length < 3, onClick: () => run(() => window.SavingsRepository.createHold({ participantId: selected.id, enrollmentId: selected.enrollment_id, component, amount, reason }), 'Retención creada.') }, 'Retener'))), h(Table, { rows: data.holds || [], columns: [['component', 'Componente'], ['amount', 'Monto', (row) => money(row.amount)], ['status', 'Estado', (row) => h(Badge, null, row.status)], ['reason', 'Motivo'], ['created_at', 'Creada', (row) => date(row.created_at)]], renderActions: (row) => row.status === 'ACTIVE' && app.admin.has('savings.write') && h('button', { className: 'sava-button', onClick: () => { const why = window.prompt('Motivo de liberación'); if (why) run(() => window.SavingsRepository.releaseHold(row.id, why), 'Retención liberada.'); } }, 'Liberar') })); }
    function processChanges() { const [process, setProcess] = React.useState(selected && selected.current_process || 'PROCESS_1'), [reason, setReason] = React.useState(''); return h('div', null, h('div', { className: 'sava-note' }, 'Los cambios de categoría hechos en Admin Afiliados aparecen automáticamente aquí. El plan histórico nunca se reescribe.'), app.admin.has('savings.write') && app.admin.has('affiliates.write') && selected && h('div', { className: 'sava-form' }, h('div', { className: 'sava-field' }, h('label', null, 'Nuevo PROCESS'), h('select', { className: 'sava-select', value: process, onChange: (e) => setProcess(e.target.value) }, ['JUB', 'PROCESS_1', 'PROCESS_3'].map((value) => h('option', { key: value }, value)))), h('div', { className: 'sava-field is-wide' }, h('label', null, 'Motivo'), h('input', { className: 'sava-input', value: reason, onChange: (e) => setReason(e.target.value) })), h('div', { className: 'sava-form-actions' }, h('button', { className: 'sava-button is-primary', disabled: busy || reason.trim().length < 3, onClick: () => run(() => window.SavingsRepository.recordProcessChange(selected.id, process, reason), 'Evento de revisión PROCESS creado.') }, 'Registrar cambio'))), h(Table, { rows: data.process_changes || [], columns: [['legacy_folio', 'Folio'], ['old_process', 'Anterior'], ['new_process', 'Nuevo'], ['current_plan_snapshot', 'Plan vigente', (row) => row.current_plan_snapshot && row.current_plan_snapshot.amount ? money(row.current_plan_snapshot.amount) + ' · ' + row.current_plan_snapshot.process_snapshot : '—'], ['status', 'Impacto / estado', (row) => h(Badge, null, row.status)], ['effective_from', 'Vigencia', (row) => date(row.effective_from)], ['reason', 'Motivo'], ['created_at', 'Creado', (row) => date(row.created_at)]], renderActions: (row) => row.status === 'SAVINGS_PROCESS_CHANGE_REVIEW_REQUIRED' && app.admin.has('savings.approve') && h('div', { className: 'sava-actions' }, h('button', { className: 'sava-button is-primary', onClick: () => { const effective = window.prompt('Vigencia futura (AAAA-MM-DD)'); const why = window.prompt('Motivo de aprobación'); if (effective && why) run(() => window.SavingsRepository.reviewProcessChange({ eventId: row.id, decision: 'APPLY', effectiveFrom: effective, reason: why }), 'Cambio PROCESS aplicado sólo a futuro.'); } }, 'Aplicar'), h('button', { className: 'sava-button', onClick: () => { const why = window.prompt('Motivo para descartar el impacto'); if (why) run(() => window.SavingsRepository.reviewProcessChange({ eventId: row.id, decision: 'DISMISS', effectiveFrom: null, reason: why }), 'Impacto PROCESS descartado; evento preservado.'); } }, 'Descartar')) })); }
    function yields() { const [year, setYear] = React.useState(String(new Date().getFullYear())), [semester, setSemester] = React.useState('1'), [rate, setRate] = React.useState(''), [starts, setStarts] = React.useState(''), [ends, setEnds] = React.useState(''); return h('div', null, h('div', { className: 'sava-note' }, 'Fundación semestral preparada. productive_enabled = false: no existe acreditación automática ni fórmula productiva autorizada.'), app.admin.has('savings.config') && h('div', { className: 'sava-form' }, [['Año', year, setYear, 'number'], ['Semestre', semester, setSemester, 'number'], ['Inicio', starts, setStarts, 'date'], ['Cierre', ends, setEnds, 'date'], ['Tasa informada', rate, setRate, 'number']].map((field) => h('div', { className: 'sava-field', key: field[0] }, h('label', null, field[0]), h('input', { className: 'sava-input', type: field[3], value: field[1], onChange: (e) => field[2](e.target.value) }))), h('div', { className: 'sava-form-actions' }, h('button', { className: 'sava-button is-primary', disabled: busy || !starts || !ends, onClick: () => run(() => window.SavingsRepository.saveYieldPeriod({ year, semester, startsOn: starts, endsOn: ends, rate, status: 'DRAFT' }), 'Periodo guardado sin activar rendimiento.') }, 'Guardar borrador'))), h(Table, { rows: data.yield_periods || [], columns: [['period_year', 'Año'], ['semester', 'Semestre'], ['starts_on', 'Inicio', (row) => date(row.starts_on)], ['ends_on', 'Cierre', (row) => date(row.ends_on)], ['rate', 'Tasa'], ['status', 'Estado', (row) => h(Badge, null, row.status)], ['productive_enabled', 'Productivo', (row) => row.productive_enabled ? 'Sí' : 'NO']] })); }
    function identity() { return h(Table, { rows: data.pending_identity || [], columns: [['legacy_folio', 'Folio'], ['identity_status', 'Estado', (row) => h(Badge, null, row.identity_status)], ['possible_matches_count', 'Coincidencias exactas'], ['financial_record_exists', 'Expediente financiero', (row) => row.financial_record_exists ? 'Sí' : 'No'], ['participant_type', 'Tipo'], ['data_classification', 'Clasificación']], renderActions: (row) => app.admin.has('savings.identity_review') && h('button', { className: 'sava-button', onClick: () => { const affiliate = window.prompt('UUID exacto del afiliado con el mismo numero_control'); const why = window.prompt('Motivo de la vinculación'); if (affiliate && why) run(() => window.SavingsRepository.resolveIdentity(row.id, affiliate, why), 'Identidad vinculada; movimientos sin alterar.'); } }, 'Vincular') }); }
    function configuration() {
      const latest = {};
      (data.configuration || []).forEach((row) => {
        const key = row.action_code + ':' + row.scope_type + ':' + (row.participant_id || '');
        if (!latest[key]) latest[key] = row;
      });
      const settings = ['JOIN', 'CHANGE_AMOUNT', 'WITHDRAW', 'TERMINATE'].flatMap((action) =>
        ['GLOBAL', 'PARTICIPANT'].map((scope) => {
          const participantId = scope === 'PARTICIPANT' ? selectedId : null;
          const item = latest[action + ':' + scope + ':' + (participantId || '')];
          const toggle = () => {
            const why = window.prompt('Motivo de configuración');
            if (why) run(() => window.SavingsRepository.setActionAvailability({ actionCode: action, enabled: !(item && item.enabled), scopeType: scope, participantId, reason: why }), 'Disponibilidad actualizada.');
          };
          return h('div', { className: 'sava-setting', key: action + scope },
            h('div', null, h('b', null, action + ' · ' + scope), h('span', null, item ? (item.enabled ? 'Habilitada' : 'Deshabilitada') + ' · ' + item.reason : 'Sin configuración · fail closed')),
            h('button', { className: 'sava-button', disabled: busy || !app.admin.has('savings.config') || scope === 'PARTICIPANT' && !selectedId, onClick: toggle }, item && item.enabled ? 'Deshabilitar' : 'Habilitar'));
        }));
      return h('div', null,
        h('div', { className: 'sava-note' }, 'El backend resuelve primero la excepción individual vigente y después la regla global. Sin regla, la acción queda deshabilitada.'),
        h('div', { className: 'sava-settings' }, settings));
    }

    const holdsView = holds();
    const processView = processChanges();
    const yieldsView = yields();

    function content() {
      if (tab === 'summary') return summary(); if (tab === 'participants') return participants(); if (tab === 'contributions') return contributions(); if (tab === 'calendar') return calendar();
      if (tab === 'amount_changes') return h(RequestSection, { rows: data.amount_changes || [], reload, app }); if (tab === 'withdrawals') return h(RequestSection, { rows: data.withdrawals || [], reload, app }); if (tab === 'terminations') return h(RequestSection, { rows: data.terminations || [], reload, app });
      if (tab === 'beneficiaries') return beneficiaries(); if (tab === 'yields') return yieldsView; if (tab === 'omissions') return omissions(); if (tab === 'holds') return holdsView; if (tab === 'process') return processView; if (tab === 'identity') return identity();
      if (tab === 'documents') return h(Table, { rows: data.documents || [], columns: [['folio', 'Solicitud'], ['participant_id', 'Participante'], ['document_id', 'Documento'], ['status', 'Estado', (row) => h(Badge, null, row.status)]] });
      if (tab === 'reports') return h(React.Fragment, null, h('div', { className: 'sava-note' }, 'Los lotes requieren snapshot certificado, SHA-256 y service_role fuera del navegador. Esta pantalla no ejecuta importaciones.'), h(Table, { rows: data.reports || [], columns: [['source_workbook_name', 'Origen'], ['source_snapshot_sha256', 'Hash'], ['certification_status', 'Certificación', (row) => h(Badge, null, row.certification_status)], ['status', 'Estado', (row) => h(Badge, null, row.status)], ['row_counts', 'Conteos', (row) => JSON.stringify(row.row_counts)], ['started_at', 'Fecha', (row) => date(row.started_at)]] }));
      if (tab === 'audit') return h(Table, { rows: data.audit || [], columns: [['created_at', 'Fecha', (row) => date(row.created_at)], ['resource', 'Recurso'], ['action', 'Acción'], ['target_id', 'Objetivo'], ['actor_real_auth_user_id', 'Actor real'], ['usuario_contexto_affiliate_id', 'Usuario contexto'], ['reason', 'Motivo']] });
      if (tab === 'config') return configuration(); return h(Empty, {});
    }

    return h('div', { className: 'sava-root', 'data-admin-savings': phase, 'data-savings-authority': globalData && globalData.authority, 'data-savings-cutover': globalData && globalData.cutover_status },
      header({ title: 'Caja de Ahorro', sub: 'SHADOW + NEW FOUNDATION · sin cutover', onBack }), h('style', null, CSS),
      h('div', { className: 'su-app-scroll sava-page' },
        h('div', { className: 'sava-banner' }, h(I, { name: 'info', size: 17 }), h('div', null, h('b', null, 'Google continúa como autoridad histórica/productiva.'), h('br'), 'Esta consola administra únicamente la fundación shadow. Los valores Q se comparan con el ledger y nunca sustituyen el saldo.')),
        phase === 'error' ? h('div', { className: 'sava-error' }, error, h('button', { className: 'sava-button', onClick: loadGlobal, style: { marginLeft: 10 } }, 'Reintentar')) : h(React.Fragment, null,
          h('div', { className: 'sava-kpis' }, [['Participantes activos', kpis.active_enrollments || 0], ['Capital total', money(kpis.capital_total)], ['Rendimientos', money(kpis.yield_total)], ['Saldo total', money(kpis.balance_total)], ['Saldo retenido', money(kpis.held_total)], ['Retiros pendientes', kpis.pending_withdrawals || 0], ['Cambios de monto', kpis.pending_amount_changes || 0], ['PROCESS por revisar', kpis.process_reviews || 0], ['Identidades ambiguas', kpis.ambiguous_identity || 0], ['Identidades huérfanas', kpis.orphan_identity || 0]].map((item) => h('div', { className: 'sava-kpi', key: item[0] }, h('span', null, item[0]), h('b', null, item[1])))),
          h('div', { className: 'sava-toolbar' }, h('label', { className: 'sava-search' }, h(I, { name: 'search', size: 16 }), h('input', { value: query, onChange: (event) => setQuery(event.target.value), placeholder: 'Buscar folio, nombre o estado…' })), h('select', { value: selectedId, onChange: (event) => setSelectedId(event.target.value) }, h('option', { value: '' }, 'Todos / sin selección'), allParticipants.map((row) => h('option', { key: row.id, value: row.id }, (row.legacy_folio || 'Sin folio') + ' · ' + (row.display_name || row.identity_status)))), h('button', { className: 'sava-button', onClick: reload, disabled: busy }, 'Actualizar')),
          feedback && h('div', { className: /No se|permiso|completó/.test(feedback) ? 'sava-error' : 'sava-success', style: { marginTop: 10 } }, feedback),
          h('nav', { className: 'sava-tabs', 'aria-label': 'Secciones de Ahorro' }, TABS.map((item) => h('button', { key: item[0], 'aria-current': tab === item[0] ? 'page' : undefined, onClick: () => setTab(item[0]), 'data-savings-admin-tab': item[0] }, item[1]))),
          h('div', { className: 'sava-workbench' }, h('aside', { className: 'sava-panel' }, h('div', { className: 'sava-panel-head' }, h('h2', null, 'Participantes'), h('span', null, visible.length + ' visibles')), h('div', { className: 'sava-list' }, visible.length ? visible.map((row) => h('button', { className: 'sava-person', key: row.id, 'aria-selected': selectedId === row.id, onClick: () => setSelectedId(row.id) }, h('span', null, h('b', null, row.display_name || 'Identidad sin resolver'), h('span', null, (row.legacy_folio || 'Sin folio') + ' · ' + row.identity_status)), h('strong', null, money(row.total)))) : h(Empty, { text: 'Sin coincidencias.' }))), h('section', { className: 'sava-panel' }, h('div', { className: 'sava-panel-head' }, h('h2', null, (TABS.find((item) => item[0] === tab) || [null, tab])[1]), h('span', null, selected ? selected.legacy_folio : 'Vista global')), h('div', { className: 'sava-content' }, phase === 'loading' ? h(Empty, { text: 'Cargando Ahorro desde Supabase…' }) : content()))))));
  }

  window.SavingsAdminModule = SavingsAdminModule;
})();
