/* Administrative affiliate file and identity context. Supabase RPC is the only authority. */
(function () {
  const DOC_STATES={VERIFIED:{label:'Verificado',color:'#087A50'},PENDING_REVIEW:{label:'Pendiente de revisión',color:'#A56600'},UNDER_REVIEW:{label:'En revisión',color:'#A56600'},REJECTED:{label:'Rechazado',color:'#A00027'},REUPLOAD_REQUIRED:{label:'Requiere nueva carga',color:'#A00027'}};
  const newestDocument=(rows,typeId)=>rows.filter(d=>d.document_type_id===typeId).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]||null;
  function IdentityAccessModule({ app, onBack, header }) {
    const [query,setQuery]=React.useState(''),[rows,setRows]=React.useState([]),[selected,setSelected]=React.useState(null);
    const [reason,setReason]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
    const [profile,setProfile]=React.useState(null),[documents,setDocuments]=React.useState([]),[documentTypes,setDocumentTypes]=React.useState([]),[canonicalDocuments,setCanonicalDocuments]=React.useState([]),[options,setOptions]=React.useState({union:[],employment_category:[]});
    const [form,setForm]=React.useState({}),[editReason,setEditReason]=React.useState('');
    const search=async()=>{if(query.trim().length<2)return;setBusy(true);setError('');try{const found=await window.AdminRepository.searchAffiliates(query);setRows(found);}catch(_){setError('No fue posible consultar afiliados.');}finally{setBusy(false);}};
    const loadDocuments=async(affiliateId)=>{if(!app.admin.has('assets.read'))return;const raw=await window.AffiliateRepository.getHistoricalDocuments(affiliateId);setDocuments(raw);if(app.admin.has('documents.read')){const[types,canonical]=await Promise.all([window.DocumentWorkflowRepository.catalog(),window.DocumentWorkflowRepository.list(affiliateId)]);setDocumentTypes(types.slice());setCanonicalDocuments(canonical.slice());}else{setDocumentTypes([]);setCanonicalDocuments([]);}};
    const select=async(row)=>{setSelected(row);setProfile(null);setDocuments([]);setDocumentTypes([]);setCanonicalDocuments([]);setError('');if(!app.admin.has('affiliates.read'))return;setBusy(true);try{const result=await window.AdminRepository.getAffiliateProfile(row.id);setProfile(result.profile);setOptions(result.options||{union:[],employment_category:[]});setForm(result.profile||{});await loadDocuments(row.id);}catch(_){setError('No fue posible cargar el expediente del afiliado.');}finally{setBusy(false);}};
    const start=async()=>{if(!selected||reason.trim().length<8)return;setBusy(true);setError('');try{await window.AdminRepository.startImpersonation(selected.id,reason);app.toast('Contexto administrativo activado');}catch(_){setError('No fue posible activar el contexto. Verifica la sesión administrativa.');}finally{setBusy(false);}};
    const fields=['full_name','display_name','phone_raw','unit_raw','city_raw','employment_position_raw','employment_area_raw','financial_union_code','financial_employee_category_code','financial_employee_type','financial_affiliation_status','financial_employment_status'];
    const save=async()=>{if(!profile||editReason.trim().length<8)return;const patch={};fields.forEach(k=>{if((form[k]||'')!==(profile[k]||''))patch[k]=form[k]||null;});if(!Object.keys(patch).length){setError('No hay cambios por guardar.');return;}setBusy(true);setError('');try{const result=await window.AdminRepository.updateAffiliateProfile(selected.id,profile.financial_profile_version,patch,editReason);setProfile(result.profile);setOptions(result.options||options);setForm(result.profile||{});setEditReason('');app.toast('Expediente actualizado y auditado');}catch(e){setError(e&&String(e.message).includes('PROFILE_VERSION_CONFLICT')?'El expediente cambió en otra sesión. Vuelve a seleccionarlo.':'No fue posible guardar el expediente. Verifica permisos y valores.');}finally{setBusy(false);}};
    const inputStyle={width:'100%',height:43,border:'none',borderRadius:12,padding:'0 12px',boxSizing:'border-box',background:'var(--surface-2)',color:'var(--ink)',fontFamily:'inherit',fontSize:13,fontWeight:650};
    const field=(key,label,type)=>React.createElement('label',{key,style:{display:'grid',gap:6,fontSize:11.5,fontWeight:800,color:'var(--ink-3)'}},label,
      type?React.createElement('select',{value:form[key]||'',disabled:!app.admin.has('affiliates.write'),onChange:e=>setForm(Object.assign({},form,{[key]:e.target.value})),style:inputStyle},React.createElement('option',{value:''},'Sin dato'),(options[type]||[]).map(o=>React.createElement('option',{key:o.code,value:o.code},o.label))):
      React.createElement('input',{value:form[key]||'',disabled:!app.admin.has('affiliates.write'),onChange:e=>setForm(Object.assign({},form,{[key]:e.target.value})),maxLength:160,style:inputStyle}));
    return React.createElement('div',null,
      header({title:'Identidad y expediente',sub:'Perfil actual · actor real auditado · contexto máximo 30 minutos',onBack}),
      React.createElement('div',{className:'su-app-scroll',style:{padding:18}},
        React.createElement('div',{style:{background:'var(--surface)',borderRadius:18,padding:16,boxShadow:'var(--neo-sm)'}},
          React.createElement('div',{style:{fontSize:13,fontWeight:800,color:'var(--ink-2)',lineHeight:1.45}},'Busca por nombre o número de control. La contraseña, Auth, número de control y solicitudes históricas no se modifican.'),
          React.createElement('div',{style:{display:'flex',gap:9,marginTop:14}},
            React.createElement('input',{value:query,onChange:e=>setQuery(e.target.value),onKeyDown:e=>{if(e.key==='Enter')search();},placeholder:'Nombre o número de control',style:{flex:1,minWidth:0,height:46,border:'none',borderRadius:13,padding:'0 13px',background:'var(--surface-2)',color:'var(--ink)',fontSize:14,fontWeight:650}}),
            React.createElement(window.Btn,{onClick:search,disabled:busy||query.trim().length<2},busy?'Buscando…':'Buscar')),
          React.createElement('div',{style:{display:'grid',gap:8,marginTop:12}},rows.map(row=>React.createElement('button',{key:row.id,onClick:()=>select(row),style:{display:'flex',alignItems:'center',gap:11,border:selected&&selected.id===row.id?'2px solid var(--guinda)':'1px solid var(--line)',borderRadius:13,padding:'11px 12px',background:'var(--surface)',textAlign:'left',cursor:'pointer',fontFamily:'inherit'}},
            React.createElement(window.Avatar,{name:row.display_name||row.full_name||'Afiliado',src:row.profilePhotoUrl||undefined,size:40,'data-profile-photo-consumer':'admin-affiliate'}),
            React.createElement('div',{style:{minWidth:0}},React.createElement('div',{style:{fontSize:14,fontWeight:850,color:'var(--ink)'}},row.display_name||row.full_name||'Afiliado'),React.createElement('div',{style:{fontSize:12,fontWeight:650,color:'var(--ink-3)',marginTop:3}},'Número de control: '+(row.numero_control||'vacío')+' · '+row.auth_eligibility))))),
          profile&&React.createElement('div',{'data-affiliate-editable-file':'supabase',style:{marginTop:16,paddingTop:16,borderTop:'1px solid var(--line)'}},
            React.createElement('div',{style:{fontSize:15,fontWeight:900,color:'var(--ink)'}},'Expediente editable del afiliado'),
            React.createElement('div',{style:{fontSize:11.5,fontWeight:650,color:'var(--ink-3)',lineHeight:1.5,marginTop:4}},'Los cambios se usan inmediatamente en futuras consultas financieras. Las solicitudes existentes conservan su snapshot.'),
            React.createElement('div',{style:{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10,marginTop:14}},field('full_name','NOMBRE COMPLETO'),field('display_name','NOMBRE VISIBLE'),field('phone_raw','TELÉFONO'),field('city_raw','CIUDAD'),field('unit_raw','UNIDAD'),field('employment_position_raw','PUESTO'),field('employment_area_raw','ÁREA'),field('financial_union_code','SINDICATO FINANCIERO','union'),field('financial_employee_category_code','CATEGORÍA DE EMPLEADO','employment_category'),field('financial_employee_type','TIPO DE EMPLEADO'),field('financial_affiliation_status','ESTATUS DE AFILIACIÓN'),field('financial_employment_status','ESTATUS LABORAL')),
            app.admin.has('affiliates.write')?React.createElement(React.Fragment,null,React.createElement('textarea',{value:editReason,onChange:e=>setEditReason(e.target.value),placeholder:'Motivo del cambio (mínimo 8 caracteres)',maxLength:500,style:{width:'100%',minHeight:72,resize:'vertical',boxSizing:'border-box',marginTop:12,border:'none',borderRadius:13,padding:12,background:'var(--surface-2)',color:'var(--ink)',fontFamily:'inherit',fontSize:13}}),React.createElement(window.Btn,{full:true,onClick:save,disabled:busy||editReason.trim().length<8,style:{marginTop:9}},busy?'Guardando…':'Guardar cambios auditados')):React.createElement('div',{style:{marginTop:12,padding:11,borderRadius:12,background:'var(--surface-2)',fontSize:12,fontWeight:700,color:'var(--ink-3)'}},'Consulta solamente. Se requiere el permiso affiliates.write para editar.'),
            app.admin.has('assets.read')&&React.createElement(AdminDigitalFile,{app,affiliateId:selected.id,types:documentTypes,canonical:canonicalDocuments,historical:documents,onChanged:()=>loadDocuments(selected.id)})),
          selected&&React.createElement(React.Fragment,null,React.createElement('textarea',{value:reason,onChange:e=>setReason(e.target.value),placeholder:'Motivo operativo obligatorio (mínimo 8 caracteres)',maxLength:500,style:{width:'100%',minHeight:82,resize:'vertical',boxSizing:'border-box',marginTop:14,border:'none',borderRadius:13,padding:12,background:'var(--surface-2)',color:'var(--ink)',fontFamily:'inherit',fontSize:14}}),React.createElement(window.Btn,{full:true,onClick:start,disabled:busy||reason.trim().length<8,style:{marginTop:10}},'Solicitar préstamo a nombre del afiliado')),
          error&&React.createElement('div',{role:'alert',style:{marginTop:12,color:'#A32921',fontSize:13,fontWeight:750}},error))));
  }
  function documentVisual(doc,height){const image=doc&&String(doc.mimeType||'').startsWith('image/')&&doc.signedUrl;return React.createElement('div',{style:{height:height||112,borderRadius:12,overflow:'hidden',background:'linear-gradient(145deg,#F3F5F9,#E7EBF2)',display:'grid',placeItems:'center'}},image?React.createElement('img',{src:doc.signedUrl,alt:'',loading:'lazy',style:{width:'100%',height:'100%',objectFit:'cover'}}):React.createElement(window.Icon,{name:doc&&doc.mimeType==='application/pdf'?'doc':(doc&&doc.icon)||'folder',size:31,stroke:1.7,style:{color:'var(--guinda)',opacity:.72}}));}
  function DocumentInspector({entry,onClose,onNavigate,onReview,canReview}){
    if(!entry||!entry.doc)return null;
    const doc=entry.doc,total=entry.items.length,index=entry.index,state=doc.status&&DOC_STATES[doc.status];
    const image=String(doc.mimeType||'').startsWith('image/'),pdf=doc.mimeType==='application/pdf';
    const content=image
      ?React.createElement('img',{src:doc.signedUrl,alt:doc.label||'Documento',style:{maxWidth:'100%',maxHeight:'100%',objectFit:'contain',borderRadius:10,boxShadow:'0 8px 30px rgba(0,0,0,.15)'}})
      :pdf?React.createElement('iframe',{src:doc.signedUrl,title:doc.label||'Documento PDF',style:{width:'100%',height:'100%',border:0,borderRadius:10,background:'#fff'}})
      :React.createElement('div',{style:{textAlign:'center',color:'var(--ink-3)'}},React.createElement(window.Icon,{name:'doc',size:52,stroke:1.5}),React.createElement('div',{style:{fontSize:13,fontWeight:800,marginTop:10}},'Este formato se abre en su visor original.'));
    return React.createElement('div',{role:'dialog','aria-modal':'true','aria-label':'Vista previa del documento','data-document-inspector':'true',onClick:onClose,style:{position:'fixed',inset:0,zIndex:10000,background:'rgba(10,17,30,.72)',backdropFilter:'blur(8px)',display:'flex',alignItems:'center',justifyContent:'center',padding:16}},
      React.createElement('div',{onClick:e=>e.stopPropagation(),style:{width:'min(920px,100%)',height:'min(86vh,760px)',background:'var(--surface)',borderRadius:22,boxShadow:'0 28px 80px rgba(0,0,0,.35)',display:'flex',flexDirection:'column',overflow:'hidden'}},
        React.createElement('div',{style:{display:'flex',alignItems:'center',gap:10,padding:'12px 14px',borderBottom:'1px solid var(--line)'}},
          React.createElement('div',{style:{flex:1,minWidth:0}},React.createElement('div',{style:{fontSize:14,fontWeight:900,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},doc.label||'Documento'),React.createElement('div',{style:{fontSize:10.5,color:state?state.color:'var(--ink-3)',marginTop:2}},state?state.label:(doc.expedienteClassification||doc.sourceColumn||'Histórico')+(doc.created_at||doc.createdAt?' · '+new Date(doc.created_at||doc.createdAt).toLocaleDateString('es-MX'):''))),
          doc.signedUrl&&React.createElement('a',{href:doc.signedUrl,target:'_blank',rel:'noopener noreferrer',style:{textDecoration:'none',fontSize:11.5,fontWeight:850,color:'var(--guinda)',padding:'8px 10px',borderRadius:10,background:'var(--surface-2)'}},'Abrir original'),
          React.createElement('button',{type:'button',onClick:onClose,'aria-label':'Cerrar vista previa',style:{width:36,height:36,border:0,borderRadius:11,background:'var(--surface-2)',display:'grid',placeItems:'center',color:'var(--ink)'}},'×')),
        React.createElement('div',{style:{flex:1,minHeight:0,display:'grid',placeItems:'center',background:'#EEF1F5',padding:12}},content),
        React.createElement('div',{style:{display:'flex',alignItems:'center',gap:8,padding:'10px 14px',borderTop:'1px solid var(--line)'}},
          React.createElement('button',{type:'button','data-document-previous':'true',disabled:index<=0,onClick:()=>onNavigate(-1),style:{border:0,borderRadius:10,padding:'8px 11px',fontWeight:850}},'Anterior'),
          React.createElement('div',{style:{fontSize:11,fontWeight:800,color:'var(--ink-3)'}},(index+1)+' / '+total),
          React.createElement('button',{type:'button','data-document-next':'true',disabled:index>=total-1,onClick:()=>onNavigate(1),style:{border:0,borderRadius:10,padding:'8px 11px',fontWeight:850}},'Siguiente'),
          React.createElement('div',{style:{flex:1}}),
          canReview&&doc.status!=='VERIFIED'&&React.createElement(React.Fragment,null,
            React.createElement('button',{type:'button',onClick:()=>onReview(doc.id,'VERIFIED'),style:{border:0,borderRadius:10,padding:'8px 10px',background:'#E5F7EF',color:'#087A50',fontWeight:850}},'Aprobar'),
            React.createElement('button',{type:'button',onClick:()=>onReview(doc.id,'REJECTED'),style:{border:0,borderRadius:10,padding:'8px 10px',background:'#FCE9EE',color:'#A00027',fontWeight:850}},'Rechazar'),
            React.createElement('button',{type:'button',onClick:()=>onReview(doc.id,'REUPLOAD_REQUIRED'),style:{border:0,borderRadius:10,padding:'8px 10px',background:'#FFF2D8',color:'#8A5900',fontWeight:850}},'Pedir recarga')))));
  }
  function AdminDigitalFile({app,affiliateId,types,canonical,historical,onChanged}){
    const[preview,setPreview]=React.useState(null),[historicalFilter,setHistoricalFilter]=React.useState('all'),[historicalOpen,setHistoricalOpen]=React.useState(true);
    const required=types.filter(t=>t.required_by_default),verified=required.filter(t=>{const d=newestDocument(canonical,t.id);return d&&d.status==='VERIFIED';}).length,extras=historical;
    const hashCounts=extras.reduce((m,d)=>{if(d.sha256)m[d.sha256]=(m[d.sha256]||0)+1;return m;},{}),duplicateCount=extras.filter(d=>d.sha256&&hashCounts[d.sha256]>1).length;
    const isTechnical=d=>d.expedienteClassification==='HISTORICAL_NON_DOCUMENT';
    const shownExtras=extras.filter(d=>historicalFilter==='all'||(historicalFilter==='document'&&!isTechnical(d))||(historicalFilter==='technical'&&isTechnical(d))||(historicalFilter==='image'&&d.kind==='image')||(historicalFilter==='pdf'&&d.kind==='pdf')||(historicalFilter==='duplicate'&&d.sha256&&hashCounts[d.sha256]>1));
    const canonicalPreviewItems=types.map(type=>{const doc=newestDocument(canonical,type.id);return doc&&doc.signedUrl?Object.assign({label:type.label},doc):null;}).filter(Boolean);
    const openPreview=(doc,items)=>{const index=Math.max(0,items.findIndex(item=>item.id===doc.id));setPreview({doc:items[index]||doc,items,index});};
    const navigate=delta=>setPreview(current=>{if(!current)return current;const index=Math.max(0,Math.min(current.items.length-1,current.index+delta));return Object.assign({},current,{index,doc:current.items[index]});});
    const review=async(id,status)=>{try{const observation=status==='VERIFIED'?'':prompt('Observación para el afiliado:')||'';if(status!=='VERIFIED'&&!observation.trim())return;await window.DocumentWorkflowRepository.review(id,status,observation);setPreview(null);await onChanged();}catch(_){app.toast&&app.toast('No se pudo actualizar el documento');}};
    const canonicalCards=types.map(type=>{
      const doc=newestDocument(canonical,type.id),state=doc?DOC_STATES[doc.status]:{label:'Faltante',color:'#A00027'},canPreview=doc&&doc.signedUrl;
      const details=React.createElement('div',{style:{padding:'9px 2px 3px'}},
        React.createElement('div',{style:{fontSize:12.5,fontWeight:900,lineHeight:1.25,color:'var(--ink)'}},type.label),
        React.createElement('div',{style:{display:'flex',alignItems:'center',gap:6,marginTop:5}},React.createElement('span',{style:{width:7,height:7,borderRadius:'50%',background:state.color,flexShrink:0}}),React.createElement('span',{style:{fontSize:10.5,fontWeight:850,color:state.color}},state.label)),
        type.required_by_default&&React.createElement('div',{style:{fontSize:9,fontWeight:900,color:'var(--guinda)',marginTop:5,letterSpacing:'.04em'}},'OBLIGATORIO'));
      const actions=doc&&app.admin.has('documents.write')&&doc.status!=='VERIFIED'&&React.createElement('div',{style:{display:'flex',gap:6,marginTop:5}},
        React.createElement('button',{onClick:()=>review(doc.id,'VERIFIED'),style:{flex:1,border:'none',borderRadius:9,padding:7,background:'#E5F7EF',color:'#087A50',fontSize:10.5,fontWeight:850}},'Aprobar'),
        React.createElement('button',{onClick:()=>review(doc.id,'REJECTED'),style:{flex:1,border:'none',borderRadius:9,padding:7,background:'#FCE9EE',color:'#A00027',fontSize:10.5,fontWeight:850}},'Rechazar'),
        React.createElement('button',{onClick:()=>review(doc.id,'REUPLOAD_REQUIRED'),style:{flex:1,border:'none',borderRadius:9,padding:7,background:'#FCE9EE',color:'#A00027',fontSize:10.5,fontWeight:850}},'Recargar'));
      return React.createElement('article',{key:type.id,'data-admin-document-type':type.code,'data-admin-document-status':doc?doc.status:'MISSING','data-admin-global-required':type.required_by_default?'true':'false',style:{border:'1px solid var(--line)',borderRadius:16,padding:9,background:'var(--surface)',boxShadow:'0 5px 16px rgba(18,31,53,.06)'}},
        React.createElement('button',{type:'button',disabled:!canPreview,onClick:()=>canPreview&&openPreview(Object.assign({label:type.label},doc),canonicalPreviewItems),style:{display:'block',width:'100%',border:0,padding:0,background:'transparent',cursor:canPreview?'zoom-in':'default',fontFamily:'inherit',textAlign:'left'}},documentVisual(doc,104),details),
        doc&&doc.review_observation&&React.createElement('div',{style:{fontSize:10.5,color:'#A00027',padding:'0 2px 6px'}},doc.review_observation),actions);
    });
    const filterButtons=[['all','Todos · '+extras.length],['document','Documentos históricos'],['technical','Técnicos ocultos'],['image','Imágenes'],['pdf','PDF'],['duplicate','Posibles duplicados · '+duplicateCount]].map(([id,label])=>React.createElement('button',{key:id,type:'button',onClick:()=>setHistoricalFilter(id),'aria-pressed':historicalFilter===id,style:{whiteSpace:'nowrap',border:0,borderRadius:999,padding:'8px 11px',background:historicalFilter===id?'var(--guinda)':'var(--surface-2)',color:historicalFilter===id?'#fff':'var(--ink-2)',fontSize:10.5,fontWeight:850}},label));
    const historicalCards=shownExtras.map(doc=>{
      const duplicate=doc.sha256&&hashCounts[doc.sha256]>1;
      return React.createElement('button',{key:doc.id,type:'button','data-admin-document-owner':doc.affiliateId,'data-admin-historical-kind':doc.kind,'data-admin-historical-classification':doc.expedienteClassification,'data-admin-duplicate-candidate':duplicate?'true':'false',onClick:()=>openPreview(doc,shownExtras),style:{border:'1px solid var(--line)',borderRadius:15,padding:8,background:'var(--surface)',fontFamily:'inherit',textAlign:'left',cursor:'zoom-in',boxShadow:'0 4px 14px rgba(18,31,53,.05)',minWidth:0}},
        documentVisual(doc,96),React.createElement('div',{style:{padding:'8px 2px 2px'}},React.createElement('div',{style:{fontSize:11.5,fontWeight:900,color:'var(--ink)',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},doc.label),React.createElement('div',{style:{fontSize:9.5,fontWeight:700,color:'var(--ink-3)',marginTop:3,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},doc.sourceColumn||doc.fileKey||doc.mimeType),React.createElement('span',{style:{display:'inline-block',marginTop:6,borderRadius:999,padding:'3px 6px',background:isTechnical(doc)?'#FCE9EE':'#EEF3FF',color:isTechnical(doc)?'#A00027':'#31558C',fontSize:8.5,fontWeight:900}},isTechnical(doc)?'TÉCNICO OCULTO':'DOCUMENTO HISTÓRICO'),duplicate&&React.createElement('span',{style:{display:'inline-block',margin:'6px 0 0 4px',borderRadius:999,padding:'3px 6px',background:'#FFF2D8',color:'#8A5900',fontSize:8.5,fontWeight:900}},'MISMO HASH')));
    });
    const historicalSection=extras.length>0&&React.createElement('section',{'data-admin-historical-unclassified':extras.length,style:{marginTop:22,paddingTop:16,borderTop:'1px solid var(--line)'}},
      React.createElement('button',{type:'button',onClick:()=>setHistoricalOpen(v=>!v),'aria-expanded':historicalOpen,style:{width:'100%',border:0,background:'transparent',padding:0,display:'flex',alignItems:'center',gap:10,textAlign:'left',fontFamily:'inherit',color:'var(--ink)'}},React.createElement('div',{style:{width:38,height:38,borderRadius:12,background:'#FFF2D8',color:'#966000',display:'grid',placeItems:'center'}},React.createElement(window.Icon,{name:'folder',size:20,stroke:2})),React.createElement('div',{style:{flex:1}},React.createElement('div',{style:{fontSize:13.5,fontWeight:950}},'Auditoría histórica'),React.createElement('div',{style:{fontSize:10.5,color:'var(--ink-3)',marginTop:2}},extras.length+' elementos preservados · visibles sólo para Administración')),React.createElement(window.Icon,{name:historicalOpen?'chevU':'chevD',size:18,stroke:2})),
      historicalOpen&&React.createElement(React.Fragment,null,React.createElement('div',{style:{display:'flex',gap:6,overflowX:'auto',padding:'12px 0 4px'}},filterButtons),React.createElement('div',{'data-admin-historical-gallery':'true',style:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(138px,1fr))',gap:9,marginTop:8}},historicalCards),shownExtras.length===0&&React.createElement('div',{style:{padding:18,borderRadius:14,background:'var(--surface-2)',fontSize:12,fontWeight:750,color:'var(--ink-3)',textAlign:'center'}},'No hay elementos en este filtro.')));
    return React.createElement('div',{'data-admin-affiliate-documents':affiliateId,'data-admin-canonical-expediente':'supabase',style:{marginTop:16,paddingTop:16,borderTop:'1px solid var(--line)'}},
      React.createElement('div',{style:{display:'flex',justifyContent:'space-between',gap:12,alignItems:'baseline'}},React.createElement('div',{style:{fontSize:16,fontWeight:950,color:'var(--ink)'}},'Expediente digital'),React.createElement('div',{'data-admin-document-progress':verified+'/'+required.length,style:{fontSize:14,fontWeight:950,color:'var(--guinda)'}},verified+' / '+required.length)),
      React.createElement('div',{style:{fontSize:11.5,color:'var(--ink-3)',fontWeight:650,marginTop:4}},'El porcentaje usa exactamente los tipos marcados en Catálogo como “Cuenta para el 100%”.'),
      React.createElement(window.ProgressBar,{value:required.length?verified/required.length*100:0,height:8}),
      React.createElement('div',{'data-admin-document-gallery':'canonical',style:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginTop:14}},canonicalCards),historicalSection,
      React.createElement(DocumentInspector,{entry:preview,onClose:()=>setPreview(null),onNavigate:navigate,onReview:review,canReview:app.admin.has('documents.write')}));
  }
  window.IdentityAccessModule=IdentityAccessModule;
})();
