/* User Savings summary. Financial values come exclusively from the certified
   self-only reader; internal provenance never appears in the UI. */
(function () {
  'use strict';
  const h = React.createElement;
  const I = window.Icon;
  const PRIMARY_ACTIONS = [
    { code: 'WITHDRAW', label: 'Retirar ahorro', icon: 'cash', primary: true },
    { code: 'CHANGE_AMOUNT', label: 'Modificar monto', icon: 'edit', primary: false },
  ];
  const CSS = `
    .su-savings{--wine:#98143f;--wine-dark:#76102f;--pink:#f8edf1;--ink:#151519;--muted:#8b8b94;--line:#e8e8ec;--bg:#f3f3f5;position:absolute;inset:0;display:flex;flex-direction:column;background:var(--bg);color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow:hidden}.su-savings *{box-sizing:border-box}
    .sav-scroll{flex:1;min-height:0;overflow:auto;scrollbar-width:none}.sav-scroll::-webkit-scrollbar{display:none}.sav-hero{position:sticky;top:0;z-index:5;padding:calc(8px + env(safe-area-inset-top)) 16px 8px;background:#fff;border-bottom:1px solid var(--line)}.sav-head{display:flex;align-items:center;gap:8px;min-height:48px}.sav-back,.sav-info{height:40px;border:0;background:transparent;color:var(--wine);display:flex;align-items:center;justify-content:center;cursor:pointer}.sav-back{width:40px}.sav-info{width:38px}.sav-head-copy{flex:1;text-align:center}.sav-head-copy b{font-size:17px;font-weight:780}.sav-head-actions{display:flex}
    .sav-body{padding:16px 16px 34px}.sav-balance{background:linear-gradient(145deg,var(--wine),var(--wine-dark));color:#fff;border-radius:20px;padding:19px 18px;box-shadow:0 16px 28px -18px rgba(152,20,63,.9)}.sav-kicker{font-size:10.5px;font-weight:780;color:var(--muted);text-transform:uppercase;letter-spacing:.07em}.sav-balance .sav-kicker{color:#f0ccd8}.sav-total{font-size:34px;line-height:1.08;font-weight:820;letter-spacing:-.025em;margin-top:8px;font-variant-numeric:tabular-nums}.sav-split{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:18px}.sav-split>div{min-width:0;padding:10px 11px;border-radius:12px;background:rgba(255,255,255,.13)}.sav-split span{display:block;font-size:9.5px;font-weight:680;color:#ebc8d4}.sav-split b{display:block;font-size:16px;font-weight:800;margin-top:3px;font-variant-numeric:tabular-nums}.sav-split>div:last-child b{color:#59e59d}
    .sav-section{margin-top:18px}.sav-section-title{display:flex;align-items:flex-end;justify-content:space-between;gap:10px;margin:0 2px 10px}.sav-section-title b{font-size:11px;font-weight:780;color:#9999a1;letter-spacing:.075em;text-transform:uppercase}.sav-card,.sav-year{background:#fff;border:1px solid #e4e4e8;border-radius:18px;padding:15px 16px;box-shadow:0 5px 16px -13px rgba(0,0,0,.35)}.sav-year-list{display:flex;flex-direction:column;gap:12px}.sav-year-head{display:flex;justify-content:space-between;align-items:center}.sav-year-head b{font-size:18px;font-weight:800}.sav-year-head span{padding:5px 10px;border-radius:999px;background:#edf8f1;color:#157f4a;font-size:9px;font-weight:780}.sav-year-head span[data-current=true]{background:#fff1d5;color:#9a6813}.sav-year-grid{display:grid;grid-template-columns:1fr 1fr;margin-top:14px}.sav-year-grid>div{padding-right:12px}.sav-year-grid>div+div{padding-left:14px;padding-right:0;border-left:1px solid var(--line)}.sav-year-grid span{display:block;font-size:10px;font-weight:620;color:#9898a0}.sav-year-grid b{display:block;font-size:18px;font-weight:800;margin-top:3px;font-variant-numeric:tabular-nums}.sav-year-grid>div:last-child b{color:#008b50}.sav-year-subtotal{display:flex;justify-content:space-between;align-items:center;margin-top:14px;padding-top:12px;border-top:1px solid var(--line)}.sav-year-subtotal span{font-size:11px;color:var(--muted);font-weight:650}.sav-year-subtotal b{font-size:15px;font-weight:820;font-variant-numeric:tabular-nums}
    .sav-actions{display:grid;grid-template-columns:1.15fr .85fr;gap:9px;margin-top:16px}.sav-action{min-height:48px;border:1px solid #dedee3;border-radius:14px;padding:11px 10px;background:#fff;color:#56565d;font:730 12px inherit;display:flex;align-items:center;justify-content:center;gap:7px;cursor:pointer}.sav-action:disabled{opacity:.58;cursor:not-allowed}.sav-action[data-primary=true]{background:var(--wine);border-color:var(--wine);color:#fff}.sav-action>span{display:grid;place-items:center}.sav-note{margin:9px 3px 0;color:#85858d;font-size:10px;font-weight:650;text-align:center}
    .sav-enroll-head{display:flex;gap:11px;align-items:center}.sav-icon{width:39px;height:39px;border-radius:12px;display:grid;place-items:center;background:var(--pink);color:var(--wine);flex-shrink:0}.sav-enroll-head>div{flex:1}.sav-enroll-head b{display:block;font-size:14px;font-weight:850}.sav-enroll-head span{font-size:11px;font-weight:680;color:var(--muted)}.sav-human-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px 18px;margin-top:13px;padding-top:12px;border-top:1px solid var(--line)}.sav-human-grid span{display:block;font-size:9.5px;color:var(--muted);font-weight:650}.sav-human-grid b{display:block;margin-top:3px;font-size:12px;font-weight:790}
    .sav-detail-nav{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.sav-detail-link{border:1px solid #e2e2e7;border-radius:15px;background:#fff;min-height:76px;padding:11px 6px;color:var(--ink);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;font:730 10.5px inherit;cursor:pointer}.sav-detail-link>span{width:28px;height:28px;border-radius:9px;display:grid;place-items:center;background:var(--pink);color:var(--wine)}.sav-detail-link small{font-size:9px;color:var(--muted);font-weight:650}
    .sav-row{display:flex;justify-content:space-between;gap:14px;padding:10px 0;border-top:1px solid var(--line);font-size:11.5px}.sav-row:first-child{border-top:0}.sav-row span{color:var(--muted);font-weight:680}.sav-row b{text-align:right;font-weight:800;overflow-wrap:anywhere}.sav-tx{display:grid;grid-template-columns:36px 1fr auto;gap:10px;align-items:center;padding:11px 0;border-top:1px solid var(--line)}.sav-tx:first-child{border-top:0}.sav-tx-icon{width:35px;height:35px;border-radius:11px;background:#edf8f3;color:#087a50;display:grid;place-items:center}.sav-tx-icon[data-debit=true]{background:var(--pink);color:var(--wine)}.sav-tx b{display:block;font-size:12px}.sav-tx span{font-size:10px;color:var(--muted);font-weight:680}.sav-tx strong{font-size:12.5px;color:#087a50}.sav-tx strong[data-debit=true]{color:var(--wine)}
    .sav-error{margin:20px 16px;padding:16px;border-radius:17px;background:#fff;color:#9a1834;font-size:12px;font-weight:730}.sav-retry,.sav-primary{border:0;border-radius:14px;padding:12px 15px;background:var(--wine);color:#fff;font:750 13px inherit;cursor:pointer}.sav-primary{width:100%;min-height:48px}.sav-primary:disabled{opacity:.5;cursor:default}.sav-empty{padding:28px 18px;text-align:center;background:#fff;color:var(--ink);border:1px solid #e4e4e8;box-shadow:none}.sav-empty .sav-icon{margin:0 auto}.sav-empty h2{font-size:19px;margin:13px 0 5px}.sav-empty p,.sav-empty-copy{font-size:12px;line-height:1.5;color:var(--muted)}
    .sav-overlay{position:fixed;inset:0;z-index:92;background:rgba(14,18,28,.52);display:flex;align-items:flex-end;justify-content:center}.sav-sheet{width:min(100%,520px);max-height:86vh;overflow:auto;background:#fff;border-radius:25px 25px 0 0;padding:9px 18px calc(22px + env(safe-area-inset-bottom));box-shadow:0 -20px 50px rgba(0,0,0,.18)}.sav-handle{width:42px;height:4px;background:#d7dce5;border-radius:999px;margin:2px auto 15px}.sav-sheet-head{display:flex;align-items:center;justify-content:space-between;gap:10px;position:sticky;top:-9px;background:#fff;padding:9px 0;z-index:1}.sav-sheet h2{font-size:20px;margin:0}.sav-sheet p{font-size:12px;color:var(--muted);font-weight:650;line-height:1.5}.sav-sheet-list{margin-top:10px}.sav-close{width:38px;height:38px;border:0;border-radius:12px;background:#f0f2f6;display:grid;place-items:center;color:var(--ink);cursor:pointer}
    @media(min-width:700px){.sav-body,.sav-head{width:min(430px,100%);margin-left:auto;margin-right:auto}.sav-hero{padding-left:max(16px,calc((100% - 430px)/2));padding-right:max(16px,calc((100% - 430px)/2))}}@media(max-width:390px){.sav-body{padding-left:13px;padding-right:13px}.sav-total{font-size:31px}.sav-action{font-size:11.5px}}
  `;
  function icon(name, size) { return h(I, { name, size: size || 18, stroke: 2, 'aria-hidden': 'true' }); }
  function money(value) { return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', minimumFractionDigits: 2 }).format(Number(value || 0)); }
  function moneyOrDash(value) { return value == null ? '—' : money(value); }
  function shortDate(value) { return value ? new Date(value + (String(value).length === 10 ? 'T12:00:00' : '')).toLocaleDateString('es-MX', { day: '2-digit', month: 'short', year: 'numeric' }) : 'Por confirmar'; }
  function frequency(value) { return value === 'MONTHLY' ? 'Mensual' : value === 'TWICE_MONTHLY' ? 'Quincenal' : 'Por confirmar'; }
  function Sheet({ title, children, onClose, code }) { return h('div', { className: 'sav-overlay', onMouseDown: (event) => { if (event.target === event.currentTarget) onClose(); }, role: 'presentation' }, h('section', { className: 'sav-sheet', role: 'dialog', 'aria-modal': 'true', 'aria-label': title, 'data-savings-sheet': code }, h('div', { className: 'sav-handle' }), h('div', { className: 'sav-sheet-head' }, h('h2', null, title), h('button', { type: 'button', className: 'sav-close', onClick: onClose, 'aria-label': 'Cerrar' }, icon('close', 18))), children)); }

  function SavingsScreen({ app }) {
    const store = window.useSavingsStore('self'), state = store.state(), dashboard = state.self;
    const [sheet, setSheet] = React.useState('');
    const reload = () => store.loadSelf(true);
    if (state.selfPhase === 'loading' || state.selfPhase === 'idle') return h('div', { className: 'su-savings', 'data-savings-screen': '', 'data-savings-phase': 'loading' }, h('style', null, CSS), h('div', { className: 'sav-error' }, 'Cargando tu ahorro…'));
    if (state.selfPhase === 'error' || !dashboard) return h('div', { className: 'su-savings', 'data-savings-screen': '', 'data-savings-phase': 'error' }, h('style', null, CSS), h('header', { className: 'sav-hero' }, h('div', { className: 'sav-head' }, h('button', { className: 'sav-back', onClick: app.back, 'aria-label': 'Atrás' }, icon('arrowL', 20)), h('div', { className: 'sav-head-copy' }, h('b', null, 'Ahorro')), h('span', { className: 'sav-info' }))), h('div', { className: 'sav-error', role: 'alert' }, 'No fue posible consultar tu ahorro.', h('div', { style: { marginTop: 12 } }, h('button', { className: 'sav-retry', onClick: reload }, 'Reintentar'))));
    const participant = dashboard.participant, enrollment = dashboard.enrollment, balance = dashboard.balances, years = dashboard.annual || [];
    const history = dashboard.history || [], withdrawals = dashboard.withdrawals || [], beneficiaries = dashboard.beneficiaries || [];
    const canWriteRequests = Boolean(dashboard.write_capabilities && dashboard.write_capabilities.requests);
    const detailRow = (label, value) => h('div', { className: 'sav-row', key: label }, h('span', null, label), h('b', null, value == null || value === '' ? 'Por confirmar' : value));
    const section = (title, content) => h('section', { className: 'sav-section' }, h('div', { className: 'sav-section-title' }, h('b', null, title)), content);
    const transaction = (item, debit) => h('div', { className: 'sav-tx', key: item.id || item.effective_date + '-' + item.amount }, h('span', { className: 'sav-tx-icon', 'data-debit': debit }, icon(debit ? 'cash' : 'check', 16)), h('div', null, h('b', null, debit ? (item.withdrawal_kind || 'Retiro') : 'Aportación'), h('span', null, shortDate(item.effective_date) + (debit && item.status ? ' · ' + item.status : ''))), h('strong', { 'data-debit': debit }, (debit ? '−' : '+') + money(item.amount)));
    const detailNav = [['HISTORY', 'Historial', history.length + ' movimientos', 'clock'], ['WITHDRAWALS', 'Retiros', withdrawals.length + ' registros', 'cash'], ['BENEFICIARIES', 'Beneficiarios', beneficiaries.length + ' registrados', 'users']];
    return h('div', { className: 'su-savings', 'data-savings-screen': '', 'data-savings-authority': dashboard.authority, 'data-savings-projection': dashboard.projection, 'data-savings-cutover': dashboard.cutover_status }, h('style', null, CSS), h('div', { className: 'sav-scroll' },
      h('header', { className: 'sav-hero' }, h('div', { className: 'sav-head' }, h('button', { type: 'button', className: 'sav-back', onClick: app.back, 'aria-label': 'Atrás' }, icon('arrowL', 20)), h('div', { className: 'sav-head-copy' }, h('b', null, 'Ahorro')), h('div', { className: 'sav-head-actions' }, h('button', { type: 'button', className: 'sav-info', onClick: reload, 'aria-label': 'Actualizar ahorro', 'data-savings-refresh': '' }, icon('refresh', 17)), h('button', { type: 'button', className: 'sav-info', onClick: () => setSheet('INFO'), 'aria-label': 'Información' }, icon('info', 17))))),
      h('main', { className: 'sav-body' }, participant ? h(React.Fragment, null,
        h('section', { className: 'sav-balance', 'aria-label': 'Resumen de ahorro' }, h('div', { className: 'sav-kicker' }, 'Saldo actual'), h('div', { className: 'sav-total', 'data-savings-total': balance && balance.total != null ? String(balance.total) : '' }, balance && balance.total != null ? money(balance.total) : 'Por confirmar'), h('div', { className: 'sav-split' }, h('div', null, h('span', null, 'AHORRO'), h('b', { 'data-savings-capital': balance && balance.capital != null ? String(balance.capital) : '' }, balance ? moneyOrDash(balance.capital) : '—')), h('div', null, h('span', null, 'RENDIMIENTO'), h('b', { 'data-savings-yield': balance && balance.yield != null ? String(balance.yield) : '' }, balance ? moneyOrDash(balance.yield) : '—')))),
        section('Detalle por año', years.length ? h('div', { className: 'sav-year-list' }, years.map((item, index) => { const subtotal = item.capital == null && item.yield == null ? null : Number(item.capital || 0) + Number(item.yield || 0); const current = Number(String(item.year).slice(0, 4)) === new Date().getFullYear(); return h('article', { className: 'sav-year', key: item.year + '-' + index, 'data-savings-year': item.year }, h('div', { className: 'sav-year-head' }, h('b', null, item.year), h('span', { 'data-current': current }, current ? 'PERIODO CERRADO' : 'DISPONIBLE')), h('div', { className: 'sav-year-grid' }, h('div', null, h('span', null, 'Ahorro'), h('b', { 'data-savings-year-capital': item.capital == null ? '' : String(item.capital) }, moneyOrDash(item.capital))), h('div', null, h('span', null, 'Rendimiento'), h('b', { 'data-savings-year-yield': item.yield == null ? '' : String(item.yield) }, moneyOrDash(item.yield)))), h('div', { className: 'sav-year-subtotal' }, h('span', null, 'Subtotal a Junio ' + item.year), h('b', { 'data-savings-year-subtotal': subtotal == null ? '' : String(subtotal) }, moneyOrDash(subtotal)))); })) : h('div', { className: 'sav-card sav-empty-copy' }, 'Aún no hay detalle anual disponible.')),
        h('div', { className: 'sav-actions', 'data-savings-actions': '' }, PRIMARY_ACTIONS.map((action) => { const enabled = Boolean(dashboard.actions && dashboard.actions[action.code] && canWriteRequests); return h('button', { type: 'button', key: action.code, className: 'sav-action', 'data-primary': action.primary, disabled: !enabled, 'aria-disabled': String(!enabled), 'data-savings-action': action.code, 'data-savings-enabled': String(enabled) }, h('span', null, icon(action.icon, 17)), action.label); })),
        h('div', { className: 'sav-note' }, 'Estas opciones aún no están disponibles para tu cuenta.'),
        section('Tu ahorro', h('div', { className: 'sav-card', 'data-savings-enrollment': '' }, enrollment ? h(React.Fragment, null, h('div', { className: 'sav-enroll-head' }, h('span', { className: 'sav-icon' }, icon('calendar', 19)), h('div', null, h('b', null, enrollment.status || 'Estado por confirmar'), h('span', null, 'Tu plan de ahorro'))), h('div', { className: 'sav-human-grid' }, h('div', null, h('span', null, 'Aportación'), h('b', null, enrollment.current_contribution_amount == null ? 'Por confirmar' : money(enrollment.current_contribution_amount))), h('div', null, h('span', null, 'Frecuencia'), h('b', null, frequency(enrollment.frequency))), h('div', null, h('span', null, 'Desde'), h('b', null, shortDate(enrollment.enrollment_started_at))), h('div', null, h('span', null, 'Estado'), h('b', null, enrollment.status || 'Por confirmar')))) : h('span', { className: 'sav-empty-copy' }, 'Aún no hay información de tu plan.'))),
        section('Más detalles', h('nav', { className: 'sav-detail-nav', 'aria-label': 'Detalles de ahorro' }, detailNav.map(([code, label, count, iconName]) => h('button', { type: 'button', className: 'sav-detail-link', key: code, onClick: () => setSheet(code), 'data-savings-detail': code.toLowerCase() }, h('span', null, icon(iconName, 16)), label, h('small', null, count)))))
      ) : h('section', { className: 'sav-balance sav-empty', 'data-savings-empty': '' }, h('span', { className: 'sav-icon' }, icon('cash', 22)), h('h2', null, 'Ahorro no encontrado'), h('p', null, 'No encontramos una cuenta de ahorro vinculada a tu perfil.'), h('button', { type: 'button', className: 'sav-primary', disabled: true }, 'Ingresar al ahorro')))),
      sheet === 'INFO' && h(Sheet, { title: 'Acerca de tu ahorro', code: 'info', onClose: () => setSheet('') }, h('p', null, 'El saldo actual muestra el monto disponible de tu ahorro. El detalle por año resume el ahorro y rendimiento registrados en cada periodo.')),
      sheet === 'HISTORY' && h(Sheet, { title: 'Historial', code: 'history', onClose: () => setSheet('') }, h('div', { className: 'sav-sheet-list', 'data-savings-history': '' }, history.length ? history.map((item) => transaction(item, false)) : h('p', null, 'Aún no hay movimientos para mostrar.'))),
      sheet === 'WITHDRAWALS' && h(Sheet, { title: 'Retiros', code: 'withdrawals', onClose: () => setSheet('') }, h('div', { className: 'sav-sheet-list', 'data-savings-withdrawals': '' }, withdrawals.length ? withdrawals.map((item) => transaction(item, true)) : h('p', null, 'No hay retiros registrados.'))),
      sheet === 'BENEFICIARIES' && h(Sheet, { title: 'Beneficiarios', code: 'beneficiaries', onClose: () => setSheet('') }, h('div', { className: 'sav-sheet-list', 'data-savings-beneficiaries': '' }, beneficiaries.length ? beneficiaries.map((item) => detailRow(item.full_name, (item.relationship || 'Parentesco por confirmar') + ' · ' + Number(item.percentage || 0).toFixed(2) + '%')) : h('p', null, 'No hay beneficiarios registrados.'))));
  }
  window.SavingsScreen = SavingsScreen;
})();
