/* Central Admin for document catalog, review, terms and QR policy. */
(function(){
  'use strict';
  const I=window.Icon;
  const h=React.createElement;
  const DESKTOP_QUERY='(min-width: 1024px)';
  const DOC_STATES=Object.freeze({
    PENDING_REVIEW:{label:'Pendiente',tone:'#9A6200',background:'#FFF3D8'},
    UNDER_REVIEW:{label:'En revisión',tone:'#755300',background:'#FFF0C2'},
    VERIFIED:{label:'Verificado',tone:'#087A50',background:'#E5F7EF'},
    REUPLOAD_REQUIRED:{label:'Requiere nueva carga',tone:'#A00027',background:'#FCE9EE'},
    REJECTED:{label:'Rechazado',tone:'#A00027',background:'#FCE9EE'}
  });
  const SEEDED_LABELS=Object.freeze({
    'Hoja de Afiliación':'Hoja de Afiliación',
    'INE FRENTE':'INE Frente',
    'INE REVERSO':'INE Reverso',
    'Hoja Tribunal':'Hoja Tribunal',
    'TALON ULTIMA QUINCENA':'Talón Última Quincena',
    'TALON PENULTIMA QUINCENA':'Talón Penúltima Quincena',
    'Photo':'Foto de perfil',
    'Credencial Afiliado':'Credencial del afiliado'
  });
  const input={width:'100%',border:'none',background:'var(--surface-2)',boxShadow:'var(--neo-inset)',borderRadius:12,padding:'11px 12px',font:'600 13px var(--font)',boxSizing:'border-box',color:'var(--ink)'};
  const panel={background:'#fff',border:'1px solid rgba(99,96,110,.12)',borderRadius:18,boxShadow:'0 10px 28px rgba(31,35,48,.07)',minWidth:0};

  function useDocumentDesktop(){
    const[desktop,setDesktop]=React.useState(()=>Boolean(window.matchMedia&&window.matchMedia(DESKTOP_QUERY).matches));
    React.useEffect(()=>{if(!window.matchMedia)return;const media=window.matchMedia(DESKTOP_QUERY),change=()=>setDesktop(media.matches);change();media.addEventListener?media.addEventListener('change',change):media.addListener(change);return()=>media.removeEventListener?media.removeEventListener('change',change):media.removeListener(change);},[]);
    return desktop;
  }
  function stateInfo(value){return DOC_STATES[value]||{label:'Estado no disponible',tone:'#60606A',background:'#EFEFF2'};}
  function businessLabel(type){const label=String(type&&type.label||'Documento');return SEEDED_LABELS[label]||label;}
  function affiliateReference(row){const raw=String(row&&row.affiliate_id||'').replace(/[^a-z0-9]/gi,'');return raw?raw.slice(-6).toUpperCase():'SIN-REF';}
  function affiliateName(row){const a=row&&row.affiliate||{};return a.display_name||a.full_name||('Afiliado · referencia '+affiliateReference(row));}
  function maskedControl(row){const raw=String(row&&row.affiliate&&row.affiliate.numero_control||'').trim();return raw?('Control ·••••'+raw.slice(-4)):('Referencia de expediente · '+affiliateReference(row));}
  function formatDate(value){if(!value)return 'Sin fecha';try{return new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}catch(_){return 'Sin fecha';}}
  function pendingAge(value){if(!value)return 'Antigüedad no disponible';const days=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000));if(days===0)return 'Recibido hoy';if(days===1)return 'Pendiente desde ayer';return 'Pendiente hace '+days+' días';}
  function mimeLabel(value){const mime=String(value||'');if(mime==='application/pdf')return 'PDF';if(mime.startsWith('image/'))return 'Imagen '+mime.split('/')[1].toUpperCase();return mime||'Formato no informado';}
  function StatusBadge({status}){const info=stateInfo(status);return h('span',{'data-document-human-status':info.label,style:{display:'inline-flex',alignItems:'center',gap:6,borderRadius:999,padding:'5px 9px',fontSize:11,fontWeight:850,color:info.tone,background:info.background,whiteSpace:'nowrap'}},h('span',{'aria-hidden':'true',style:{width:7,height:7,borderRadius:'50%',background:info.tone}}),info.label);}

  function DesktopPreview({row,preview,phase,error,onRetry,position,total}){
    const current=preview&&preview.id===row.id?preview:row;
    const mime=String(current&&current.mimeType||'');
    let visual;
    if(phase==='loading')visual=h('div',{style:{display:'grid',placeItems:'center',height:'100%',color:'var(--ink-3)',fontWeight:800}},'Cargando documento…');
    else if(error)visual=h('div',{role:'alert',style:{display:'grid',placeItems:'center',alignContent:'center',gap:12,height:'100%',padding:24,textAlign:'center'}},h(I,{name:'warning',size:30}),h('b',null,'No fue posible cargar la vista previa'),h('button',{type:'button',onClick:onRetry,style:{border:0,borderRadius:11,padding:'10px 14px',fontWeight:850,color:'var(--guinda)',background:'var(--surface-2)'}},'Reintentar'));
    else if(current&&current.signedUrl&&mime.startsWith('image/'))visual=h('img',{src:current.signedUrl,alt:'Vista previa de '+businessLabel(current.document_type),style:{width:'100%',height:'100%',objectFit:'contain'}});
    else if(current&&current.signedUrl&&mime==='application/pdf')visual=h('iframe',{src:current.signedUrl,title:'Vista previa de '+businessLabel(current.document_type),style:{width:'100%',height:'100%',border:0,background:'#fff'}});
    else visual=h('div',{style:{display:'grid',placeItems:'center',alignContent:'center',gap:10,height:'100%',padding:24,textAlign:'center',color:'var(--ink-3)'}},h(I,{name:mime==='application/pdf'?'doc':'folder',size:42}),h('b',null,current&&current.previewUnavailable?'No se pudo autorizar la vista previa':'Vista previa no disponible para este formato'),current&&current.signedUrl&&h('a',{href:current.signedUrl,target:'_blank',rel:'noopener noreferrer',style:{color:'var(--guinda)',fontWeight:850}},'Abrir documento'));
    return h('section',{'data-document-preview-panel':'true',className:'docwb-preview',style:Object.assign({},panel,{display:'flex',flexDirection:'column',overflow:'hidden'})},
      h('div',{style:{padding:'15px 17px',borderBottom:'1px solid var(--hairline)',display:'flex',justifyContent:'space-between',gap:12,alignItems:'start'}},h('div',{style:{minWidth:0}},h('div',{style:{fontSize:11,fontWeight:850,color:'var(--ink-3)',textTransform:'uppercase',letterSpacing:'.05em'}},'Documento seleccionado'),h('h2',{style:{fontSize:17,margin:'4px 0 2px'}},businessLabel(row.document_type)),h('div',{style:{fontSize:12,color:'var(--ink-3)',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},affiliateName(row)+' · '+maskedControl(row))),h('b',{'data-document-queue-position':'true',style:{fontSize:11,color:'var(--guinda)',whiteSpace:'nowrap'}},position+' de '+total)),
      h('div',{'data-document-persistent-preview':'true',style:{height:'clamp(270px,44vh,520px)',background:'#E9E9ED',display:'grid',placeItems:'stretch',padding:10}},visual),
      h('div',{style:{padding:'13px 17px',display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10,borderTop:'1px solid var(--hairline)'}},
        h('div',null,h('span',{style:{fontSize:10.5,color:'var(--ink-3)',fontWeight:750}},'Recibido'),h('div',{style:{fontSize:12,fontWeight:800,marginTop:2}},formatDate(row.created_at))),
        h('div',null,h('span',{style:{fontSize:10.5,color:'var(--ink-3)',fontWeight:750}},'Formato'),h('div',{style:{fontSize:12,fontWeight:800,marginTop:2}},mimeLabel(current&&current.mimeType))),
        h('div',null,h('span',{style:{fontSize:10.5,color:'var(--ink-3)',fontWeight:750}},'Estado'),h('div',{style:{marginTop:4}},h(StatusBadge,{status:row.status}))),
        h('div',null,h('span',{style:{fontSize:10.5,color:'var(--ink-3)',fontWeight:750}},'Historial relevante'),h('div',{style:{fontSize:11.5,fontWeight:750,marginTop:2}},row.reviewed_at?'Última decisión · '+formatDate(row.reviewed_at):'Carga recibida · sin decisión')),
        row.review_observation&&h('div',{style:{gridColumn:'1 / -1',fontSize:11.5,color:'var(--ink-2)',background:'var(--surface-2)',borderRadius:10,padding:9}},h('b',null,'Observación anterior: '),row.review_observation),
        current&&current.signedUrl&&h('a',{href:current.signedUrl,target:'_blank',rel:'noopener noreferrer',style:{gridColumn:'1 / -1',textAlign:'center',color:'var(--guinda)',fontSize:11.5,fontWeight:850,textDecoration:'none'}},'Abrir original en otra pestaña')));
  }

  function DesktopReview(props){
    const{app,types,queue,visibleQueue,selectedId,setSelectedId,preview,previewPhase,previewError,retryPreview,reviewFilter,setReviewFilter,statusFilter,setStatusFilter,typeFilter,setTypeFilter,affiliateFilter,setAffiliateFilter,sort,setSort,rowFeedback,decision,setDecision,observation,setObservation,commitDecision,go,position}=props;
    const selected=visibleQueue.find((row)=>row.id===selectedId)||queue.find((row)=>row.id===selectedId)||null;
    const canReview=app.admin.has('documents.write');
    const affiliates=[];queue.forEach((row)=>{if(!affiliates.some((entry)=>entry.id===row.affiliate_id))affiliates.push({id:row.affiliate_id,label:affiliateName(row)});});affiliates.sort((a,b)=>a.label.localeCompare(b.label,'es'));
    const onKeys=(event)=>{if(['INPUT','TEXTAREA','SELECT','BUTTON','A'].includes(event.target.tagName))return;if(event.key==='ArrowDown'){event.preventDefault();go(1);}else if(event.key==='ArrowUp'){event.preventDefault();go(-1);}else if(event.key==='Enter'&&selected){event.preventDefault();setSelectedId(selected.id);}};
    return h('div',{'data-admin-document-workbench':'true',tabIndex:0,onKeyDown:onKeys,style:{outline:'none'}},
      h('style',null,'.docwb-filters{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-bottom:12px}.docwb-filters>:first-child{grid-column:1 / -1}.docwb-grid{display:grid;grid-template-columns:minmax(265px,.82fr) minmax(360px,1.35fr);grid-template-rows:minmax(330px,auto) auto;gap:14px;align-items:stretch}.docwb-queue{grid-column:1;grid-row:1 / span 2}.docwb-preview{grid-column:2;grid-row:1}.docwb-decision{grid-column:2;grid-row:2}.docwb-nav{grid-column:1 / -1}@media(min-width:1280px){.docwb-filters{grid-template-columns:minmax(220px,1fr) repeat(4,minmax(125px,.48fr))}.docwb-filters>:first-child{grid-column:auto}.docwb-grid{grid-template-columns:minmax(255px,.82fr) minmax(370px,1.35fr) minmax(260px,.82fr);grid-template-rows:minmax(520px,1fr) auto}.docwb-queue{grid-column:1;grid-row:1}.docwb-preview{grid-column:2;grid-row:1}.docwb-decision{grid-column:3;grid-row:1}.docwb-nav{grid-column:1 / -1;grid-row:2}}'),
      h('div',{className:'docwb-filters','data-document-queue-filters':'true'},
        h('input',{value:reviewFilter,onChange:(event)=>setReviewFilter(event.target.value),placeholder:'Buscar afiliado o documento',style:input,'aria-label':'Buscar en la cola documental'}),
        h('select',{value:statusFilter,onChange:(event)=>setStatusFilter(event.target.value),style:input,'aria-label':'Filtrar por estado'},h('option',{value:''},'Todos los estados'),Object.keys(DOC_STATES).map((value)=>h('option',{key:value,value},DOC_STATES[value].label))),
        h('select',{value:typeFilter,onChange:(event)=>setTypeFilter(event.target.value),style:input,'aria-label':'Filtrar por documento'},h('option',{value:''},'Todos los documentos'),types.map((type)=>h('option',{key:type.id,value:type.id},businessLabel(type)))),
        h('select',{value:affiliateFilter,onChange:(event)=>setAffiliateFilter(event.target.value),style:input,'aria-label':'Filtrar por afiliado'},h('option',{value:''},'Todos los afiliados'),affiliates.map((entry)=>h('option',{key:entry.id,value:entry.id},entry.label))),
        h('select',{value:sort,onChange:(event)=>setSort(event.target.value),style:input,'aria-label':'Ordenar cola'},h('option',{value:'oldest'},'Más antiguos primero'),h('option',{value:'newest'},'Más recientes primero'),h('option',{value:'affiliate'},'Afiliado A–Z'),h('option',{value:'document'},'Documento A–Z'))),
      h('div',{className:'docwb-grid'},
        h('section',{'data-document-review-queue':'true',className:'docwb-queue',style:Object.assign({},panel,{display:'flex',flexDirection:'column',overflow:'hidden'})},
          h('div',{style:{padding:'14px 15px',borderBottom:'1px solid var(--hairline)',display:'flex',justifyContent:'space-between',alignItems:'center'}},h('div',null,h('b',{style:{fontSize:14}},'Cola documental'),h('div',{style:{fontSize:10.5,color:'var(--ink-3)',marginTop:2}},'↑/↓ navega · Enter activa')),h('span',{style:{fontSize:11,fontWeight:850,color:'var(--guinda)'}},visibleQueue.length+' casos')),
          h('div',{style:{overflowY:'auto',minHeight:300,maxHeight:'calc(100vh - 285px)',padding:8}},visibleQueue.length?visibleQueue.map((row)=>{const active=row.id===selectedId,info=stateInfo(row.status),feedback=rowFeedback[row.id];return h('button',{key:row.id,type:'button','data-document-queue-item':row.id,'aria-current':active?'true':undefined,onClick:()=>setSelectedId(row.id),style:{display:'block',width:'100%',border:active?'2px solid var(--guinda)':'1px solid transparent',borderRadius:13,padding:11,marginBottom:7,textAlign:'left',background:active?'#FFF7F9':'#F7F7F9',fontFamily:'inherit',cursor:'pointer',boxShadow:active?'0 6px 16px rgba(128,0,38,.1)':'none'}},h('div',{style:{display:'flex',gap:9,alignItems:'start'}},h('span',{'aria-hidden':'true',style:{width:32,height:32,borderRadius:10,background:'#fff',display:'grid',placeItems:'center',color:'var(--guinda)',flex:'0 0 auto'}},h(I,{name:row.document_type&&row.document_type.icon||'doc',size:17})),h('span',{style:{minWidth:0,flex:1}},h('b',{style:{display:'block',fontSize:12.5,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},affiliateName(row)),h('span',{style:{display:'block',fontSize:11,color:'var(--ink-3)',marginTop:2,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},businessLabel(row.document_type)),h('span',{style:{display:'block',fontSize:10.5,color:'var(--ink-3)',marginTop:4}},pendingAge(row.created_at))),h('span',{style:{width:8,height:8,borderRadius:'50%',background:info.tone,marginTop:5,flex:'0 0 auto'},title:info.label})),feedback&&h('span',{'data-document-inline-feedback':feedback.tone,style:{display:'block',fontSize:10.5,fontWeight:850,color:feedback.tone==='error'?'#A00027':'#087A50',marginTop:7}},feedback.text));}):h('div',{style:{padding:25,textAlign:'center'}},h('b',null,'Sin resultados'),h('p',{style:{fontSize:12,color:'var(--ink-3)'}},reviewFilter||statusFilter||typeFilter||affiliateFilter?'Ajusta los filtros para ver otros documentos.':'No hay documentos pendientes de revisión.')))),
        selected?h(DesktopPreview,{row:selected,preview,phase:previewPhase,error:previewError,onRetry:retryPreview,position,total:visibleQueue.length}):h('section',{className:'docwb-preview',style:Object.assign({},panel,{display:'grid',placeItems:'center',padding:30})},'Selecciona un documento de la cola.'),
        selected?h('aside',{'data-document-decision-panel':'true',className:'docwb-decision',style:Object.assign({},panel,{padding:16,display:'flex',flexDirection:'column',gap:12})},
          h('div',null,h('div',{style:{fontSize:10.5,color:'var(--ink-3)',fontWeight:850,textTransform:'uppercase'}},'Decisión'),h('h2',{style:{fontSize:16,margin:'4px 0'}},affiliateName(selected)),h('div',{style:{fontSize:11.5,color:'var(--ink-3)'}},businessLabel(selected.document_type)+' · '+position+' de '+visibleQueue.length)),
          h('div',{style:{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderTop:'1px solid var(--hairline)',borderBottom:'1px solid var(--hairline)'}},h('span',{style:{fontSize:11,fontWeight:800}},'Estado actual'),h(StatusBadge,{status:selected.status})),
          canReview?h(React.Fragment,null,
            h('div',{role:'group','aria-label':'Decisión documental',style:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}},h('button',{type:'button','aria-pressed':decision==='VERIFIED',onClick:()=>setDecision('VERIFIED'),style:{border:decision==='VERIFIED'?'2px solid #087A50':'1px solid var(--hairline)',borderRadius:12,padding:'11px 8px',background:'#E5F7EF',color:'#087A50',fontWeight:850}},'Aprobar'),h('button',{type:'button','aria-pressed':decision==='REUPLOAD_REQUIRED',onClick:()=>setDecision('REUPLOAD_REQUIRED'),style:{border:decision==='REUPLOAD_REQUIRED'?'2px solid #A00027':'1px solid var(--hairline)',borderRadius:12,padding:'11px 8px',background:'#FCE9EE',color:'#A00027',fontWeight:850}},'Pedir nueva carga')),
            h('label',{style:{fontSize:11.5,fontWeight:800}},'Observación para el afiliado',h('textarea',{value:observation,onChange:(event)=>setObservation(event.target.value),rows:5,maxLength:1000,placeholder:decision==='REUPLOAD_REQUIRED'?'Explica qué debe corregir…':'Opcional al aprobar',style:Object.assign({},input,{marginTop:6,resize:'vertical'})})),
            rowFeedback[selected.id]&&h('div',{role:rowFeedback[selected.id].tone==='error'?'alert':'status','data-document-decision-feedback':rowFeedback[selected.id].tone,style:{borderRadius:11,padding:10,fontSize:11.5,fontWeight:850,color:rowFeedback[selected.id].tone==='error'?'#A00027':'#087A50',background:rowFeedback[selected.id].tone==='error'?'#FCE9EE':'#E5F7EF'}},rowFeedback[selected.id].text),
            h('button',{type:'button',disabled:!decision||(decision==='REUPLOAD_REQUIRED'&&!observation.trim())||props.saving,onClick:()=>commitDecision(false),style:{border:0,borderRadius:12,padding:11,background:'var(--surface-2)',color:'var(--guinda)',fontWeight:850,opacity:!decision?.55:1}},props.saving?'Guardando…':'Guardar decisión'))
          :h('div',{'data-document-review-denied':'true',style:{background:'var(--surface-2)',borderRadius:12,padding:12,fontSize:12,color:'var(--ink-3)'}},h('b',{style:{display:'block',color:'var(--ink)'}},'Consulta solamente'),'La capacidad Documentos · Editar es necesaria para decidir.'),
          h('div',{style:{marginTop:'auto',fontSize:10.5,color:'var(--ink-3)'}},'La autorización se valida nuevamente en backend/RLS.')):null,
        h('div',{'data-document-queue-navigator':'true',className:'docwb-nav',style:Object.assign({},panel,{display:'grid',gridTemplateColumns:'1fr auto 1fr',alignItems:'center',padding:'11px 14px'})},h('button',{type:'button',disabled:position<=1,onClick:()=>go(-1),style:{justifySelf:'start',border:0,borderRadius:10,padding:'9px 13px',fontWeight:850,background:'var(--surface-2)',color:'var(--ink)',opacity:position<=1?.45:1}},'Anterior'),h('b',{style:{fontSize:12,color:'var(--ink-2)'}},selected?position+' de '+visibleQueue.length:'0 de '+visibleQueue.length),h('button',{type:'button',disabled:!selected||!canReview||!decision||(decision==='REUPLOAD_REQUIRED'&&!observation.trim())||props.saving,onClick:()=>commitDecision(true),style:{justifySelf:'end',border:0,borderRadius:11,padding:'10px 15px',fontWeight:850,background:'var(--guinda)',color:'#fff',opacity:!selected||!decision?.5:1}},props.saving?'Guardando…':'Guardar y siguiente'))));
  }

  function DesktopCatalog({types,setTypes,busy,dragId,setDragId,reorderType,load,app}){
    const canWrite=app.admin.has('documents.write');
    return h('div',{'data-document-catalog-desktop':'true',style:{display:'flex',flexDirection:'column',gap:10}},
      h('div',{style:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}},h('div',null,h('h2',{style:{fontSize:17,margin:0}},'Catálogo documental'),h('p',{style:{fontSize:11.5,color:'var(--ink-3)',margin:'4px 0 0'}},'El nombre de negocio es principal; el código interno permanece en detalles.')),h(window.Btn,{icon:'plus',disabled:!canWrite,onClick:async()=>{const label=prompt('Nombre del tipo de documento:');if(!label)return;const code=prompt('Código técnico (minúsculas y guiones bajos):');if(!code)return;try{await window.DocumentWorkflowRepository.saveType({code,label,description:'',icon:'doc',required_by_default:false,accepted_mime_types:['image/jpeg','image/png','image/webp','application/pdf'],enabled:true,sort_order:types.length+1,system_type:false});await load();}catch(_){app.toast&&app.toast('No se pudo crear el tipo');}}},'Nuevo tipo documental')),
      h('div',{style:{display:'grid',gap:8}},types.map((type)=>h('article',{key:type.id,'data-document-type-row':type.id,draggable:canWrite&&busy!=='order',onDragStart:()=>setDragId(type.id),onDragOver:(event)=>event.preventDefault(),onDrop:()=>reorderType(type.id),style:Object.assign({},panel,{display:'grid',gridTemplateColumns:'38px minmax(220px,1fr) minmax(190px,.8fr) 126px 82px 38px',alignItems:'center',gap:12,padding:'12px 14px',cursor:canWrite?'grab':'default'})},
        h('span',{'aria-label':'Arrastrar para reordenar',style:{width:34,height:34,borderRadius:10,display:'grid',placeItems:'center',background:'var(--surface-2)',color:'var(--ink-3)'}},h(I,{name:'menu',size:18})),
        h('div',{style:{minWidth:0}},h('b',{'data-document-business-label':'true',style:{display:'block',fontSize:14,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},businessLabel(type)),type.description&&h('span',{style:{display:'block',fontSize:10.5,color:'var(--ink-3)',marginTop:3,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}},type.description),h('details',{style:{marginTop:5}},h('summary',{style:{fontSize:10.5,color:'var(--guinda)',fontWeight:800,cursor:'pointer'}},'Editar nombre y detalles técnicos'),h('label',{style:{display:'block',fontSize:10.5,fontWeight:750,marginTop:7}},'Nombre visible',h('input',{value:type.label,disabled:!canWrite,onChange:(event)=>setTypes((all)=>all.map((item)=>item.id===type.id?Object.assign({},item,{label:event.target.value}):item)),onBlur:async(event)=>{if(!canWrite)return;await window.DocumentWorkflowRepository.saveType(Object.assign({},type,{label:event.target.value.trim()}));await load();},style:Object.assign({},input,{marginTop:4,padding:8})})),h('div',{'data-document-technical-code':'secondary',style:{fontSize:10,color:'var(--ink-3)',marginTop:6}},'Código interno: ',h('code',null,type.code)))),
        h('label',{style:{fontSize:11,fontWeight:800,color:type.required_by_default?'var(--guinda)':'var(--ink-3)'}},h('span',{style:{display:'flex',alignItems:'center',gap:7}},h('input',{'data-global-required':type.code,type:'checkbox',disabled:!canWrite,checked:!!type.required_by_default,onChange:async(event)=>{await window.DocumentWorkflowRepository.saveType(Object.assign({},type,{required_by_default:event.target.checked}));await load();}}),'Cuenta para el 100% del expediente'),h('span',{'data-owner-clarification-required':'required_by_default',style:{display:'block',fontSize:9.5,fontWeight:650,lineHeight:1.35,color:'var(--ink-3)',marginTop:4}},'Incluye este tipo en el cálculo global de completitud. Nombre de negocio pendiente de definición.')),
        h('label',{style:{fontSize:10.5,fontWeight:800,color:'var(--ink-3)'}},'Posición',h('input',{type:'number',min:1,value:type.sort_order,disabled:!canWrite,'aria-label':'Posición de '+businessLabel(type),onChange:(event)=>setTypes((all)=>all.map((item)=>item.id===type.id?Object.assign({},item,{sort_order:event.target.value}):item)),onBlur:async(event)=>{if(!canWrite)return;await window.DocumentWorkflowRepository.saveType(Object.assign({},type,{sort_order:Number(event.target.value)}));await load();},style:Object.assign({},input,{marginTop:4,padding:8})})),
        h('div',{style:{textAlign:'center'}},h('span',{style:{display:'block',fontSize:9.5,fontWeight:800,color:'var(--ink-3)',marginBottom:5}},type.enabled?'Activo':'Inactivo'),h(window.Toggle,{on:type.enabled,onClick:canWrite?async()=>{await window.DocumentWorkflowRepository.saveType(Object.assign({},type,{enabled:!type.enabled}));await load();}:undefined})),
        !type.system_type?h('button',{type:'button',disabled:!canWrite,'aria-label':'Eliminar '+businessLabel(type),onClick:async()=>{if(confirm('¿Eliminar este tipo sin uso?'))try{await window.DocumentWorkflowRepository.removeType(type.id);await load();}catch(_){app.toast&&app.toast('No puede eliminarse porque ya está relacionado. Desactívalo.');}},style:{border:'none',background:'#FCE9EE',color:'#A00027',borderRadius:9,width:32,height:32,opacity:canWrite?1:.45}},h(I,{name:'trash',size:15})):h('span',null)))));
  }

  function RequirementsPanel({types,reqTarget,setReqTarget,reqRows,loadRequirements,app}){
    const canWrite=app.admin.has('documents.write');
    return h('div',{'data-document-requirements-desktop':'true',style:{display:'grid',gridTemplateColumns:'minmax(240px,.6fr) minmax(420px,1.4fr)',gap:14}},
      h('section',{style:Object.assign({},panel,{padding:16})},h('div',{style:{fontSize:10.5,fontWeight:850,color:'var(--ink-3)',textTransform:'uppercase'}},'Regla por programa o trámite'),h('h2',{style:{fontSize:17,margin:'5px 0 12px'}},'Contexto del requisito'),h('label',{style:{fontSize:11,fontWeight:800}},'Programa',h('select',{value:reqTarget.program_id,onChange:(event)=>setReqTarget({program_id:event.target.value,membership_offering_id:''}),style:Object.assign({},input,{marginTop:6})},h('option',{value:'prestamo'},'Suti Préstamo'),h('option',{value:'membership'},'Membresía'))),reqTarget.program_id==='membership'&&h('label',{style:{display:'block',fontSize:11,fontWeight:800,marginTop:11}},'Membresía',h('select',{value:reqTarget.membership_offering_id,onChange:(event)=>setReqTarget((value)=>Object.assign({},value,{membership_offering_id:event.target.value})),style:Object.assign({},input,{marginTop:6})},h('option',{value:''},'Selecciona membresía'),window.membershipStore.all().map((membership)=>h('option',{key:membership.id,value:membership.id},membership.empresa)))),h('p',{style:{fontSize:10.5,color:'var(--ink-3)',lineHeight:1.5,marginTop:15}},'Este panel define la regla del trámite. No modifica el catálogo de tipos documentales.')),
      h('section',{style:Object.assign({},panel,{padding:16})},h('div',{style:{fontSize:10.5,fontWeight:850,color:'var(--ink-3)',textTransform:'uppercase'}},'Tipos documentales disponibles'),h('h2',{style:{fontSize:17,margin:'5px 0 10px'}},'Documentos requeridos'),h('div',null,types.filter((type)=>type.enabled).map((type)=>{const existing=reqRows.find((row)=>row.document_type_id===type.id);return h('div',{key:type.id,style:{display:'flex',alignItems:'center',gap:12,padding:'11px 0',borderTop:'1px solid var(--hairline)'}},h('span',{style:{flex:1,fontSize:12.5,fontWeight:800}},businessLabel(type)),h('label',{style:{fontSize:11,fontWeight:750}},'Obligatorio ',h('input',{type:'checkbox',disabled:!canWrite,checked:!!(existing&&existing.required),onChange:async(event)=>{await window.DocumentWorkflowRepository.saveRequirement({program_id:reqTarget.program_id,membership_offering_id:reqTarget.membership_offering_id||null,document_type_id:type.id,required:event.target.checked,allow_verified_reuse:true,sort_order:existing&&existing.sort_order||type.sort_order,enabled:true});await loadRequirements();}})));}))))
  }

  function DesktopConfiguration(props){
    const tabs=[['catalog','Catálogo'],['requirements','Requisitos'],['terms','Términos'],['qr','QR']];
    return h('div',{'data-document-configuration':'true'},h('div',{style:{display:'flex',gap:6,marginBottom:14,padding:5,borderRadius:14,background:'#E8E8EC',width:'fit-content'}},tabs.map((entry)=>h('button',{key:entry[0],type:'button',onClick:()=>props.setTab(entry[0]),style:{border:0,borderRadius:10,padding:'9px 14px',fontWeight:850,background:props.tab===entry[0]?'#fff':'transparent',color:props.tab===entry[0]?'var(--guinda)':'var(--ink-2)',boxShadow:props.tab===entry[0]?'0 3px 10px rgba(31,35,48,.08)':'none'}},entry[1]))),
      props.tab==='catalog'&&h(DesktopCatalog,props),
      props.tab==='requirements'&&h(RequirementsPanel,props),
      props.tab==='terms'&&h('section',{style:Object.assign({},panel,{padding:18,maxWidth:820})},h('div',{style:{fontSize:10.5,fontWeight:850,color:'var(--ink-3)',textTransform:'uppercase'}},'Configuración · términos'),h('h2',{style:{fontSize:17,margin:'5px 0 14px'}},'Publicar nueva versión'),h('select',{value:props.terms.program_id,onChange:(event)=>props.setTerms((value)=>Object.assign({},value,{program_id:event.target.value,membership_offering_id:''})),style:input},h('option',{value:'prestamo'},'Suti Préstamo'),h('option',{value:'membership'},'Membresía')),props.terms.program_id==='membership'&&h('select',{value:props.terms.membership_offering_id,onChange:(event)=>props.setTerms((value)=>Object.assign({},value,{membership_offering_id:event.target.value})),style:Object.assign({},input,{marginTop:9})},h('option',{value:''},'Selecciona membresía'),window.membershipStore.all().map((membership)=>h('option',{key:membership.id,value:membership.id},membership.empresa))),h('input',{value:props.terms.title,onChange:(event)=>props.setTerms((value)=>Object.assign({},value,{title:event.target.value})),placeholder:'Título de la versión',style:Object.assign({},input,{marginTop:9})}),h('textarea',{value:props.terms.body,onChange:(event)=>props.setTerms((value)=>Object.assign({},value,{body:event.target.value})),placeholder:'Texto completo de términos y condiciones',rows:10,style:Object.assign({},input,{marginTop:9,resize:'vertical'})}),h(window.Btn,{full:true,disabled:props.busy==='terms'||props.terms.title.trim().length<3||props.terms.body.trim().length<20||(props.terms.program_id==='membership'&&!props.terms.membership_offering_id)||!props.app.admin.has('documents.write'),onClick:props.publish,style:{marginTop:12}},'Publicar nueva versión')),
      props.tab==='qr'&&h('section',{style:Object.assign({},panel,{padding:18,maxWidth:720})},h('div',{style:{fontSize:10.5,fontWeight:850,color:'var(--ink-3)',textTransform:'uppercase'}},'Configuración secundaria'),h('h2',{style:{fontSize:17,margin:'5px 0 4px'}},'Credencial QR'),h('p',{style:{fontSize:11.5,color:'var(--ink-3)',margin:'0 0 14px'}},'Destino actual: Credencial del afiliado'),h('label',{style:{display:'block',fontSize:12,fontWeight:800}},'Vigencia en segundos',h('input',{type:'number',min:15,max:120,value:props.qr.ttl_seconds,onChange:(event)=>props.setQr((value)=>Object.assign({},value,{ttl_seconds:event.target.value})),style:Object.assign({},input,{marginTop:6})})),h('details',{style:{marginTop:13}},h('summary',{style:{fontSize:11,color:'var(--guinda)',fontWeight:800,cursor:'pointer'}},'Detalles técnicos del destino'),h('label',{style:{display:'block',fontSize:11,fontWeight:800,marginTop:9}},'Ruta permitida',h('input',{value:props.qr.destination_path,onChange:(event)=>props.setQr((value)=>Object.assign({},value,{destination_path:event.target.value})),style:Object.assign({},input,{marginTop:6})}))),h(window.Btn,{full:true,disabled:props.busy==='qr'||!props.app.admin.has('content.write'),onClick:props.saveQr,style:{marginTop:14}},'Guardar política QR')));
  }

  function MobileDocuments(props){
    const visibleQueue=props.queue.filter((d)=>{const affiliate=d.affiliate||{},type=d.document_type||{};return !props.reviewFilter||[affiliate.display_name,affiliate.full_name,affiliate.numero_control,type.label,d.status].join(' ').toLowerCase().includes(props.reviewFilter.toLowerCase());});
    return h('div',null,props.header({title:'Documentos y credencial',sub:props.queue.length+' revisión(es) pendiente(s)',onBack:props.onBack}),h('div',{className:'su-app-scroll',style:{padding:16,paddingBottom:30}},
      props.error&&h('div',{role:'alert',style:{color:'#A32921',fontWeight:700}},props.error),h('div',{style:{display:'flex',gap:6,overflowX:'auto',marginBottom:14}},[['review','Revisión'],['catalog','Catálogo'],['requirements','Requisitos'],['terms','Términos'],['qr','QR']].map((entry)=>h('button',{key:entry[0],onClick:()=>props.setTab(entry[0]),style:{border:'none',borderRadius:999,padding:'9px 13px',fontWeight:800,background:props.tab===entry[0]?'var(--guinda)':'var(--surface-2)',color:props.tab===entry[0]?'#fff':'var(--ink-2)'}},entry[1]))),
      props.tab==='review'&&h('div',{style:{display:'flex',flexDirection:'column',gap:10}},h('input',{value:props.reviewFilter,onChange:(event)=>props.setReviewFilter(event.target.value),placeholder:'Filtrar por afiliado, control, documento o estado',style:input,'aria-label':'Filtrar revisión documental'}),visibleQueue.length?visibleQueue.map((d)=>h('div',{key:d.id,style:{background:'#fff',borderRadius:16,padding:13,boxShadow:'var(--neo-sm)'}},h('b',null,d.document_type&&d.document_type.label),h('div',{style:{fontSize:12,color:'var(--ink-3)',marginTop:3}},(d.affiliate&&(d.affiliate.display_name||d.affiliate.full_name))+' · '+(d.affiliate&&d.affiliate.numero_control)),h('div',{style:{display:'flex',gap:7,marginTop:11}},h('button',{disabled:!d.signedUrl,onClick:()=>window.open(d.signedUrl,'_blank','noopener,noreferrer'),style:{border:'none',borderRadius:10,padding:9,background:'var(--surface-2)',color:'var(--ink)',fontWeight:800}},'Ver'),h('button',{disabled:props.busy===d.id,onClick:()=>props.mobileReview(d.id,'VERIFIED'),style:{flex:1,border:'none',borderRadius:10,padding:9,background:'#E5F7EF',color:'#087A50',fontWeight:800}},'Aprobar'),h('button',{disabled:props.busy===d.id,onClick:()=>props.mobileReview(d.id,'REUPLOAD_REQUIRED'),style:{flex:1,border:'none',borderRadius:10,padding:9,background:'#FCE9EE',color:'#A00027',fontWeight:800}},'Pedir carga')))):h(window.EmptyState,{icon:'checkCircle',title:'Sin resultados',sub:props.reviewFilter?'Ningún documento coincide con el filtro.':'No hay documentos pendientes de revisión.'})),
      props.tab==='catalog'&&h('div',{style:{display:'flex',flexDirection:'column',gap:9}},h(window.Btn,{full:true,icon:'plus',onClick:props.createType},'Nuevo tipo documental'),props.types.map((type)=>h('div',{key:type.id,draggable:props.busy!=='order',onDragStart:()=>props.setDragId(type.id),onDragOver:(event)=>event.preventDefault(),onDrop:()=>props.reorderType(type.id),style:{display:'flex',alignItems:'center',gap:8,background:'#fff',borderRadius:14,padding:11,cursor:'grab'}},h(I,{name:'menu',size:18}),h(I,{name:type.icon||'doc',size:20}),h('div',{style:{flex:1,minWidth:0}},h('input',{value:type.label,onChange:(event)=>props.setTypes((all)=>all.map((item)=>item.id===type.id?Object.assign({},item,{label:event.target.value}):item)),onBlur:async(event)=>{await window.DocumentWorkflowRepository.saveType(Object.assign({},type,{label:event.target.value.trim()}));await props.load();},style:{border:'none',font:'800 13px var(--font)',width:'100%'}}),h('div',{style:{fontSize:10.5,color:'var(--ink-3)'}},type.code),h('label',{style:{display:'flex',alignItems:'center',gap:5,fontSize:10.5,fontWeight:800,color:type.required_by_default?'var(--guinda)':'var(--ink-3)',marginTop:5}},h('input',{'data-global-required':type.code,type:'checkbox',checked:!!type.required_by_default,onChange:async(event)=>{await window.DocumentWorkflowRepository.saveType(Object.assign({},type,{required_by_default:event.target.checked}));await props.load();}}),'Cuenta para el 100% del expediente')),h('input',{type:'number',min:1,value:type.sort_order,'aria-label':'Orden accesible',onChange:(event)=>props.setTypes((all)=>all.map((item)=>item.id===type.id?Object.assign({},item,{sort_order:event.target.value}):item)),onBlur:async(event)=>{await window.DocumentWorkflowRepository.saveType(Object.assign({},type,{sort_order:Number(event.target.value)}));await props.load();},style:Object.assign({},input,{width:42})}),h(window.Toggle,{on:type.enabled,onClick:async()=>{await window.DocumentWorkflowRepository.saveType(Object.assign({},type,{enabled:!type.enabled}));await props.load();}}),!type.system_type&&h('button',{onClick:async()=>{if(confirm('¿Eliminar este tipo sin uso?'))try{await window.DocumentWorkflowRepository.removeType(type.id);await props.load();}catch(_){props.app.toast&&props.app.toast('No puede eliminarse porque ya está relacionado. Desactívalo.');}},style:{border:'none',background:'#FCE9EE',color:'#A00027',borderRadius:9,width:32,height:32}},h(I,{name:'trash',size:15}))))),
      props.tab==='requirements'&&h('div',{style:{background:'#fff',borderRadius:16,padding:14}},h('select',{value:props.reqTarget.program_id,onChange:(event)=>props.setReqTarget({program_id:event.target.value,membership_offering_id:''}),style:input},h('option',{value:'prestamo'},'Suti Préstamo'),h('option',{value:'membership'},'Membresía')),props.reqTarget.program_id==='membership'&&h('select',{value:props.reqTarget.membership_offering_id,onChange:(event)=>props.setReqTarget((value)=>Object.assign({},value,{membership_offering_id:event.target.value})),style:Object.assign({},input,{marginTop:9})},h('option',{value:''},'Selecciona membresía'),window.membershipStore.all().map((membership)=>h('option',{key:membership.id,value:membership.id},membership.empresa))),h('div',{style:{display:'flex',flexDirection:'column',gap:8,marginTop:12}},props.types.filter((type)=>type.enabled).map((type)=>{const existing=props.reqRows.find((row)=>row.document_type_id===type.id);return h('div',{key:type.id,style:{display:'flex',alignItems:'center',gap:9,padding:'9px 0',borderTop:'1px solid var(--hairline)'}},h('div',{style:{flex:1,fontSize:12.5,fontWeight:800}},type.label),h('label',{style:{fontSize:11,fontWeight:700}},'Obligatorio ',h('input',{type:'checkbox',checked:!!(existing&&existing.required),onChange:async(event)=>{await window.DocumentWorkflowRepository.saveRequirement({program_id:props.reqTarget.program_id,membership_offering_id:props.reqTarget.membership_offering_id||null,document_type_id:type.id,required:event.target.checked,allow_verified_reuse:true,sort_order:existing&&existing.sort_order||type.sort_order,enabled:true});await props.loadRequirements();}})));}))),
      props.tab==='terms'&&h('div',{style:{background:'#fff',borderRadius:16,padding:14}},h('select',{value:props.terms.program_id,onChange:(event)=>props.setTerms((value)=>Object.assign({},value,{program_id:event.target.value,membership_offering_id:''})),style:input},h('option',{value:'prestamo'},'Suti Préstamo'),h('option',{value:'membership'},'Membresía')),props.terms.program_id==='membership'&&h('select',{value:props.terms.membership_offering_id,onChange:(event)=>props.setTerms((value)=>Object.assign({},value,{membership_offering_id:event.target.value})),style:Object.assign({},input,{marginTop:9})},h('option',{value:''},'Selecciona membresía'),window.membershipStore.all().map((membership)=>h('option',{key:membership.id,value:membership.id},membership.empresa))),h('input',{value:props.terms.title,onChange:(event)=>props.setTerms((value)=>Object.assign({},value,{title:event.target.value})),placeholder:'Título de la versión',style:Object.assign({},input,{marginTop:9})}),h('textarea',{value:props.terms.body,onChange:(event)=>props.setTerms((value)=>Object.assign({},value,{body:event.target.value})),placeholder:'Texto completo de términos y condiciones',rows:10,style:Object.assign({},input,{marginTop:9,resize:'vertical'})}),h(window.Btn,{full:true,disabled:props.busy==='terms'||props.terms.title.trim().length<3||props.terms.body.trim().length<20||(props.terms.program_id==='membership'&&!props.terms.membership_offering_id),onClick:props.publish,style:{marginTop:12}},'Publicar nueva versión')),
      props.tab==='qr'&&h('div',{style:{background:'#fff',borderRadius:16,padding:14}},h('label',{style:{fontSize:12,fontWeight:800}},'Ruta allowlisted',h('input',{value:props.qr.destination_path,onChange:(event)=>props.setQr((value)=>Object.assign({},value,{destination_path:event.target.value})),style:Object.assign({},input,{marginTop:6})})),h('label',{style:{display:'block',fontSize:12,fontWeight:800,marginTop:12}},'Vigencia en segundos',h('input',{type:'number',min:15,max:120,value:props.qr.ttl_seconds,onChange:(event)=>props.setQr((value)=>Object.assign({},value,{ttl_seconds:event.target.value})),style:Object.assign({},input,{marginTop:6})})),h(window.Btn,{full:true,disabled:props.busy==='qr',onClick:props.saveQr,style:{marginTop:14}},'Guardar política QR'))));
  }

  function DocumentsAdminModule({app,onBack,header,initialAffiliateId}){
    const desktop=useDocumentDesktop();
    const[tab,setTab]=React.useState('review');
    const[types,setTypes]=React.useState([]),[queue,setQueue]=React.useState([]),[busy,setBusy]=React.useState(''),[reviewFilter,setReviewFilter]=React.useState(''),[dragId,setDragId]=React.useState(''),[reqTarget,setReqTarget]=React.useState({program_id:'prestamo',membership_offering_id:''}),[reqRows,setReqRows]=React.useState([]),[terms,setTerms]=React.useState({program_id:'prestamo',membership_offering_id:'',title:'',body:''}),[qr,setQr]=React.useState({destination_path:'/SutiApp.html#credencial',ttl_seconds:30}),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true);
    const[selectedId,setSelectedId]=React.useState(''),[preview,setPreview]=React.useState(null),[previewPhase,setPreviewPhase]=React.useState('idle'),[previewError,setPreviewError]=React.useState(''),[previewNonce,setPreviewNonce]=React.useState(0),[statusFilter,setStatusFilter]=React.useState(''),[typeFilter,setTypeFilter]=React.useState(''),[affiliateFilter,setAffiliateFilter]=React.useState(initialAffiliateId||''),[sort,setSort]=React.useState('oldest'),[decision,setDecision]=React.useState(''),[observation,setObservation]=React.useState(''),[rowFeedback,setRowFeedback]=React.useState({});
    React.useEffect(()=>{if(initialAffiliateId)setAffiliateFilter(initialAffiliateId);},[initialAffiliateId]);
    const load=React.useCallback(async()=>{setLoading(true);try{const[t,q,s]=await Promise.all([window.DocumentWorkflowRepository.catalog({includeDisabled:true}),window.DocumentWorkflowRepository.reviewQueue({includePreviews:!desktop}),window.SutiSupabase.getClient().from('credential_qr_settings').select('*').single()]);setTypes(t.slice());setQueue(q.slice());if(!s.error)setQr(s.data);setError('');}catch(_){setError('No fue posible cargar la configuración documental.');}finally{setLoading(false);}},[desktop]);
    React.useEffect(()=>{load();if(window.membershipStore.state().phase==='idle')window.membershipStore.load(false);},[load]);
    const loadRequirements=React.useCallback(async()=>{if(reqTarget.program_id==='membership'&&!reqTarget.membership_offering_id){setReqRows([]);return;}try{setReqRows((await window.DocumentWorkflowRepository.requirements(reqTarget.program_id,reqTarget.membership_offering_id||null)).slice());}catch(_){setReqRows([]);}},[reqTarget.program_id,reqTarget.membership_offering_id]);
    React.useEffect(()=>{loadRequirements();},[loadRequirements]);
    const visibleQueue=queue.filter((row)=>{const text=[affiliateName(row),row.affiliate&&row.affiliate.numero_control,businessLabel(row.document_type),stateInfo(row.status).label].join(' ').toLowerCase();return(!reviewFilter||text.includes(reviewFilter.toLowerCase()))&&(!statusFilter||row.status===statusFilter)&&(!typeFilter||row.document_type_id===typeFilter)&&(!affiliateFilter||row.affiliate_id===affiliateFilter);}).slice().sort((a,b)=>{if(sort==='newest')return new Date(b.created_at)-new Date(a.created_at);if(sort==='affiliate')return affiliateName(a).localeCompare(affiliateName(b),'es');if(sort==='document')return businessLabel(a.document_type).localeCompare(businessLabel(b.document_type),'es');return new Date(a.created_at)-new Date(b.created_at);});
    React.useEffect(()=>{if(!desktop)return;if(visibleQueue.length&&!visibleQueue.some((row)=>row.id===selectedId))setSelectedId(visibleQueue[0].id);else if(!visibleQueue.length&&selectedId)setSelectedId('');},[desktop,queue,reviewFilter,statusFilter,typeFilter,affiliateFilter,sort,selectedId]);
    React.useEffect(()=>{if(!desktop||!selectedId){setPreview(null);setPreviewPhase('idle');setPreviewError('');return;}let active=true;setPreviewPhase('loading');setPreviewError('');window.DocumentWorkflowRepository.reviewPreview(selectedId).then((row)=>{if(active){setPreview(row);setPreviewPhase('ready');}}).catch(()=>{if(active){setPreview(null);setPreviewPhase('error');setPreviewError('PREVIEW_UNAVAILABLE');}});return()=>{active=false;};},[desktop,selectedId,previewNonce]);
    React.useEffect(()=>{setDecision('');setObservation('');},[selectedId]);
    const position=Math.max(0,visibleQueue.findIndex((row)=>row.id===selectedId))+1;
    const go=(delta)=>{if(!visibleQueue.length)return;const current=Math.max(0,visibleQueue.findIndex((row)=>row.id===selectedId)),next=Math.max(0,Math.min(visibleQueue.length-1,current+delta));setSelectedId(visibleQueue[next].id);};
    const commitDecision=async(advance)=>{const selected=visibleQueue.find((row)=>row.id===selectedId)||queue.find((row)=>row.id===selectedId);if(!selected||!decision||!app.admin.has('documents.write'))return;const currentIndex=visibleQueue.findIndex((row)=>row.id===selected.id),nextRow=visibleQueue[currentIndex+1]||null;setBusy(selected.id);setRowFeedback((all)=>Object.assign({},all,{[selected.id]:{tone:'saving',text:'Guardando…'}}));try{const result=await window.DocumentWorkflowRepository.review(selected.id,decision,observation);const merged=Object.assign({},selected,result,{document_type:selected.document_type,affiliate:selected.affiliate,affiliate_file:selected.affiliate_file,private_asset:selected.private_asset,signedUrl:preview&&preview.signedUrl||null,mimeType:preview&&preview.mimeType||selected.mimeType});setQueue((all)=>all.map((row)=>row.id===selected.id?merged:row));setPreview(merged);setRowFeedback((all)=>Object.assign({},all,{[selected.id]:{tone:'success',text:decision==='VERIFIED'?'✓ Verificado':'! Requiere nueva carga'}}));if(advance&&nextRow&&nextRow.id!==selected.id)setSelectedId(nextRow.id);setDecision('');setObservation('');}catch(_){setRowFeedback((all)=>Object.assign({},all,{[selected.id]:{tone:'error',text:'Error al guardar · Reintentar'}}));}finally{setBusy('');}};
    const mobileReview=async(id,status)=>{setBusy(id);try{const observationValue=status==='VERIFIED'?'':prompt('Observación para el afiliado:')||'';await window.DocumentWorkflowRepository.review(id,status,observationValue);await load();}catch(_){app.toast&&app.toast('No se pudo completar la revisión');}finally{setBusy('');}};
    const publish=async()=>{setBusy('terms');try{await window.ProgramTermsRepository.publish(terms.program_id,terms.membership_offering_id||null,terms.title,terms.body);setTerms((value)=>Object.assign({},value,{title:'',body:''}));app.toast&&app.toast('Nueva versión publicada');}catch(_){app.toast&&app.toast('No se pudieron publicar los términos');}finally{setBusy('');}};
    const saveQr=async()=>{setBusy('qr');try{const result=await window.SutiSupabase.getClient().from('credential_qr_settings').update({destination_path:qr.destination_path,ttl_seconds:Number(qr.ttl_seconds),updated_by_auth_user_id:app.admin.user&&app.admin.user.id,updated_at:new Date().toISOString()}).eq('id',true);if(result.error)throw result.error;app.toast&&app.toast('Destino QR actualizado');}catch(_){app.toast&&app.toast('No se pudo actualizar el QR');}finally{setBusy('');}};
    const reorderType=async(targetId)=>{if(!dragId||dragId===targetId)return;const next=types.slice(),from=next.findIndex((type)=>type.id===dragId),to=next.findIndex((type)=>type.id===targetId);if(from<0||to<0)return;const slots=types.map((type)=>Number(type.sort_order)),original=new Map(types.map((type)=>[type.id,Number(type.sort_order)])),moved=next.splice(from,1)[0];next.splice(to,0,moved);const ordered=next.map((type,index)=>Object.assign({},type,{sort_order:slots[index]})),changed=ordered.filter((type)=>original.get(type.id)!==type.sort_order);setTypes(ordered);setBusy('order');try{await Promise.all(changed.map((type)=>window.DocumentWorkflowRepository.saveType(type)));await load();}catch(_){app.toast&&app.toast('No se pudo guardar el orden');await load();}finally{setBusy('');setDragId('');}};
    const createType=async()=>{const label=prompt('Nombre del tipo de documento:');if(!label)return;const code=prompt('Código técnico (minúsculas y guiones bajos):');if(!code)return;try{await window.DocumentWorkflowRepository.saveType({code,label,description:'',icon:'doc',required_by_default:false,accepted_mime_types:['image/jpeg','image/png','image/webp','application/pdf'],enabled:true,sort_order:types.length+1,system_type:false});await load();}catch(_){app.toast&&app.toast('No se pudo crear el tipo');}};
    const common={app,onBack,header,tab,setTab,types,setTypes,queue,busy,reviewFilter,setReviewFilter,dragId,setDragId,reqTarget,setReqTarget,reqRows,terms,setTerms,qr,setQr,error,load,loadRequirements,reorderType,publish,saveQr,mobileReview,createType};
    if(!desktop)return h(MobileDocuments,common);
    const configTab=tab==='review'?'catalog':tab;
    return h('div',{'data-admin-document-desktop':'true'},header({title:'Documentos y credencial',sub:queue.length+' documentos en la cola operativa',onBack}),h('div',{className:'su-app-scroll',style:{padding:'16px 18px 28px'}},
      error&&h('div',{role:'alert',style:{color:'#A32921',fontWeight:800,marginBottom:10}},error),
      h('nav',{'aria-label':'Área de documentos',style:{display:'flex',gap:8,marginBottom:14}},h('button',{type:'button','data-document-area':'operation',onClick:()=>setTab('review'),style:{border:0,borderRadius:12,padding:'10px 15px',fontWeight:850,background:tab==='review'?'var(--guinda)':'#fff',color:tab==='review'?'#fff':'var(--ink-2)',boxShadow:'0 5px 16px rgba(31,35,48,.07)'}},'Bandeja de revisión'),h('button',{type:'button','data-document-area':'configuration',onClick:()=>setTab(configTab),style:{border:0,borderRadius:12,padding:'10px 15px',fontWeight:850,background:tab!=='review'?'var(--guinda)':'#fff',color:tab!=='review'?'#fff':'var(--ink-2)',boxShadow:'0 5px 16px rgba(31,35,48,.07)'}},'Configuración documental')),
      loading&&queue.length===0?h('div',{style:{padding:35,textAlign:'center',fontWeight:800,color:'var(--ink-3)'}},'Cargando documentos…'):tab==='review'?h(DesktopReview,{app,types,queue,visibleQueue,selectedId,setSelectedId,preview,previewPhase,previewError,retryPreview:()=>setPreviewNonce((value)=>value+1),reviewFilter,setReviewFilter,statusFilter,setStatusFilter,typeFilter,setTypeFilter,affiliateFilter,setAffiliateFilter,sort,setSort,rowFeedback,decision,setDecision,observation,setObservation,commitDecision,go,position,saving:busy===selectedId}):h(DesktopConfiguration,Object.assign({},common,{tab,setTab}))))
  }
  window.DocumentsAdminModule=DocumentsAdminModule;
})();
