/* Claude-consistent operational export center. No browser database reads. */
(function(){
  'use strict';
  const I=window.Icon;
  function FilterControl({name,type,value,onChange}){
    const label=name.replaceAll('_',' ');
    if(type==='boolean')return React.createElement('label',{style:{fontSize:11,fontWeight:800,color:'var(--ink-3)'}},label,React.createElement('select',{value:value===undefined?'':String(value),onChange:e=>onChange(e.target.value===''?undefined:e.target.value==='true'),style:{display:'block',width:'100%',marginTop:5,padding:'9px 10px',borderRadius:10,border:'1px solid var(--line)',background:'var(--surface)',fontFamily:'inherit'}},React.createElement('option',{value:''},'Todos'),React.createElement('option',{value:'true'},'Sí'),React.createElement('option',{value:'false'},'No')));
    return React.createElement('label',{style:{fontSize:11,fontWeight:800,color:'var(--ink-3)'}},label,React.createElement('input',{type:type==='date'?'date':'text',value:value||'',onChange:e=>onChange(e.target.value||undefined),placeholder:'Valor exacto',style:{display:'block',width:'100%',boxSizing:'border-box',marginTop:5,padding:'9px 10px',borderRadius:10,border:'1px solid var(--line)',background:'var(--surface)',fontFamily:'inherit'}}));
  }
  function DomainCard({domain,app}){
    const[filters,setFilters]=React.useState({});const[busy,setBusy]=React.useState('');
    const run=async format=>{setBusy(format);try{await window.DataExportRepository.download(domain.key,format,filters,domain.label);app.toast('Exportación generada y auditada');}catch(_){app.toast('No fue posible generar la exportación');}finally{setBusy('');}};
    const filterEntries=Object.entries(domain.filters||{});
    return React.createElement('article',{'data-export-domain':domain.key,style:{background:'var(--surface)',borderRadius:18,padding:15,boxShadow:'var(--neo-sm)'}},
      React.createElement('div',{style:{display:'flex',gap:12,alignItems:'flex-start'}},React.createElement('div',{style:{width:42,height:42,borderRadius:13,background:'var(--grad-guinda-soft)',color:'#fff',display:'grid',placeItems:'center',flexShrink:0}},React.createElement(I,{name:'download',size:22,stroke:2})),React.createElement('div',{style:{flex:1,minWidth:0}},React.createElement('div',{style:{fontSize:15,fontWeight:900,color:'var(--ink)'}},domain.label),React.createElement('div',{style:{fontSize:11.5,fontWeight:600,color:'var(--ink-3)',lineHeight:1.4,marginTop:3}},domain.description),Number.isInteger(domain.record_count)&&React.createElement('div',{style:{fontSize:10.5,fontWeight:850,color:'var(--guinda)',marginTop:5}},domain.record_count.toLocaleString('es-MX'),' registros'))),
      domain.sensitive_pii&&React.createElement('div',{style:{marginTop:10,padding:'8px 10px',borderRadius:10,background:'#FFF4E5',color:'#8A4B08',fontSize:10.5,fontWeight:800}},'Contiene PII autorizada · resguarda el archivo descargado'),
      filterEntries.length>0&&React.createElement('details',{style:{marginTop:11}},React.createElement('summary',{style:{fontSize:11.5,fontWeight:850,color:'var(--ink-2)',cursor:'pointer'}},'Filtros (',filterEntries.length,')'),React.createElement('div',{style:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9,marginTop:10}},filterEntries.map(([name,type])=>React.createElement(FilterControl,{key:name,name,type,value:filters[name],onChange:value=>setFilters(current=>Object.assign({},current,{[name]:value}))})))),
      React.createElement('div',{style:{display:'flex',gap:8,marginTop:13}},React.createElement('button',{disabled:Boolean(busy),onClick:()=>run('xlsx'),style:{flex:1,border:0,borderRadius:12,padding:'11px 8px',background:'var(--grad-guinda-soft)',color:'#fff',fontFamily:'inherit',fontWeight:900,cursor:'pointer'}},busy==='xlsx'?'Generando…':'XLSX'),React.createElement('button',{disabled:Boolean(busy),onClick:()=>run('csv'),style:{flex:1,border:'1px solid var(--line)',borderRadius:12,padding:'11px 8px',background:'var(--surface)',color:'var(--ink)',fontFamily:'inherit',fontWeight:900,cursor:'pointer'}},busy==='csv'?'Generando…':'CSV')));
  }
  function DataExportsModule({app,onBack,header}){
    const[state,setState]=React.useState({phase:'loading',domains:[],backup:null,detail:''});
    const load=()=>{setState(s=>Object.assign({},s,{phase:'loading'}));window.DataExportRepository.listDomains().then(data=>setState({phase:'ready',domains:data.domains||[],backup:data.technical_backup||null,detail:''})).catch(error=>setState({phase:'error',domains:[],backup:null,detail:[error&&error.code,error&&error.status?'HTTP '+error.status:''].filter(Boolean).join(' · ')}));};
    React.useEffect(load,[]);
    return React.createElement('div',{'data-admin-data-exports':state.phase},header({title:'Datos y respaldos',sub:'Exportaciones operativas autorizadas',onBack}),React.createElement(window.ActingBanner,{}),React.createElement('div',{className:'su-app-scroll',style:{padding:'16px 16px 28px'}},
      React.createElement('div',{style:{background:'var(--surface)',borderRadius:16,padding:'13px 14px',boxShadow:'var(--neo-sm)',fontSize:11.5,fontWeight:650,color:'var(--ink-2)',lineHeight:1.5,marginBottom:14}},React.createElement('b',null,'Descarga segura por dominio.'),' El archivo se genera en backend, se entrega directamente y no queda público. XLSX/CSV no sustituye el backup técnico de Supabase.'),
      state.phase==='loading'&&React.createElement('div',{style:{padding:30,textAlign:'center',fontWeight:800,color:'var(--ink-3)'}},'Consultando permisos y dominios…'),
      state.phase==='error'&&React.createElement('div',{style:{background:'var(--surface)',borderRadius:16,padding:18,textAlign:'center',boxShadow:'var(--neo-sm)'}},React.createElement('div',{style:{fontWeight:900}},'No fue posible consultar la fuente autorizada.'),state.detail&&React.createElement('div',{'data-export-error-detail':state.detail,style:{marginTop:6,fontSize:10.5,fontWeight:800,color:'var(--ink-3)',fontFamily:'var(--mono)'}},state.detail),React.createElement('button',{onClick:load,style:{marginTop:12}},'Reintentar')),
      state.phase==='ready'&&React.createElement(React.Fragment,null,React.createElement('div',{style:{display:'grid',gap:12}},state.domains.map(domain=>React.createElement(DomainCard,{key:domain.key,domain,app}))),!state.domains.length&&React.createElement('div',{style:{padding:24,textAlign:'center'}},'No hay dominios exportables para esta cuenta.'),React.createElement('section',{style:{marginTop:15,background:'var(--surface-2)',borderRadius:16,padding:14}},React.createElement('div',{style:{fontSize:13,fontWeight:900,color:'var(--ink)'}},'Backup técnico'),React.createElement('div',{style:{fontSize:11.5,fontWeight:650,color:'var(--ink-3)',marginTop:4,lineHeight:1.45}},state.backup&&state.backup.message||'Administrado por Supabase CLI/SQL fuera de esta sección.')))));
  }
  window.DataExportsModule=DataExportsModule;
})();
