/* User Savings read-only experience. The approved Claude Design hierarchy is
   preserved while every value comes from the certified Supabase SHADOW reader. */
(function () {
  'use strict';
  const h = React.createElement;
  const I = window.Icon;
  const ACTION_LABELS = { JOIN: 'Ingresar al ahorro', CHANGE_AMOUNT: 'Modificar monto', WITHDRAW: 'Retirar ahorro', TERMINATE: 'Darme de baja' };
  const ACTION_ORDER = ['WITHDRAW', 'CHANGE_AMOUNT', 'TERMINATE', 'JOIN'];
  const ACTION_ICONS = { JOIN: 'checkCircle', CHANGE_AMOUNT: 'edit', WITHDRAW: 'cash', TERMINATE: 'refresh' };
  const CSS = `
    .su-savings{--sav-wine:#8a1538;--sav-wine-dark:#65102a;--sav-red:#8a1538;--sav-pink:#f8edf1;--sav-ink:#171719;--sav-muted:#8a8a90;--sav-line:#ededf0;--sav-bg:#f3f3f5;position:absolute;inset:0;display:flex;flex-direction:column;background:var(--sav-bg);color:var(--sav-ink);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow:hidden}.su-savings *{box-sizing:border-box}
    .sav-scroll{flex:1;min-height:0;overflow:auto;scrollbar-width:none}.sav-scroll::-webkit-scrollbar{display:none}.sav-hero{position:sticky;top:0;z-index:5;padding:calc(8px + env(safe-area-inset-top)) 16px 8px;background:#fff;color:var(--sav-ink);border-bottom:1px solid var(--sav-line)}.sav-hero:after{display:none}
    .sav-head{display:flex;align-items:center;gap:8px;min-height:48px}.sav-back,.sav-info{height:40px;border:0;background:transparent;color:var(--sav-wine);display:flex;align-items:center;justify-content:center;gap:4px;cursor:pointer}.sav-back{width:40px}.sav-info{width:38px}.sav-head-copy{flex:1;min-width:0;text-align:center}.sav-head-copy b{display:block;font-size:17px;font-weight:750}.sav-head-copy span{display:none}.sav-head-actions{display:flex;gap:0}.sav-source{display:none}.sav-provenance{margin:10px 2px 0;color:#8f8f95;font-size:9.5px;font-weight:650;text-align:center;line-height:1.35}
    .sav-body{position:relative;padding:16px 16px 40px}.sav-balance{background:var(--sav-wine);color:#fff;border-radius:20px;padding:18px;box-shadow:0 16px 26px -18px rgba(138,21,56,.8)}.sav-balance-top{display:block}.sav-kicker{font-size:10.5px;font-weight:750;color:var(--sav-muted);text-transform:uppercase;letter-spacing:.07em}.sav-balance .sav-kicker{color:#ebcbd6}.sav-total{font-size:34px;line-height:1.08;font-weight:800;letter-spacing:-.025em;margin-top:8px;font-variant-numeric:tabular-nums}.sav-state{display:none}.sav-split{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:18px}.sav-split>div{min-width:0;padding:10px 11px;border-radius:12px;background:rgba(255,255,255,.12)}.sav-split>div+div{border:0;padding-left:11px}.sav-split span{display:block;font-size:9.5px;font-weight:650;color:#e6c2cf}.sav-split b{display:block;font-size:16px;font-weight:780;margin-top:3px;font-variant-numeric:tabular-nums}.sav-split>div:last-child b{color:#56e09a}.sav-availability{display:none}
    .sav-actions{display:flex;flex-direction:column;gap:9px;margin-top:16px}.sav-action{width:100%;min-height:48px;border:1px solid #dedee2;border-radius:14px;padding:12px 15px;background:#fff;color:#4b4b50;font:700 13px inherit;display:flex;align-items:center;justify-content:center;gap:8px;cursor:pointer}.sav-action:disabled{opacity:.58;cursor:not-allowed}.sav-action>span{width:auto;height:auto;background:transparent;color:currentColor;display:grid;place-items:center}.sav-action[data-primary=true]{background:var(--sav-wine);border-color:var(--sav-wine);color:#fff;opacity:.68}.sav-action[data-primary=true]>span{background:transparent;color:#fff}
    .sav-section{margin-top:18px}.sav-section-title{display:flex;align-items:flex-end;justify-content:space-between;gap:10px;margin:0 2px 10px}.sav-section-title b{font-size:11px;font-weight:750;color:#99999f;letter-spacing:.075em;text-transform:uppercase}.sav-section-title span{font-size:10px;font-weight:650;color:#a0a0a6;text-align:right}.sav-card,.sav-year{background:#fff;border:1px solid #e6e6e9;border-radius:18px;padding:15px 16px;box-shadow:0 5px 16px -13px rgba(0,0,0,.35)}.sav-year-list{display:flex;flex-direction:column;gap:12px}.sav-year-head{display:flex;justify-content:space-between;align-items:center}.sav-year-head b{font-size:18px;font-weight:780}.sav-year-head span{padding:5px 10px;border-radius:999px;background:#edf8f1;color:#157f4a;font-size:9px;font-weight:750}.sav-year-head span[data-current=true]{background:#fff2d9;color:#9a6813}.sav-year-grid{display:grid;grid-template-columns:1fr 1fr;gap:0;margin-top:14px}.sav-year-grid>div{padding-right:12px}.sav-year-grid>div+div{padding-left:14px;padding-right:0;border-left:1px solid var(--sav-line)}.sav-year-grid span{display:block;font-size:10px;font-weight:600;color:#9a9aa0}.sav-year-grid b{display:block;font-size:18px;font-weight:780;margin-top:3px}.sav-year-grid>div:last-child{text-align:left}.sav-year-grid>div:last-child b{color:#008b50}
    .sav-enroll-head{display:flex;gap:11px;align-items:center}.sav-icon{width:39px;height:39px;border-radius:12px;display:grid;place-items:center;background:var(--sav-pink);color:var(--sav-wine);flex-shrink:0}.sav-enroll-head>div{flex:1;min-width:0}.sav-enroll-head b{display:block;font-size:14px;font-weight:900}.sav-enroll-head span{font-size:11px;font-weight:750;color:var(--sav-muted)}.sav-rows{margin-top:10px}.sav-row{display:flex;justify-content:space-between;gap:14px;padding:8px 0;border-top:1px solid var(--sav-line);font-size:11.5px}.sav-row span{color:var(--sav-muted);font-weight:750}.sav-row b{text-align:right;font-weight:850;overflow-wrap:anywhere}
    .sav-next{display:flex;gap:10px;align-items:center;padding:10px 0;border-top:1px solid var(--sav-line)}.sav-next:first-child,.sav-tx:first-child{border-top:0}.sav-date{width:43px;text-align:center;border-radius:11px;padding:6px 3px;background:#f3f5f8}.sav-date b{display:block;font-size:14px;font-weight:900}.sav-date span{font-size:8.5px;font-weight:850;color:var(--sav-muted);text-transform:uppercase}.sav-next-copy{flex:1;min-width:0}.sav-next-copy b{display:block;font-size:12px}.sav-next-copy span{font-size:10px;color:var(--sav-muted);font-weight:700}.sav-next>strong{font-size:13px;color:var(--sav-wine)}
    .sav-history-tabs{display:flex;gap:7px;overflow:auto;margin-bottom:10px}.sav-history-tabs button{border:0;border-radius:999px;padding:7px 11px;background:#e9edf3;color:#67738a;font:800 10.5px inherit;white-space:nowrap;cursor:pointer}.sav-history-tabs button[aria-pressed=true]{background:var(--sav-wine);color:#fff}.sav-tx{display:grid;grid-template-columns:38px 1fr auto;gap:10px;align-items:center;padding:11px 0;border-top:1px solid var(--sav-line)}.sav-tx-icon{width:36px;height:36px;border-radius:11px;background:#edf8f3;color:#087a50;display:grid;place-items:center}.sav-tx-icon[data-debit=true]{background:var(--sav-pink);color:var(--sav-wine)}.sav-tx b{display:block;font-size:12px}.sav-tx span{font-size:10px;color:var(--sav-muted);font-weight:700}.sav-tx strong{font-size:12.5px;color:#087a50}.sav-tx strong[data-debit=true]{color:var(--sav-wine)}
    .sav-alert{border-radius:13px;padding:10px 12px;background:#efeff1;color:#6f6f75;font-size:10.5px;font-weight:650;line-height:1.45;margin-top:10px}.sav-error{margin:20px 16px;padding:16px;border-radius:17px;background:#fff;color:#9a1834;box-shadow:0 8px 24px -14px rgba(23,35,61,.3);font-size:12px;font-weight:750}.sav-retry,.sav-primary{border:0;border-radius:14px;padding:12px 15px;background:var(--sav-wine);color:#fff;font:750 13px inherit;cursor:pointer}.sav-primary{width:100%;min-height:48px}.sav-primary:disabled{opacity:.5;cursor:default}.sav-empty{padding:28px 18px;text-align:center;background:#fff;color:var(--sav-ink);border:1px solid #e6e6e9;box-shadow:none}.sav-empty .sav-icon{margin:0 auto}.sav-empty h2{font-size:19px;margin:13px 0 5px}.sav-empty p{font-size:12.5px;line-height:1.5;color:var(--sav-muted);margin:0 auto 16px;max-width:300px}
    .sav-overlay{position:fixed;inset:0;z-index:92;background:rgba(14,18,28,.52);display:flex;align-items:flex-end;justify-content:center}.sav-sheet{width:min(100%,520px);background:#fff;border-radius:25px 25px 0 0;padding:9px 18px calc(22px + env(safe-area-inset-bottom));box-shadow:0 -20px 50px rgba(0,0,0,.18)}.sav-handle{width:42px;height:4px;background:#d7dce5;border-radius:999px;margin:2px auto 15px}.sav-sheet-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.sav-sheet h2{font-size:20px;margin:0}.sav-sheet p{font-size:12px;color:var(--sav-muted);font-weight:650;line-height:1.5}.sav-close{width:38px;height:38px;border:0;border-radius:12px;background:#f0f2f6;display:grid;place-items:center;color:var(--sav-ink);cursor:pointer}
    @media(min-width:700px){.sav-body,.sav-head{width:min(430px,100%);margin-left:auto;margin-right:auto}.sav-hero{padding-left:max(16px,calc((100% - 430px)/2));padding-right:max(16px,calc((100% - 430px)/2))}}@media(max-width:390px){.sav-body{padding-left:13px;padding-right:13px}.sav-total{font-size:30px}.sav-action{font-size:12px}}
  `;
  function icon(name, size) { return h(I, { name, size: size || 18, stroke: 2, 'aria-hidden': 'true' }); }
  function money(value) { return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', minimumFractionDigits: 2 }).format(Number(value || 0)); }
  function moneyOrDash(value) { return value == null ? '—' : money(value); }
  function shortDate(value) { return value ? new Date(value + (String(value).length === 10 ? 'T12:00:00' : '')).toLocaleDateString('es-MX', { day: '2-digit', month: 'short', year: 'numeric' }) : 'Por confirmar'; }
  function Sheet({ title, children, onClose }) { return h('div', { className: 'sav-overlay', onMouseDown: (event) => { if (event.target === event.currentTarget) onClose(); }, role: 'presentation' }, h('section', { className: 'sav-sheet', role: 'dialog', 'aria-modal': 'true', 'aria-label': title }, h('div', { className: 'sav-handle' }), h('div', { className: 'sav-sheet-head' }, h('h2', null, title), h('button', { type: 'button', className: 'sav-close', onClick: onClose, 'aria-label': 'Cerrar' }, icon('close', 18))), children)); }

  function SavingsScreen({ app }) {
    const store = window.useSavingsStore('self'), state = store.state(), dashboard = state.self;
    const [sheet, setSheet] = React.useState(''), [historyYear, setHistoryYear] = React.useState('all');
    const reload = () => store.loadSelf(true);
    if (state.selfPhase === 'loading' || state.selfPhase === 'idle') return h('div', { className: 'su-savings', 'data-savings-screen': '', 'data-savings-phase': 'loading' }, h('style', null, CSS), h('div', { className: 'sav-error' }, 'Cargando tu ahorro desde el backend…'));
    if (state.selfPhase === 'error' || !dashboard) return h('div', { className: 'su-savings', 'data-savings-screen': '', 'data-savings-phase': 'error' }, h('style', null, CSS), h('header', { className: 'sav-hero' }, h('div', { className: 'sav-head' }, h('button', { className: 'sav-back', onClick: app.back, 'aria-label': 'Atrás' }, icon('arrowL', 20)), h('div', { className: 'sav-head-copy' }, h('b', null, 'Ahorro'), h('span', null, 'Mi Financiera')))), h('div', { className: 'sav-error', role: 'alert' }, 'No fue posible consultar Ahorro. No mostramos saldos de respaldo.', h('div', { style: { marginTop: 12 } }, h('button', { className: 'sav-retry', onClick: reload }, 'Reintentar'))));
    const participant = dashboard.participant, enrollment = dashboard.enrollment, balance = dashboard.balances, years = dashboard.annual || [];
    const historyYears = Array.from(new Set((dashboard.history || []).map((item) => String(item.effective_date || '').slice(0, 4)).filter(Boolean)));
    const history = (dashboard.history || []).filter((item) => historyYear === 'all' || String(item.effective_date || '').startsWith(historyYear));
    const canWriteRequests = Boolean(dashboard.write_capabilities && dashboard.write_capabilities.requests), canWriteBeneficiaries = Boolean(dashboard.write_capabilities && dashboard.write_capabilities.beneficiaries);
    const detailRow = (label, value) => h('div', { className: 'sav-row', key: label }, h('span', null, label), h('b', null, value == null || value === '' ? 'Por confirmar' : value));
    const section = (title, note, content) => h('section', { className: 'sav-section' }, h('div', { className: 'sav-section-title' }, h('b', null, title), h('span', null, note)), content);
    return h('div', { className: 'su-savings', 'data-savings-screen': '', 'data-savings-authority': dashboard.authority, 'data-savings-projection': dashboard.projection, 'data-savings-cutover': dashboard.cutover_status }, h('style', null, CSS), h('div', { className: 'sav-scroll' },
      h('header', { className: 'sav-hero' }, h('div', { className: 'sav-head' }, h('button', { type: 'button', className: 'sav-back', onClick: app.back, 'aria-label': 'Atrás' }, icon('arrowL', 20)), h('div', { className: 'sav-head-copy' }, h('b', null, 'Ahorro'), h('span', null, 'Tu ahorro, claro y en un solo lugar')), h('div', { className: 'sav-head-actions' }, h('button', { type: 'button', className: 'sav-info', onClick: reload, 'aria-label': 'Actualizar ahorro', 'data-savings-refresh': '' }, icon('refresh', 17)), h('button', { type: 'button', className: 'sav-info', onClick: () => setSheet('INFO'), 'aria-label': 'Información' }, icon('info', 17))))),
      h('main', { className: 'sav-body' }, participant ? h(React.Fragment, null,
        h('section', { className: 'sav-balance', 'aria-label': 'Resumen de ahorro' }, h('div', { className: 'sav-balance-top' }, h('div', null, h('div', { className: 'sav-kicker' }, 'Saldo actual total · Q'), h('div', { className: 'sav-total', 'data-savings-total': balance && balance.total != null ? String(balance.total) : '' }, balance && balance.total != null ? money(balance.total) : 'No reportado en Q')), h('span', { className: 'sav-state' }, enrollment && enrollment.status || 'LEGACY')), h('div', { className: 'sav-split' }, h('div', null, h('span', null, 'AHORRADO HISTÓRICO'), h('b', { 'data-savings-capital': balance && balance.capital != null ? String(balance.capital) : '' }, balance ? moneyOrDash(balance.capital) : '—')), h('div', null, h('span', null, 'RENDIMIENTO HISTÓRICO'), h('b', { 'data-savings-yield': balance && balance.yield != null ? String(balance.yield) : '' }, balance ? moneyOrDash(balance.yield) : '—'))), h('div', { className: 'sav-availability' }, h('div', { className: 'sav-chip' }, 'Saldo mostrado', h('b', null, 'Columna Q')), h('div', { className: 'sav-chip' }, 'Capital / rendimiento', h('b', null, 'DP:DW directo')))),
        h('div', { className: 'sav-provenance', 'data-savings-provenance': '' }, 'Google legacy · SHADOW certificado · saldo Q · DP:DW directo'),
        section('Detalle por año', years.length + ' periodos históricos', years.length ? h('div', { className: 'sav-year-list' }, years.map((item, index) => h('article', { className: 'sav-year', key: item.year + '-' + index, 'data-savings-year': item.year }, h('div', { className: 'sav-year-head' }, h('b', null, item.year), h('span', { 'data-current': Number(String(item.year).slice(0, 4)) === new Date().getFullYear() }, Number(String(item.year).slice(0, 4)) === new Date().getFullYear() ? 'EN CURSO' : 'DISPONIBLE')), h('div', { className: 'sav-year-grid' }, h('div', null, h('span', null, 'Ahorro'), h('b', null, moneyOrDash(item.capital)), h('span', null, item.capital_cell_kind)), h('div', null, h('span', null, 'Rendimiento'), h('b', null, moneyOrDash(item.yield)), h('span', null, item.yield_cell_kind)))))) : h('div', { className: 'sav-card' }, h('span', { className: 'sav-kicker' }, 'No hay periodos DP:DW atribuibles a este Folio.'))),
        h('div', { className: 'sav-actions', 'data-savings-actions': '' }, ACTION_ORDER.map((action) => { const enabled = Boolean(dashboard.actions && dashboard.actions[action] && canWriteRequests); return h('button', { type: 'button', key: action, className: 'sav-action', 'data-primary': action === 'WITHDRAW', disabled: !enabled, 'aria-disabled': String(!enabled), onClick: enabled ? () => setSheet(action) : undefined, 'data-savings-action': action, 'data-savings-enabled': String(enabled) }, h('span', null, icon(ACTION_ICONS[action], 17)), ACTION_LABELS[action]); })),
        h('div', { className: 'sav-alert', 'data-savings-readonly': '' }, 'Consulta de sólo lectura. Las solicitudes no están habilitadas para tu cuenta en este momento.'),
        section('Mi ahorro', 'Identidad legacy', h('div', { className: 'sav-card', 'data-savings-enrollment': '' }, enrollment ? h(React.Fragment, null, h('div', { className: 'sav-enroll-head' }, h('span', { className: 'sav-icon' }, icon('calendar', 19)), h('div', null, h('b', null, enrollment.status || 'Estado por confirmar'), h('span', null, 'Folio legacy ' + (participant.legacy_folio || 'por confirmar')))), h('div', { className: 'sav-rows' }, detailRow('Fecha de inicio', shortDate(enrollment.enrollment_started_at)), detailRow('Monto vigente', enrollment.current_contribution_amount == null ? null : money(enrollment.current_contribution_amount)), detailRow('PROCESS histórico', enrollment.historical_process), detailRow('PROCESS actual', enrollment.current_process), detailRow('Frecuencia inferida', enrollment.frequency === 'MONTHLY' ? 'Mensual' : enrollment.frequency === 'TWICE_MONTHLY' ? 'Quincenal' : null), detailRow('Tipo de celda del monto', enrollment.amount_cell_kind))) : h('span', { className: 'sav-kicker' }, 'Sin evidencia de inscripción vinculada.'))),
        section('Próximos registros', 'AA:DO · evidencia esperada', h('div', { className: 'sav-card', 'data-savings-upcoming': '' }, (dashboard.upcoming || []).length ? dashboard.upcoming.slice(0, 8).map((item, index) => { const date = new Date(item.contribution_date + 'T12:00:00'); return h('div', { className: 'sav-next', key: item.contribution_date + '-' + index }, h('div', { className: 'sav-date' }, h('b', null, date.getDate()), h('span', null, date.toLocaleDateString('es-MX', { month: 'short' }))), h('div', { className: 'sav-next-copy' }, h('b', null, 'Monto esperado'), h('span', null, item.cell_kind + (item.process_snapshot ? ' · ' + item.process_snapshot : ''))), h('strong', null, money(item.expected_amount))); }) : h('span', { className: 'sav-kicker' }, 'No hay fechas futuras con valor en AA:DO.'))),
        section('Histórico AA:DO', 'Evidencia legacy · no es ledger', h(React.Fragment, null, h('div', { className: 'sav-history-tabs' }, h('button', { type: 'button', 'aria-pressed': historyYear === 'all', onClick: () => setHistoryYear('all') }, 'Todos'), historyYears.map((year) => h('button', { type: 'button', key: year, 'aria-pressed': historyYear === year, onClick: () => setHistoryYear(year) }, year))), h('div', { className: 'sav-card', 'data-savings-history': '' }, history.length ? history.map((item) => { const manual = item.cell_kind === 'MANUAL'; return h('div', { className: 'sav-tx', key: item.id }, h('span', { className: 'sav-tx-icon', 'data-debit': manual }, icon(manual ? 'edit' : 'check', 16)), h('div', null, h('b', null, manual ? 'Monto registrado manual' : 'Monto esperado'), h('span', null, shortDate(item.effective_date) + ' · ' + item.cell_kind)), h('strong', null, money(item.amount))); }) : h('span', { className: 'sav-kicker' }, 'No hay evidencia AA:DO en este filtro.')))),
        section('Retiros', (dashboard.withdrawals || []).length + ' registros', h('div', { className: 'sav-card', 'data-savings-withdrawals': '' }, (dashboard.withdrawals || []).length ? dashboard.withdrawals.map((item) => h('div', { className: 'sav-tx', key: item.id }, h('span', { className: 'sav-tx-icon', 'data-debit': true }, icon('cash', 16)), h('div', null, h('b', null, item.withdrawal_kind || 'Retiro'), h('span', null, shortDate(item.effective_date) + (item.status ? ' · ' + item.status : ''))), h('strong', { 'data-debit': true }, '−' + money(item.amount)))) : h('span', { className: 'sav-kicker' }, 'No hay retiros vinculados a este Folio.'))),
        section('Cambios de monto', (dashboard.plan_changes || []).length + ' registros', h('div', { className: 'sav-card', 'data-savings-plan-changes': '' }, (dashboard.plan_changes || []).length ? dashboard.plan_changes.map((item) => h('div', { className: 'sav-tx', key: item.id }, h('span', { className: 'sav-tx-icon' }, icon('edit', 16)), h('div', null, h('b', null, moneyOrDash(item.old_amount) + ' → ' + moneyOrDash(item.new_amount)), h('span', null, shortDate(item.effective_date) + (item.applied ? ' · ' + item.applied : ''))))) : h('span', { className: 'sav-kicker' }, 'No hay solicitudes de cambio vinculadas a este Folio.'))),
        section('Beneficiarios', (dashboard.beneficiaries || []).length + ' registrados', h('div', { className: 'sav-card', 'data-savings-beneficiaries': '' }, (dashboard.beneficiaries || []).length ? dashboard.beneficiaries.map((item) => detailRow(item.full_name, (item.relationship || 'Sin parentesco') + ' · ' + Number(item.percentage || 0).toFixed(2) + '%')) : h(React.Fragment, null, h('span', { className: 'sav-kicker' }, 'No hay beneficiarios registrados en el SHADOW.'), h('button', { type: 'button', className: 'sav-primary', disabled: !canWriteBeneficiaries, style: { marginTop: 12 } }, 'Registrar beneficiarios'))))
      ) : h('section', { className: 'sav-balance sav-empty', 'data-savings-empty': '' }, h('span', { className: 'sav-icon' }, icon('cash', 22)), h('h2', null, 'Ahorro no encontrado'), h('p', null, 'No encontramos un Folio de ahorro legacy vinculado de forma resuelta a tu cuenta.'), h('div', { className: 'sav-alert' }, 'Las solicitudes de inscripción no están habilitadas en esta etapa de sólo lectura.')))),
      sheet === 'INFO' && h(Sheet, { title: 'Acerca de Ahorro', onClose: () => setSheet('') }, h('p', null, 'La pantalla lee el espejo SHADOW certificado. Google legacy continúa como autoridad hasta un cutover futuro.'), h('div', { className: 'sav-alert' }, 'El saldo mostrado es Q. Capital y rendimiento histórico provienen directamente de DP:DW; no se calculan ni acreditan rendimientos y no se usa un ledger canónico.')));
  }
  window.SavingsScreen = SavingsScreen;
})();
