'use strict';
const assert=require('assert'),fs=require('fs'); const read=(p)=>fs.readFileSync(p,'utf8');
const migration=read('supabase/migrations/20260821000500_create_admin_authorization.sql');
const repository=read('app/admin-repository.js'), screen=read('app/screens-admin.jsx'), store=read('app/admin-store.jsx'), branding=read('app/screens-admin-branding.jsx'), bundle=read('app/bundle.js');
assert(migration.includes('create table public.admin_assignments'));
assert(migration.includes('auth_user_id uuid not null unique references auth.users'));
assert(migration.includes("public.has_admin_permission('assets.write')"));
assert(migration.includes('create table public.admin_audit_log'));
assert(migration.includes('h008_storage_admin_insert'));
assert(!store.includes('suti_admin_auth_v1'));
assert(!screen.includes('S().login()'));
assert(screen.includes("app.admin.phase !== 'authorized'"));
assert(screen.includes("app.admin.has('assets.write')"));
assert(repository.includes("rpc('get_admin_access_context')"));
assert(repository.includes("from('app_settings').update"));
assert(repository.includes("storage.from('app-assets').upload"));
assert(repository.includes('React.useEffect(()=>{retry();},[])'));
assert(read('app/affiliate-auth.js').includes('adminOnly: !affiliate && isAdmin'));
assert(read('app/app.jsx').includes("defaultTab: auth.affiliateView ? 'home' : 'admin'"));
assert(branding.includes("'data-h008-admin-editor'"));
assert(branding.includes('install_screen_${i+1}_asset_id'));
assert(![repository,screen,branding,bundle].some(x=>/SUPABASE_SECRET_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_ACCESS_TOKEN|SUPABASE_DB_PASSWORD/.test(x)));
console.log('H-008 static verification PASS: real Supabase assignment gate, RLS writer, audit and no browser secret.');
