/* Static Phase 4 membership authority and Claude UI checks. */
'use strict';
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');const read=(p)=>fs.readFileSync(path.join(root,p),'utf8'),must=(x,m)=>{if(!x)throw new Error(m);};
const sql=read('supabase/migrations/20260821001000_create_phase4_memberships.sql'),recovery=read('supabase/recovery/20260821001000_create_phase4_memberships_recovery.sql'),protect=read('supabase/migrations/20260821001001_protect_phase4_membership_history.sql'),protectRecovery=read('supabase/recovery/20260821001001_restore_phase4_membership_history_policy.sql'),repo=read('app/membership-repository.js'),store=read('app/membership-store.jsx'),publicUi=read('app/screens-membresias.jsx'),admin=read('app/screens-admin-membresias.jsx'),adminRoot=read('app/screens-admin.jsx'),bundle=read('app/bundle.js'),snap=read('data/phase4-memberships-source.json');
for(const text of ['create table public.membership_offerings','enable row level security','force row level security',"has_admin_permission('memberships.write')",'1098C6D59E933DC6EF85E043BA736CA216A2356B517A1C56DBB2F51334A9DEA6'])must(sql.includes(text),'schema/provenance missing '+text);
must(recovery.includes('drop table if exists public.membership_offerings'),'recovery missing');must(protect.includes("record_origin='ADMIN_PHASE4'")&&protect.includes('grant update(company_raw,concept,amount,installments,logo_asset_id,enabled,sort_order,updated_at)')&&protectRecovery.includes('membership_offerings_admin_write'),'historical protection/recovery missing');must((sql.match(/'HISTORICAL_IMPORT'/g)||[]).length>=7,'six historical rows missing');must(!store.includes('localStorage')&&!store.includes('SEED')&&!store.includes('window.DATA'),'local membership authority remains');must(repo.includes("from('membership_offerings')")&&repo.includes('uploadManagedAsset'),'repository incomplete');must(publicUi.includes('Membresías')&&publicUi.includes('Paga en parcialidades vía nómina')&&publicUi.includes('useReveal')&&publicUi.includes('data-memberships-state'),'public Claude structure missing');must(admin.includes('Nueva membresía')&&admin.includes('Monto (MXN)')&&admin.includes('Pagos')&&admin.includes('Subir imagen')&&admin.includes("A.has('memberships.write')")&&admin.includes("m.record_origin==='ADMIN_PHASE4'"),'Admin Claude CRUD/history guard missing');must(adminRoot.includes("membresias:'memberships.read'")&&adminRoot.includes("view==='membresias'"),'Admin route missing');must(bundle.includes('/* @@file membership-repository.js */')&&bundle.includes('NO_PRODUCTIVE_MEMBERSHIP_RESET'),'bundle/source mismatch');must(JSON.parse(snap).rows.length===6,'snapshot row count');
must(repo.includes('row.activo===undefined?row.enabled!==false:row.activo!==false'),'UI enabled value does not override stale projection');
must(repo.includes("update({enabled:next})")&&repo.includes('MEMBERSHIP_ENABLED_MISMATCH')&&store.includes('MembershipRepository.setEnabled(m.id,!m.activo)'),'dedicated enabled writer missing');
must(admin.includes("membershipStore.state().phase === 'idle'")&&admin.includes('membershipStore.load(false)'),'Admin membership catalog does not initialize its authority');
console.log('Phase 4 static verification PASS: six historical memberships, Supabase-only repository, secure Admin CRUD and Claude UI structure present.');
