/* Static Phase 2 authority, security, UI-contract and bundle checks. */
'use strict';
const fs=require('fs');const path=require('path');const root=path.resolve(__dirname,'..');
const read=(name)=>fs.readFileSync(path.join(root,name),'utf8');const must=(ok,msg)=>{if(!ok)throw new Error(msg);};
const sql=read('supabase/migrations/20260821000800_complete_phase2_content.sql');
const recovery=read('supabase/recovery/20260821000800_complete_phase2_content_recovery.sql');
const repo=read('app/admin-repository.js');const publicRepo=read('app/content-repositories.js');
const news=read('app/screens-admin-news.jsx');const menu=read('app/screens-admin.jsx');
const dataSource=read('app/data.jsx');const oldAdminStore=read('app/admin-store.jsx');
const educationMigration=read('supabase/migrations/20260821000801_phase2_education_provenance.sql');const educationSource=read('data/phase2-education-source.json');const educationImport=read('scripts/import-phase2-education.py');
const educationRecovery=read('scripts/recover-phase2-education.py');const visualCrud=read('app/screens-admin-visual-crud.jsx');
const home=read('app/screens-home-r2.jsx');const app=read('app/app.jsx');const bundle=read('app/bundle.js');const html=read('SutiApp.html');const sw=read('sw.js');
const bundleVersion=Number((html.match(/bundle\.js\?v=(\d+)/)||[])[1]);const cacheVersion=Number((sw.match(/sutiapp-v(\d+)/)||[])[1]);
['news_articles','news_settings','educational_resources','managed_copy_overrides'].forEach((table)=>{
  must(sql.includes('alter table public.'+table+' enable row level security'),'RLS missing '+table);
  must(sql.includes('alter table public.'+table+' force row level security'),'forced RLS missing '+table);
  must(recovery.includes('drop table if exists public.'+table),'recovery missing '+table);
});
must(sql.includes("Starts empty; DATA/adminStore seeds are never imported"),'news must start empty');
must(educationMigration.includes('source_payload jsonb')&&educationMigration.includes('educational_resources_historical_source_idx'),'education provenance missing');
must(JSON.parse(educationSource).sheets.education.values.length===29&&JSON.parse(educationSource).sheets.tutorials.values.length===5,'education snapshot count mismatch');
must(educationImport.includes("'published':False")&&educationImport.includes("storage/v1/object/app-assets"),'education import publication/storage contract missing');
must(educationImport.includes('if applied:return'),'education import is not idempotent');
must(educationRecovery.includes('external reference')&&educationRecovery.includes("parser.add_argument('--apply'"),'education recovery guard missing');
must(visualCrud.includes("aria-label':'Subir'")&&visualCrud.includes("aria-label':'Bajar'")&&visualCrud.includes("item.provenance==='ADMIN_PHASE2'"),'education order/history controls missing');
must(repo.includes("permission:'news.write'")&&repo.includes("permission:'content.write'"),'backend permissions missing');
must(repo.includes('removeManaged')&&repo.includes('reorderManaged'),'editorial CRUD incomplete');
must(publicRepo.includes("from('news_articles')")&&!publicRepo.includes('DATA'),'public news fallback found');
must(news.includes("listManaged('news')")&&!news.includes('window.adminStore'),'News Admin still local');
must(!dataSource.match(/window\.DATA\s*=\s*\{[^}]*noticias/),'DATA still exports news');
must(!oldAdminStore.includes('localStorage.getItem(NKEY)')&&!oldAdminStore.includes('localStorage.setItem(NKEY)')&&!oldAdminStore.includes('localStorage.getItem(NSKEY)'),'local news persistence remains active');
must(!news.includes('PENDING BACKEND')&&news.includes('segmentación por perfil aún no está disponible')&&news.includes('reorderManaged'),'News UI user-facing pending/ordering contract missing');
must(news.includes('pendingRef.current')&&news.includes('discardAsset'),'News upload cancellation cleanup missing');
must(!fs.existsSync(path.join(root,'app/copy-store.jsx'))&&!fs.existsSync(path.join(root,'app/live-text.jsx')),'retired live-copy sources remain');
must(!publicRepo.includes('managed_copy_overrides')&&!repo.includes('saveCopy')&&!repo.includes('removeCopy'),'retired live-copy repository surface remains');
must(menu.includes("noticias:'news.read'")&&menu.includes("education:'content.read'")&&menu.includes("education:['education','tutorials']")&&menu.includes("key+'.read'"),'Admin modules not permission-gated');
must(home.includes('data-phase2-news-state')&&app.includes('useEditorialContent'),'News states missing');
must(bundle.includes('/* @@file content-repositories.js */')&&!bundle.includes('/* @@file copy-store.jsx */')&&!bundle.includes('/* @@file live-text.jsx */'),'bundle/source divergence');
must(Number.isInteger(bundleVersion)&&bundleVersion>=95&&Number.isInteger(cacheVersion)&&cacheVersion>=40,'PWA version below Phase 2 baseline');
console.log('Phase 2 static verification PASS: empty news authority, secure editorial CRUD, retired live copy, explicit states, no local fallback.');
