'use strict';
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const must=(v,m)=>{if(!v)throw new Error(m);};
const edge=read('supabase/functions/financial-legacy/index.ts');
const repo=read('app/financial-legacy-repository.js');
const loan=read('app/screens-loan.jsx');
const dashboard=read('app/screens-financiera.jsx');
const market=read('app/screens-marketplace.jsx');
const finance=read('app/finance-store.jsx');
const funds=read('app/funds-store.jsx');
const fincat=read('app/fincat-store.jsx');
const bundle=read('app/bundle.js');
const operations=read('app/operations-store.jsx');
const catalog=read('app/screens-catalogo.jsx');
const handoff=read('google-apps-script/financial-handoff/Code.gs');
const adminRequests=read('app/screens-admin-requests.jsx');
const writer=read('supabase/migrations/20260823000100_final_approved_loan_export_writer.sql');
const recovery=read('supabase/recovery/20260823000100_final_approved_loan_export_writer.sql');
const loanResolver=read('supabase/migrations/20260826000100_authenticated_loan_snapshot_quote_rpc.sql');
must(edge.includes('get_current_affiliate_financial_context')&&edge.includes('rulesForProfile(rules, profile)'),'backend identity and current financial-profile derivation missing');
must(edge.includes('ACTION_KEYS')&&edge.includes('INVALID_REQUEST'),'identity-selector rejection contract missing');
must(edge.includes('FINANCIAL_LEGACY_API_TOKEN')&&!repo.includes('FINANCIAL_LEGACY_API_TOKEN'),'legacy secret exposed to browser');
must(edge.includes('Cache-Control')&&edge.includes('no-store')&&edge.includes('ALLOWED_APP_ORIGINS'),'cache/CORS boundary missing');
must(edge.includes('overview: new Set')&&edge.includes('resolveEligibility: new Set')&&edge.includes('resolveSimulation: new Set'),'financial resolver actions missing');
must(edge.includes('handoff: new Set(["action", "request_id"])')&&edge.includes('ADMIN_APPROVAL_REQUIRED')&&edge.includes('program_requests.write'),'handoff admin boundary missing');
must(edge.includes('request.status !== "approved"')&&edge.includes('"ready_for_handoff", "in_progress", "failed", "handed_off"'),'approval/export state gate missing');
must(edge.includes('FINANCIAL_LEGACY_API_URL')&&edge.includes('FINANCIAL_LEGACY_API_TOKEN')&&edge.includes('complete_financial_request_export'),'handoff server boundary missing');
must(!repo.includes('FINANCIAL_HANDOFF_SECRET')&&repo.includes("action: 'handoff'"),'handoff secret exposed or browser boundary missing');
must(handoff.includes("HANDOFF_SHEET_NAME = 'SutiApp Financial Handoff'")&&handoff.includes("TARGET_SHEET_NAME = 'Historial de solicitudes'")&&handoff.includes('LockService.getScriptLock()'),'Apps Script isolated lock boundary missing');
must(handoff.includes('createTextFinder(requestId).matchEntireCell(true)')&&handoff.includes("return failure_('UNAUTHORIZED')"),'Apps Script idempotency/security missing');
must(handoff.includes('TARGET_HEADERS')&&handoff.includes('TARGET_VERIFICATION_FAILED')&&handoff.includes("'processing'")&&handoff.includes("'processed'"),'exact append/recovery contract missing');
must(writer.includes('financial_request_export_audit')&&writer.includes('begin_financial_request_export')&&writer.includes('complete_financial_request_export')&&writer.includes("financial_processing_status='in_progress'"),'Supabase export audit/state machine missing');
must(recovery.includes('RECOVERY_BLOCKED_EXPORTED_GOOGLE_ROWS_REQUIRE_OWNER_RECONCILIATION'),'safe recovery guard missing');
for(const copy of ['Lista para enviar','Enviando a gestión…','Enviada a gestión','No se pudo enviar','Reintentar envío']) must(adminRequests.includes(copy),'Admin export state/copy missing: '+copy);
must(adminRequests.includes("FinancialLegacyRepository.handoffRequest(row.id)")&&adminRequests.includes("financial_processing_status==='handed_off'"),'Admin retry/final-state control missing');
must(adminRequests.includes('exportErrorCopy')&&adminRequests.includes('Falta un documento requerido.')&&!/LockService|RLS|backend|legacy writer/.test(adminRequests),'Admin business error copy missing or technical copy exposed');
must(!operations.includes('handoffRequest(')&&!operations.includes('retryPendingHandoffs')&&!operations.includes('handoffAttempts'),'history must not export before admin approval');
must(!catalog.includes('handoffRequest(created.id)'),'user submission must write Supabase only');
must(!/\bRATE\s*=|FIN_RATE|months\s*=\s*quincenas|tasaMensual|DATA\.user|localStorage/.test(loan),'local loan authority/calculation remains');
must(dashboard.includes('useFinancialLegacy')&&!dashboard.includes('D().user'),'financial summary fallback remains');
must(market.includes("title: 'Simula tu financiamiento'")&&market.includes('requestQuote(program.id, amount, term)'),'Marketplace resolver integration missing');
must(!/FIN_RATE|finCalc|financeStore|DATA\.user|tasaMensual/.test(market),'Marketplace local financial prototype remains');
for(const text of [finance,funds,fincat]) must(text.includes('FINANCIAL_LEGACY_READ_ONLY')&&!text.includes('localStorage'),'browser financial writer remains');
for(const label of ['Monto','Depósito','Documentos','Resumen','Simula tu préstamo','Ver desglose completo']) must(loan.includes(label),'Claude loan structure missing: '+label);
for(const retired of ['Impacto en tu quincena','Tu talón de pago','data-payroll-impact','data-payroll-card']) must(!loan.includes(retired),'retired payroll card remains: '+retired);
must(bundle.includes('FINANCIAL_LEGACY_READ_ONLY')&&bundle.includes('data-step-simulator-v2'),'bundle stale');
must(edge.includes('readCriteriaRules')&&edge.includes('resolve_suti_loan_quote_contract')&&loanResolver.includes('round(p_amount*v_rate_factor*p_term,2)')&&loanResolver.includes('v_fee_per_payment numeric := 15'),'server-side Google criteria calculation missing');
console.log('Phase 7 static verification PASS: backend-derived profile, live Google resolver, server-side calculation, no browser financial calculation/storage.');
