'use strict';
const assert=require('assert'),fs=require('fs');const read=(p)=>fs.readFileSync(p,'utf8');
const migration=read('supabase/migrations/20260821000600_enable_visual_admin_crud.sql');
const recovery=read('supabase/recovery/20260821000600_disable_visual_admin_crud.sql');
const repository=read('app/admin-repository.js');const ui=read('app/screens-admin-visual-crud.jsx');const screen=read('app/screens-admin.jsx');
assert(migration.includes("record_origin = 'ADMIN_H009'"));
assert(migration.includes('companies_public_read')&&migration.includes('using (enabled)'));
assert(migration.includes('institutional_documents_public_read'));
assert(migration.includes("public.has_admin_permission('documents.write')"));
assert(migration.includes('replace_company_asset'));
assert(migration.includes('revoke insert, update, delete on public.companies, public.banners, public.popups'));
assert(recovery.includes('Recovery blocked: preserve ADMIN_H009 records'));
for(const method of ['listManaged','saveManaged','setEnabled','uploadManagedAsset','discardAsset','replaceCompanyAsset'])assert(repository.includes(method));
for(const kind of ['banners','popups','companies','documents'])assert(ui.includes(`${kind}:`));
assert(screen.includes("const allowedViews = ['menu'].concat(MODULES.map((m)=>m.id))"));
assert(screen.includes('window.VisualCrudModule'));
assert(!screen.includes("body = React.createElement(PopupsModule"));
assert(read('app/visual-repositories.js').includes("query.eq('enabled', true).order('sort_order'"));
assert(read('app/institutional-repositories.js').includes("query.eq('enabled', true)"));
assert(![repository,ui,screen,read('app/bundle.js')].some((x)=>/SUPABASE_SECRET_KEY|SUPABASE_SERVICE_ROLE_KEY|SUPABASE_ACCESS_TOKEN|SUPABASE_DB_PASSWORD/.test(x)));
console.log('H-009 static verification PASS: Supabase-only CRUD modules, column-scoped grants, public enabled filters, RLS and no browser secret.');
