begin;
set local lock_timeout='2s';set local statement_timeout='60s';
lock table public.admin_assignments,public.admin_section_responsibilities,public.admin_roles,public.admin_role_permissions,public.admin_audit_log,public.companies,public.company_assets,public.company_benefit_profiles,public.company_benefits,public.company_audience_rules,public.marketplace_company_memberships,public.company_portal_subscriptions,public.company_portal_plans in share row exclusive mode;
do $recover$ declare r record;begin
 if (select definition from public.admin_permission_fix_recovery_20260924000200 where key='state') is distinct from md5(concat_ws('|',md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.admin_assignments x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.admin_section_responsibilities x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.admin_roles x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.admin_role_permissions x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.admin_audit_log x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.companies x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.company_assets x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.company_benefit_profiles x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.company_benefits x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.company_audience_rules x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.marketplace_company_memberships x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.company_portal_subscriptions x),'[]')),md5(coalesce((select jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text from public.company_portal_plans x),'[]')))) then raise exception 'RECOVERY_BLOCKED_DATA_OR_AUTHORIZATION_USE';end if;
 for r in select * from public.admin_permission_fix_recovery_20260924000200 where key not in('state','membership_policy','new_guard') loop
  if r.applied_hash is distinct from md5(pg_get_functiondef(r.key::regprocedure)) then raise exception 'RECOVERY_BLOCKED_FUNCTION_DRIFT';end if;
  if r.security is distinct from (select jsonb_build_array(oid,proowner,proacl::text) from pg_proc where oid=r.key::regprocedure) then raise exception 'RECOVERY_BLOCKED_FUNCTION_SECURITY_DRIFT';end if;
 end loop;
 if (select applied_hash from public.admin_permission_fix_recovery_20260924000200 where key='membership_policy') is distinct from (select md5(pg_get_expr(polqual,polrelid)) from pg_policy where polrelid='public.marketplace_company_memberships'::regclass and polname='marketplace_memberships_self_read') then raise exception 'RECOVERY_BLOCKED_POLICY_DRIFT';end if;
 if (select security from public.admin_permission_fix_recovery_20260924000200 where key='membership_policy') is distinct from (select jsonb_build_array(polpermissive,polroles::text,polcmd,pg_get_expr(polwithcheck,polrelid)) from pg_policy where polrelid='public.marketplace_company_memberships'::regclass and polname='marketplace_memberships_self_read') then raise exception 'RECOVERY_BLOCKED_POLICY_SECURITY_DRIFT';end if;
 if (select applied_hash from public.admin_permission_fix_recovery_20260924000200 where key='new_guard') is distinct from md5(pg_get_functiondef('public.enforce_admin_company_module_scope()'::regprocedure)) then raise exception 'RECOVERY_BLOCKED_GUARD_DRIFT';end if;
 if (select security from public.admin_permission_fix_recovery_20260924000200 where key='new_guard') is distinct from (select jsonb_build_array(oid,proowner,proacl::text) from pg_proc where oid='public.enforce_admin_company_module_scope()'::regprocedure) then raise exception 'RECOVERY_BLOCKED_GUARD_SECURITY_DRIFT';end if;
 if not exists(select 1 from pg_trigger where tgrelid='public.company_benefit_profiles'::regclass and tgname='admin_company_module_scope' and tgenabled='O' and tgfoid='public.enforce_admin_company_module_scope()'::regprocedure and tgtype=31) then raise exception 'RECOVERY_BLOCKED_TRIGGER_DRIFT';end if;
if not exists(select 1 from pg_trigger where tgrelid='public.company_benefits'::regclass and tgname='admin_company_module_scope' and tgenabled='O' and tgfoid='public.enforce_admin_company_module_scope()'::regprocedure and tgtype=31) then raise exception 'RECOVERY_BLOCKED_TRIGGER_DRIFT';end if;
if not exists(select 1 from pg_trigger where tgrelid='public.company_audience_rules'::regclass and tgname='admin_company_module_scope' and tgenabled='O' and tgfoid='public.enforce_admin_company_module_scope()'::regprocedure and tgtype=31) then raise exception 'RECOVERY_BLOCKED_TRIGGER_DRIFT';end if;
 for r in select * from public.admin_permission_fix_recovery_20260924000200 where key not in('state','membership_policy','new_guard') loop execute r.definition;end loop;
 execute 'alter policy marketplace_memberships_self_read on public.marketplace_company_memberships using('||(select definition from public.admin_permission_fix_recovery_20260924000200 where key='membership_policy')||')';
end $recover$;
drop trigger admin_company_module_scope on public.company_benefit_profiles;
drop trigger admin_company_module_scope on public.company_benefits;
drop trigger admin_company_module_scope on public.company_audience_rules;
drop function public.enforce_admin_company_module_scope();
drop table public.admin_permission_fix_recovery_20260924000200;
commit;
