begin;
-- No automatic rollback after actual user assignments. Preserve history instead.
do $$ begin
 if exists(select 1 from public.admin_assignments a join public.admin_roles r on r.id=a.role_id where r.code='module_admin')
 or exists(select 1 from public.admin_section_responsibilities g join public.admin_section_definitions d on d.section_key=g.section_key where d.module_key is not null)
 or exists(select 1 from public.admin_audit_log where resource='admin_user_modules') then raise exception 'RECOVERY_BLOCKED_MODULE_ACCESS_HISTORY'; end if;
 if exists(select 1 from public.admin_module_access_recovery where applied_hash<>md5(pg_get_functiondef(('public.'||signature)::regprocedure))) then raise exception 'RECOVERY_BLOCKED_NEWER_FUNCTION'; end if;
end $$;
do $$ declare item record; begin
 for item in select definition from public.admin_module_access_recovery loop execute item.definition; end loop;
end $$;
drop policy module_scope_insert on public.finance_catalog_presentation;
drop policy module_scope_update on public.finance_catalog_presentation;
drop policy module_scope_delete on public.finance_catalog_presentation;
drop policy module_scope_insert on public.operational_workflows;
drop policy module_scope_update on public.operational_workflows;
drop policy module_scope_delete on public.operational_workflows;
drop policy module_scope_insert on public.operational_workflow_stages;
drop policy module_scope_update on public.operational_workflow_stages;
drop policy module_scope_delete on public.operational_workflow_stages;
drop policy module_scope_insert on public.operational_request_tracking;
drop policy module_scope_update on public.operational_request_tracking;
drop policy module_scope_delete on public.operational_request_tracking;
drop policy module_scope_insert on public.screen_access_policies;
drop policy module_scope_update on public.screen_access_policies;
drop policy module_scope_delete on public.screen_access_policies;
drop policy module_scope_insert on public.segmentation_catalog_entries;
drop policy module_scope_update on public.segmentation_catalog_entries;
drop policy module_scope_delete on public.segmentation_catalog_entries;
drop policy module_scope_insert on public.company_popup_proposals;
drop policy module_scope_update on public.company_popup_proposals;
drop policy module_scope_delete on public.company_popup_proposals;
drop policy module_scope_insert on public.app_settings;
drop policy module_scope_update on public.app_settings;
drop policy module_scope_delete on public.app_settings;
drop policy module_scope_insert on public.educational_resources;
drop policy module_scope_update on public.educational_resources;
drop policy module_scope_delete on public.educational_resources;
drop policy module_scope_insert on public.institutional_programs;
drop policy module_scope_update on public.institutional_programs;
drop policy module_scope_delete on public.institutional_programs;
drop policy module_scope_insert on public.institutional_documents;
drop policy module_scope_update on public.institutional_documents;
drop policy module_scope_delete on public.institutional_documents;
drop policy module_scope_insert on public.directory_members;
drop policy module_scope_update on public.directory_members;
drop policy module_scope_delete on public.directory_members;
drop policy module_scope_insert on public.minutes;
drop policy module_scope_update on public.minutes;
drop policy module_scope_delete on public.minutes;
drop policy module_scope_insert on public.news_articles;
drop policy module_scope_update on public.news_articles;
drop policy module_scope_delete on public.news_articles;
drop policy module_scope_insert on public.news_settings;
drop policy module_scope_update on public.news_settings;
drop policy module_scope_delete on public.news_settings;
drop policy module_scope_insert on public.banners;
drop policy module_scope_update on public.banners;
drop policy module_scope_delete on public.banners;
drop policy module_scope_insert on public.popups;
drop policy module_scope_update on public.popups;
drop policy module_scope_delete on public.popups;
drop policy module_scope_insert on public.company_benefit_profiles;
drop policy module_scope_update on public.company_benefit_profiles;
drop policy module_scope_delete on public.company_benefit_profiles;
drop policy module_scope_insert on public.company_benefits;
drop policy module_scope_update on public.company_benefits;
drop policy module_scope_delete on public.company_benefits;
drop policy module_scope_insert on public.company_audience_rules;
drop policy module_scope_update on public.company_audience_rules;
drop policy module_scope_delete on public.company_audience_rules;
drop policy module_scope_requests on public.program_requests;
drop policy module_scope_read on public.operational_workflows;
drop policy module_scope_read on public.operational_workflow_stages;
drop policy module_scope_read on public.operational_request_tracking;
drop policy module_scope_read on public.screen_access_policies;
drop policy module_scope_read on public.company_popup_proposals;
drop policy module_scope_insert on public.app_assets;
drop policy module_scope_update on public.app_assets;
drop policy module_scope_delete on public.app_assets;
drop policy module_scope_insert on storage.objects;
drop policy module_scope_update on storage.objects;
drop policy module_scope_delete on storage.objects;
drop policy module_scope_sources on public.asset_sources;
drop function public.save_admin_user_modules(text,text,text[],text);
drop function public.get_admin_user_modules(text);
drop function public.admin_user_module_version(uuid);
drop function public.list_admin_module_catalog();
drop function public.list_module_general_requests(uuid);
drop function public.admin_request_module_boundary(uuid);
drop function public.admin_asset_module_boundary(text,text);
drop function public.module_effective_permissions();
drop function public.admin_module_boundary(text[],text);
drop function public.has_admin_module(text,text);
drop function public.is_module_admin();
drop function public.module_prior_get_admin_access_context();
drop function public.module_prior_has_section_action(text,text);
drop function public.module_prior_has_admin_permission(text);
delete from public.admin_roles where code='module_admin';
delete from public.admin_section_definitions where module_key is not null;
alter table public.admin_section_definitions drop column module_key,drop column module_read_permissions,drop column module_write_permissions,drop column module_sections,drop column module_total_only,drop column module_order;
drop table public.admin_module_access_recovery;
notify pgrst,'reload schema';
commit;
