begin;
-- Refuse recovery after business activity; never erase history.
do $$ begin
 if (select md5(coalesce(string_agg((to_jsonb(t)-array['public_details'])::text,'' order by (to_jsonb(t)-array['public_details'])::text),'')) from public.companies t)<>'7aae40d6724690c55601d0c7a4761d35' then raise exception 'RECOVERY_BLOCKED_companies_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t))::text,'' order by (to_jsonb(t))::text),'')) from public.company_assets t)<>'8c85ac2d56b3018cee080a3d3229ac6b' then raise exception 'RECOVERY_BLOCKED_company_assets_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t)-array['description','conditions'])::text,'' order by (to_jsonb(t)-array['description','conditions'])::text),'')) from public.company_benefit_profiles t)<>'d41d8cd98f00b204e9800998ecf8427e' then raise exception 'RECOVERY_BLOCKED_company_benefit_profiles_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t))::text,'' order by (to_jsonb(t))::text),'')) from public.company_benefits t)<>'d41d8cd98f00b204e9800998ecf8427e' then raise exception 'RECOVERY_BLOCKED_company_benefits_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t))::text,'' order by (to_jsonb(t))::text),'')) from public.company_audience_rules t)<>'d41d8cd98f00b204e9800998ecf8427e' then raise exception 'RECOVERY_BLOCKED_company_audience_rules_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t)-array['public_details','cover_asset_id'])::text,'' order by (to_jsonb(t)-array['public_details','cover_asset_id'])::text),'')) from public.educational_resources t)<>'39a743d415962aef48721caa9b70a2ca' then raise exception 'RECOVERY_BLOCKED_educational_resources_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t))::text,'' order by (to_jsonb(t))::text),'')) from public.marketplace_products t)<>'d41d8cd98f00b204e9800998ecf8427e' then raise exception 'RECOVERY_BLOCKED_marketplace_products_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t))::text,'' order by (to_jsonb(t))::text),'')) from public.marketplace_promotions t)<>'d41d8cd98f00b204e9800998ecf8427e' then raise exception 'RECOVERY_BLOCKED_marketplace_promotions_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t)-array['payment_reference','payment_amount','accredited_by','accredited_at'])::text,'' order by (to_jsonb(t)-array['payment_reference','payment_amount','accredited_by','accredited_at'])::text),'')) from public.company_portal_subscriptions t)<>'d41d8cd98f00b204e9800998ecf8427e' then raise exception 'RECOVERY_BLOCKED_company_portal_subscriptions_CHANGED';end if;
 if (select md5(coalesce(string_agg((to_jsonb(t))::text,'' order by (to_jsonb(t))::text),'')) from public.marketplace_company_memberships t)<>'d41d8cd98f00b204e9800998ecf8427e' then raise exception 'RECOVERY_BLOCKED_marketplace_company_memberships_CHANGED';end if;
 if exists(select 1 from public.companies where public_details<>'{}') or exists(select 1 from public.educational_resources where public_details<>'{}' or cover_asset_id is not null) or exists(select 1 from public.company_benefit_profiles where description<>'' or conditions<>'') or exists(select 1 from public.educational_resource_favorites) or exists(select 1 from public.company_portal_plans where id::text like 'cc000000%' and updated_at<>created_at) then raise exception 'RECOVERY_BLOCKED_NEW_HISTORY';end if;
end $$;
drop policy education_favorite_self on public.educational_resource_favorites;
drop policy company_ficha_image_upload on storage.objects;
drop policy company_portal_plans_read on public.company_portal_plans;
drop policy agreement_product_insert on public.marketplace_products;
drop policy agreement_product_update on public.marketplace_products;
drop policy agreement_product_delete on public.marketplace_products;
drop policy agreement_product_read on public.marketplace_products;
drop policy agreement_product_asset_write on public.marketplace_product_assets;
create policy company_portal_plans_read on public.company_portal_plans for select to authenticated using((has_admin_permission('company_portal.read'::text) OR (EXISTS ( SELECT 1
   FROM company_portal_subscriptions s
  WHERE ((s.plan_id = s.id) AND is_marketplace_company_member(s.company_id))))));
drop trigger companies_section_action_guard on public.companies;
CREATE TRIGGER companies_section_action_guard BEFORE INSERT OR DELETE OR UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION enforce_section_row_action('companies', 'companies.write', 'enabled', 'sort_order', 'logo_asset_id', 'record_origin', 'ADMIN_H009');
drop trigger company_product_plan_guard on public.marketplace_products;
drop trigger company_promotion_plan_guard on public.marketplace_promotions;
drop trigger company_assets_section_action_guard on public.company_assets;
CREATE TRIGGER company_assets_section_action_guard BEFORE INSERT OR DELETE OR UPDATE ON public.company_assets FOR EACH ROW EXECUTE FUNCTION enforce_section_row_action('companies', 'companies.write', '', 'sort_order', 'asset_id', 'record_origin', 'ADMIN_SECTION_ROLLOUT');
drop trigger marketplace_products_section_action_guard on public.marketplace_products;
CREATE TRIGGER marketplace_products_section_action_guard BEFORE INSERT OR DELETE OR UPDATE ON public.marketplace_products FOR EACH ROW EXECUTE FUNCTION enforce_section_row_action('marketplace', 'marketplace.write', 'enabled', 'sort_order', '', 'record_origin', 'ADMIN_PHASE3');
drop trigger marketplace_product_assets_section_action_guard on public.marketplace_product_assets;
CREATE TRIGGER marketplace_product_assets_section_action_guard BEFORE INSERT OR DELETE OR UPDATE ON public.marketplace_product_assets FOR EACH ROW EXECUTE FUNCTION enforce_section_row_action('marketplace', 'marketplace.write', '', 'sort_order', 'asset_id', 'record_origin', 'ADMIN_PHASE3');
drop trigger educational_resources_section_action_guard on public.educational_resources;
CREATE TRIGGER educational_resources_section_action_guard BEFORE INSERT OR DELETE OR UPDATE ON public.educational_resources FOR EACH ROW EXECUTE FUNCTION enforce_section_row_action('education', 'content.write', 'published', 'sort_order', 'image_asset_id,document_asset_id', 'provenance', 'ADMIN_PHASE2');
drop table public.educational_resource_favorites;
drop function public.list_paid_company_ids();
drop function public.get_current_company_access();
drop function public.enforce_agreement_product_action();
drop function public.can_manage_agreement_product(uuid,text);
drop function public.accredit_company_plan(uuid,uuid,text,text,boolean,text);
drop function public.enforce_company_ficha_asset_action();
drop function public.attach_company_ficha_image(uuid,uuid,text);
drop function public.register_company_ficha_image(uuid,text,text,text,bigint);
drop function public.can_upload_company_ficha(text);
drop function public.save_agreement_ficha(jsonb);
drop function public.get_company_activity(uuid);
drop function public.list_public_convenios();
drop function public.enforce_company_plan_limits();
drop function public.save_company_ficha(uuid,jsonb);
drop function public.enforce_company_ficha_action();
drop function public.can_manage_company_ficha(uuid,text);
drop function public.company_is_paid(uuid);
drop function public.company_has_active_plan(uuid);
delete from public.company_portal_plans where id in ('cc000000-0000-4000-8000-000000000001','cc000000-0000-4000-8000-000000000002','cc000000-0000-4000-8000-000000000003');
alter table public.companies drop column public_details;
alter table public.educational_resources drop column public_details;
alter table public.educational_resources drop column cover_asset_id;
alter table public.company_benefit_profiles drop column description;
alter table public.company_benefit_profiles drop column conditions;
alter table public.company_portal_subscriptions drop column payment_reference;
alter table public.company_portal_subscriptions drop column payment_amount;
alter table public.company_portal_subscriptions drop column accredited_by;
alter table public.company_portal_subscriptions drop column accredited_at;
commit;
