begin;

update public.admin_section_definitions set enforcement_status='DESIGN_ONLY',updated_at=now()
where section_key in('education','tutorials','companies','agreements','banners','popups','documents','minutes','programs','marketplace');

do $$ declare r text;begin foreach r in array array['educational_resources','companies','company_assets','banners','popups','institutional_documents','minutes','institutional_programs','company_benefit_profiles','company_benefits','company_audience_rules','marketplace_categories','marketplace_products','marketplace_product_assets','marketplace_promotions'] loop execute format('drop trigger if exists %I_section_action_guard on public.%I',r,r);execute format('drop trigger if exists %I_section_action_audit on public.%I',r,r);end loop;end $$;

drop policy if exists education_section_write on public.educational_resources;drop policy if exists education_section_read on public.educational_resources;
create policy education_admin_write on public.educational_resources for all to authenticated using(public.has_admin_permission('content.write')) with check(public.has_admin_permission('content.write'));

drop policy if exists companies_section_insert on public.companies;drop policy if exists companies_section_update on public.companies;drop policy if exists companies_section_delete on public.companies;drop policy if exists companies_section_read on public.companies;
create policy companies_admin_insert on public.companies for insert to authenticated with check(public.has_admin_permission('companies.write') and record_origin='ADMIN_H009');
create policy companies_admin_update on public.companies for update to authenticated using(public.has_admin_permission('companies.write')) with check(public.has_admin_permission('companies.write'));
create policy companies_admin_delete on public.companies for delete to authenticated using(public.has_admin_permission('companies.write') and record_origin='ADMIN_H009');
drop policy if exists company_assets_section_write on public.company_assets;create policy company_assets_admin_all on public.company_assets for all to authenticated using(public.has_admin_permission('companies.write')) with check(public.has_admin_permission('companies.write'));

drop policy if exists banners_section_write on public.banners;drop policy if exists banners_section_read on public.banners;
create policy banners_admin_insert on public.banners for insert to authenticated with check(public.has_admin_permission('banners.write') and record_origin='ADMIN_H009');create policy banners_admin_update on public.banners for update to authenticated using(public.has_admin_permission('banners.write')) with check(public.has_admin_permission('banners.write'));create policy banners_admin_delete on public.banners for delete to authenticated using(public.has_admin_permission('banners.write') and record_origin='ADMIN_H009');
drop policy if exists popups_section_write on public.popups;drop policy if exists popups_section_read on public.popups;
create policy popups_admin_insert on public.popups for insert to authenticated with check(public.has_admin_permission('popups.write') and record_origin='ADMIN_H009');create policy popups_admin_update on public.popups for update to authenticated using(public.has_admin_permission('popups.write')) with check(public.has_admin_permission('popups.write'));create policy popups_admin_delete on public.popups for delete to authenticated using(public.has_admin_permission('popups.write') and record_origin='ADMIN_H009');

drop policy if exists documents_section_write on public.institutional_documents;drop policy if exists documents_section_read on public.institutional_documents;
create policy institutional_documents_admin_insert on public.institutional_documents for insert to authenticated with check(public.has_admin_permission('documents.write') and record_origin='ADMIN_H009');create policy institutional_documents_admin_update on public.institutional_documents for update to authenticated using(public.has_admin_permission('documents.write')) with check(public.has_admin_permission('documents.write'));create policy institutional_documents_admin_delete on public.institutional_documents for delete to authenticated using(public.has_admin_permission('documents.write') and record_origin='ADMIN_H009');

drop policy if exists minutes_section_write on public.minutes;drop policy if exists minutes_section_read on public.minutes;drop policy if exists minutes_public_read on public.minutes;create policy minutes_public_read on public.minutes for select to anon,authenticated using(true);create policy minutes_assets_admin_update on public.minutes for update to authenticated using(public.has_admin_permission('documents.write')) with check(public.has_admin_permission('documents.write'));
drop policy if exists programs_section_write on public.institutional_programs;drop policy if exists programs_section_read on public.institutional_programs;drop policy if exists institutional_programs_public_read on public.institutional_programs;create policy institutional_programs_public_read on public.institutional_programs for select to anon,authenticated using(true);create policy programs_assets_admin_update on public.institutional_programs for update to authenticated using(public.has_admin_permission('documents.write')) with check(public.has_admin_permission('documents.write'));

drop policy if exists company_profiles_section_write on public.company_benefit_profiles;drop policy if exists company_benefits_section_write on public.company_benefits;drop policy if exists company_audience_section_write on public.company_audience_rules;drop policy if exists company_profiles_section_read on public.company_benefit_profiles;drop policy if exists company_benefits_section_read on public.company_benefits;drop policy if exists company_audience_section_read on public.company_audience_rules;
create policy company_profiles_write on public.company_benefit_profiles for all to authenticated using(public.has_admin_permission('companies.write')) with check(public.has_admin_permission('companies.write'));create policy company_benefits_write on public.company_benefits for all to authenticated using(public.has_admin_permission('companies.write')) with check(public.has_admin_permission('companies.write'));create policy company_audience_write on public.company_audience_rules for all to authenticated using(public.has_admin_permission('segmentation.write')) with check(public.has_admin_permission('segmentation.write'));

drop policy if exists marketplace_categories_section_write on public.marketplace_categories;drop policy if exists marketplace_products_section_write on public.marketplace_products;drop policy if exists marketplace_product_assets_section_write on public.marketplace_product_assets;drop policy if exists marketplace_promotions_section_write on public.marketplace_promotions;
create policy marketplace_categories_admin_write on public.marketplace_categories for all to authenticated using(public.has_admin_permission('marketplace.write')) with check(public.has_admin_permission('marketplace.write'));create policy marketplace_products_admin_write on public.marketplace_products for all to authenticated using(public.has_admin_permission('marketplace.write')) with check(public.has_admin_permission('marketplace.write'));create policy marketplace_product_assets_admin_write on public.marketplace_product_assets for all to authenticated using(public.has_admin_permission('marketplace.write')) with check(public.has_admin_permission('marketplace.write'));create policy marketplace_promotions_admin_write on public.marketplace_promotions for all to authenticated using(public.has_admin_permission('marketplace.write')) with check(public.has_admin_permission('marketplace.write'));

drop policy if exists app_assets_section_owner_insert on public.app_assets;drop policy if exists app_assets_section_owner_update on public.app_assets;drop policy if exists app_assets_section_owner_delete on public.app_assets;drop policy if exists asset_sources_section_owner_insert on public.asset_sources;drop policy if exists section_owner_storage_insert on storage.objects;drop policy if exists section_owner_storage_update on storage.objects;drop policy if exists section_owner_storage_delete on storage.objects;
drop function if exists public.audit_section_row_action();drop function if exists public.enforce_section_row_action();drop function if exists public.section_row_required_actions(jsonb,jsonb,text,text,text,text[]);

-- Additive columns/definition remain so recovery never destroys content created after rollout.
commit;
